
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `CertificateCounter` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model CertificateCounter
 * 
 */
export type CertificateCounterModel = runtime.Types.Result.DefaultSelection<Prisma.$CertificateCounterPayload>

export type AggregateCertificateCounter = {
  _count: CertificateCounterCountAggregateOutputType | null
  _avg: CertificateCounterAvgAggregateOutputType | null
  _sum: CertificateCounterSumAggregateOutputType | null
  _min: CertificateCounterMinAggregateOutputType | null
  _max: CertificateCounterMaxAggregateOutputType | null
}

export type CertificateCounterAvgAggregateOutputType = {
  count: number | null
}

export type CertificateCounterSumAggregateOutputType = {
  count: number | null
}

export type CertificateCounterMinAggregateOutputType = {
  id: string | null
  typeEn: string | null
  typeBn: string | null
  count: number | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type CertificateCounterMaxAggregateOutputType = {
  id: string | null
  typeEn: string | null
  typeBn: string | null
  count: number | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type CertificateCounterCountAggregateOutputType = {
  id: number
  typeEn: number
  typeBn: number
  count: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type CertificateCounterAvgAggregateInputType = {
  count?: true
}

export type CertificateCounterSumAggregateInputType = {
  count?: true
}

export type CertificateCounterMinAggregateInputType = {
  id?: true
  typeEn?: true
  typeBn?: true
  count?: true
  createdAt?: true
  updatedAt?: true
}

export type CertificateCounterMaxAggregateInputType = {
  id?: true
  typeEn?: true
  typeBn?: true
  count?: true
  createdAt?: true
  updatedAt?: true
}

export type CertificateCounterCountAggregateInputType = {
  id?: true
  typeEn?: true
  typeBn?: true
  count?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type CertificateCounterAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which CertificateCounter to aggregate.
   */
  where?: Prisma.CertificateCounterWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of CertificateCounters to fetch.
   */
  orderBy?: Prisma.CertificateCounterOrderByWithRelationInput | Prisma.CertificateCounterOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.CertificateCounterWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` CertificateCounters from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` CertificateCounters.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned CertificateCounters
  **/
  _count?: true | CertificateCounterCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: CertificateCounterAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: CertificateCounterSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: CertificateCounterMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: CertificateCounterMaxAggregateInputType
}

export type GetCertificateCounterAggregateType<T extends CertificateCounterAggregateArgs> = {
      [P in keyof T & keyof AggregateCertificateCounter]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateCertificateCounter[P]>
    : Prisma.GetScalarType<T[P], AggregateCertificateCounter[P]>
}




export type CertificateCounterGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.CertificateCounterWhereInput
  orderBy?: Prisma.CertificateCounterOrderByWithAggregationInput | Prisma.CertificateCounterOrderByWithAggregationInput[]
  by: Prisma.CertificateCounterScalarFieldEnum[] | Prisma.CertificateCounterScalarFieldEnum
  having?: Prisma.CertificateCounterScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: CertificateCounterCountAggregateInputType | true
  _avg?: CertificateCounterAvgAggregateInputType
  _sum?: CertificateCounterSumAggregateInputType
  _min?: CertificateCounterMinAggregateInputType
  _max?: CertificateCounterMaxAggregateInputType
}

export type CertificateCounterGroupByOutputType = {
  id: string
  typeEn: string
  typeBn: string
  count: number
  createdAt: Date
  updatedAt: Date
  _count: CertificateCounterCountAggregateOutputType | null
  _avg: CertificateCounterAvgAggregateOutputType | null
  _sum: CertificateCounterSumAggregateOutputType | null
  _min: CertificateCounterMinAggregateOutputType | null
  _max: CertificateCounterMaxAggregateOutputType | null
}

type GetCertificateCounterGroupByPayload<T extends CertificateCounterGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<CertificateCounterGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof CertificateCounterGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], CertificateCounterGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], CertificateCounterGroupByOutputType[P]>
      }
    >
  >



export type CertificateCounterWhereInput = {
  AND?: Prisma.CertificateCounterWhereInput | Prisma.CertificateCounterWhereInput[]
  OR?: Prisma.CertificateCounterWhereInput[]
  NOT?: Prisma.CertificateCounterWhereInput | Prisma.CertificateCounterWhereInput[]
  id?: Prisma.StringFilter<"CertificateCounter"> | string
  typeEn?: Prisma.StringFilter<"CertificateCounter"> | string
  typeBn?: Prisma.StringFilter<"CertificateCounter"> | string
  count?: Prisma.IntFilter<"CertificateCounter"> | number
  createdAt?: Prisma.DateTimeFilter<"CertificateCounter"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"CertificateCounter"> | Date | string
}

export type CertificateCounterOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  typeEn?: Prisma.SortOrder
  typeBn?: Prisma.SortOrder
  count?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type CertificateCounterWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  typeEn?: string
  AND?: Prisma.CertificateCounterWhereInput | Prisma.CertificateCounterWhereInput[]
  OR?: Prisma.CertificateCounterWhereInput[]
  NOT?: Prisma.CertificateCounterWhereInput | Prisma.CertificateCounterWhereInput[]
  typeBn?: Prisma.StringFilter<"CertificateCounter"> | string
  count?: Prisma.IntFilter<"CertificateCounter"> | number
  createdAt?: Prisma.DateTimeFilter<"CertificateCounter"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"CertificateCounter"> | Date | string
}, "id" | "typeEn">

export type CertificateCounterOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  typeEn?: Prisma.SortOrder
  typeBn?: Prisma.SortOrder
  count?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.CertificateCounterCountOrderByAggregateInput
  _avg?: Prisma.CertificateCounterAvgOrderByAggregateInput
  _max?: Prisma.CertificateCounterMaxOrderByAggregateInput
  _min?: Prisma.CertificateCounterMinOrderByAggregateInput
  _sum?: Prisma.CertificateCounterSumOrderByAggregateInput
}

export type CertificateCounterScalarWhereWithAggregatesInput = {
  AND?: Prisma.CertificateCounterScalarWhereWithAggregatesInput | Prisma.CertificateCounterScalarWhereWithAggregatesInput[]
  OR?: Prisma.CertificateCounterScalarWhereWithAggregatesInput[]
  NOT?: Prisma.CertificateCounterScalarWhereWithAggregatesInput | Prisma.CertificateCounterScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"CertificateCounter"> | string
  typeEn?: Prisma.StringWithAggregatesFilter<"CertificateCounter"> | string
  typeBn?: Prisma.StringWithAggregatesFilter<"CertificateCounter"> | string
  count?: Prisma.IntWithAggregatesFilter<"CertificateCounter"> | number
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"CertificateCounter"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"CertificateCounter"> | Date | string
}

export type CertificateCounterCreateInput = {
  id?: string
  typeEn: string
  typeBn: string
  count?: number
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type CertificateCounterUncheckedCreateInput = {
  id?: string
  typeEn: string
  typeBn: string
  count?: number
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type CertificateCounterUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  typeEn?: Prisma.StringFieldUpdateOperationsInput | string
  typeBn?: Prisma.StringFieldUpdateOperationsInput | string
  count?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type CertificateCounterUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  typeEn?: Prisma.StringFieldUpdateOperationsInput | string
  typeBn?: Prisma.StringFieldUpdateOperationsInput | string
  count?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type CertificateCounterCreateManyInput = {
  id?: string
  typeEn: string
  typeBn: string
  count?: number
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type CertificateCounterUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  typeEn?: Prisma.StringFieldUpdateOperationsInput | string
  typeBn?: Prisma.StringFieldUpdateOperationsInput | string
  count?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type CertificateCounterUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  typeEn?: Prisma.StringFieldUpdateOperationsInput | string
  typeBn?: Prisma.StringFieldUpdateOperationsInput | string
  count?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type CertificateCounterCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  typeEn?: Prisma.SortOrder
  typeBn?: Prisma.SortOrder
  count?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type CertificateCounterAvgOrderByAggregateInput = {
  count?: Prisma.SortOrder
}

export type CertificateCounterMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  typeEn?: Prisma.SortOrder
  typeBn?: Prisma.SortOrder
  count?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type CertificateCounterMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  typeEn?: Prisma.SortOrder
  typeBn?: Prisma.SortOrder
  count?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type CertificateCounterSumOrderByAggregateInput = {
  count?: Prisma.SortOrder
}



export type CertificateCounterSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  typeEn?: boolean
  typeBn?: boolean
  count?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["certificateCounter"]>

export type CertificateCounterSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  typeEn?: boolean
  typeBn?: boolean
  count?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["certificateCounter"]>

export type CertificateCounterSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  typeEn?: boolean
  typeBn?: boolean
  count?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["certificateCounter"]>

export type CertificateCounterSelectScalar = {
  id?: boolean
  typeEn?: boolean
  typeBn?: boolean
  count?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type CertificateCounterOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "typeEn" | "typeBn" | "count" | "createdAt" | "updatedAt", ExtArgs["result"]["certificateCounter"]>

export type $CertificateCounterPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "CertificateCounter"
  objects: {}
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    typeEn: string
    typeBn: string
    count: number
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["certificateCounter"]>
  composites: {}
}

export type CertificateCounterGetPayload<S extends boolean | null | undefined | CertificateCounterDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$CertificateCounterPayload, S>

export type CertificateCounterCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<CertificateCounterFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: CertificateCounterCountAggregateInputType | true
  }

export interface CertificateCounterDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['CertificateCounter'], meta: { name: 'CertificateCounter' } }
  /**
   * Find zero or one CertificateCounter that matches the filter.
   * @param {CertificateCounterFindUniqueArgs} args - Arguments to find a CertificateCounter
   * @example
   * // Get one CertificateCounter
   * const certificateCounter = await prisma.certificateCounter.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends CertificateCounterFindUniqueArgs>(args: Prisma.SelectSubset<T, CertificateCounterFindUniqueArgs<ExtArgs>>): Prisma.Prisma__CertificateCounterClient<runtime.Types.Result.GetResult<Prisma.$CertificateCounterPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one CertificateCounter that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {CertificateCounterFindUniqueOrThrowArgs} args - Arguments to find a CertificateCounter
   * @example
   * // Get one CertificateCounter
   * const certificateCounter = await prisma.certificateCounter.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends CertificateCounterFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, CertificateCounterFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__CertificateCounterClient<runtime.Types.Result.GetResult<Prisma.$CertificateCounterPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first CertificateCounter that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CertificateCounterFindFirstArgs} args - Arguments to find a CertificateCounter
   * @example
   * // Get one CertificateCounter
   * const certificateCounter = await prisma.certificateCounter.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends CertificateCounterFindFirstArgs>(args?: Prisma.SelectSubset<T, CertificateCounterFindFirstArgs<ExtArgs>>): Prisma.Prisma__CertificateCounterClient<runtime.Types.Result.GetResult<Prisma.$CertificateCounterPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first CertificateCounter that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CertificateCounterFindFirstOrThrowArgs} args - Arguments to find a CertificateCounter
   * @example
   * // Get one CertificateCounter
   * const certificateCounter = await prisma.certificateCounter.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends CertificateCounterFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, CertificateCounterFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__CertificateCounterClient<runtime.Types.Result.GetResult<Prisma.$CertificateCounterPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more CertificateCounters that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CertificateCounterFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all CertificateCounters
   * const certificateCounters = await prisma.certificateCounter.findMany()
   * 
   * // Get first 10 CertificateCounters
   * const certificateCounters = await prisma.certificateCounter.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const certificateCounterWithIdOnly = await prisma.certificateCounter.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends CertificateCounterFindManyArgs>(args?: Prisma.SelectSubset<T, CertificateCounterFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$CertificateCounterPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a CertificateCounter.
   * @param {CertificateCounterCreateArgs} args - Arguments to create a CertificateCounter.
   * @example
   * // Create one CertificateCounter
   * const CertificateCounter = await prisma.certificateCounter.create({
   *   data: {
   *     // ... data to create a CertificateCounter
   *   }
   * })
   * 
   */
  create<T extends CertificateCounterCreateArgs>(args: Prisma.SelectSubset<T, CertificateCounterCreateArgs<ExtArgs>>): Prisma.Prisma__CertificateCounterClient<runtime.Types.Result.GetResult<Prisma.$CertificateCounterPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many CertificateCounters.
   * @param {CertificateCounterCreateManyArgs} args - Arguments to create many CertificateCounters.
   * @example
   * // Create many CertificateCounters
   * const certificateCounter = await prisma.certificateCounter.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends CertificateCounterCreateManyArgs>(args?: Prisma.SelectSubset<T, CertificateCounterCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many CertificateCounters and returns the data saved in the database.
   * @param {CertificateCounterCreateManyAndReturnArgs} args - Arguments to create many CertificateCounters.
   * @example
   * // Create many CertificateCounters
   * const certificateCounter = await prisma.certificateCounter.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many CertificateCounters and only return the `id`
   * const certificateCounterWithIdOnly = await prisma.certificateCounter.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends CertificateCounterCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, CertificateCounterCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$CertificateCounterPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a CertificateCounter.
   * @param {CertificateCounterDeleteArgs} args - Arguments to delete one CertificateCounter.
   * @example
   * // Delete one CertificateCounter
   * const CertificateCounter = await prisma.certificateCounter.delete({
   *   where: {
   *     // ... filter to delete one CertificateCounter
   *   }
   * })
   * 
   */
  delete<T extends CertificateCounterDeleteArgs>(args: Prisma.SelectSubset<T, CertificateCounterDeleteArgs<ExtArgs>>): Prisma.Prisma__CertificateCounterClient<runtime.Types.Result.GetResult<Prisma.$CertificateCounterPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one CertificateCounter.
   * @param {CertificateCounterUpdateArgs} args - Arguments to update one CertificateCounter.
   * @example
   * // Update one CertificateCounter
   * const certificateCounter = await prisma.certificateCounter.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends CertificateCounterUpdateArgs>(args: Prisma.SelectSubset<T, CertificateCounterUpdateArgs<ExtArgs>>): Prisma.Prisma__CertificateCounterClient<runtime.Types.Result.GetResult<Prisma.$CertificateCounterPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more CertificateCounters.
   * @param {CertificateCounterDeleteManyArgs} args - Arguments to filter CertificateCounters to delete.
   * @example
   * // Delete a few CertificateCounters
   * const { count } = await prisma.certificateCounter.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends CertificateCounterDeleteManyArgs>(args?: Prisma.SelectSubset<T, CertificateCounterDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more CertificateCounters.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CertificateCounterUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many CertificateCounters
   * const certificateCounter = await prisma.certificateCounter.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends CertificateCounterUpdateManyArgs>(args: Prisma.SelectSubset<T, CertificateCounterUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more CertificateCounters and returns the data updated in the database.
   * @param {CertificateCounterUpdateManyAndReturnArgs} args - Arguments to update many CertificateCounters.
   * @example
   * // Update many CertificateCounters
   * const certificateCounter = await prisma.certificateCounter.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more CertificateCounters and only return the `id`
   * const certificateCounterWithIdOnly = await prisma.certificateCounter.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends CertificateCounterUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, CertificateCounterUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$CertificateCounterPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one CertificateCounter.
   * @param {CertificateCounterUpsertArgs} args - Arguments to update or create a CertificateCounter.
   * @example
   * // Update or create a CertificateCounter
   * const certificateCounter = await prisma.certificateCounter.upsert({
   *   create: {
   *     // ... data to create a CertificateCounter
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the CertificateCounter we want to update
   *   }
   * })
   */
  upsert<T extends CertificateCounterUpsertArgs>(args: Prisma.SelectSubset<T, CertificateCounterUpsertArgs<ExtArgs>>): Prisma.Prisma__CertificateCounterClient<runtime.Types.Result.GetResult<Prisma.$CertificateCounterPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of CertificateCounters.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CertificateCounterCountArgs} args - Arguments to filter CertificateCounters to count.
   * @example
   * // Count the number of CertificateCounters
   * const count = await prisma.certificateCounter.count({
   *   where: {
   *     // ... the filter for the CertificateCounters we want to count
   *   }
   * })
  **/
  count<T extends CertificateCounterCountArgs>(
    args?: Prisma.Subset<T, CertificateCounterCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], CertificateCounterCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a CertificateCounter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CertificateCounterAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends CertificateCounterAggregateArgs>(args: Prisma.Subset<T, CertificateCounterAggregateArgs>): Prisma.PrismaPromise<GetCertificateCounterAggregateType<T>>

  /**
   * Group by CertificateCounter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CertificateCounterGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends CertificateCounterGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: CertificateCounterGroupByArgs['orderBy'] }
      : { orderBy?: CertificateCounterGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, CertificateCounterGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetCertificateCounterGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the CertificateCounter model
 */
readonly fields: CertificateCounterFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for CertificateCounter.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__CertificateCounterClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the CertificateCounter model
 */
export interface CertificateCounterFieldRefs {
  readonly id: Prisma.FieldRef<"CertificateCounter", 'String'>
  readonly typeEn: Prisma.FieldRef<"CertificateCounter", 'String'>
  readonly typeBn: Prisma.FieldRef<"CertificateCounter", 'String'>
  readonly count: Prisma.FieldRef<"CertificateCounter", 'Int'>
  readonly createdAt: Prisma.FieldRef<"CertificateCounter", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"CertificateCounter", 'DateTime'>
}
    

// Custom InputTypes
/**
 * CertificateCounter findUnique
 */
export type CertificateCounterFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CertificateCounter
   */
  select?: Prisma.CertificateCounterSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CertificateCounter
   */
  omit?: Prisma.CertificateCounterOmit<ExtArgs> | null
  /**
   * Filter, which CertificateCounter to fetch.
   */
  where: Prisma.CertificateCounterWhereUniqueInput
}

/**
 * CertificateCounter findUniqueOrThrow
 */
export type CertificateCounterFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CertificateCounter
   */
  select?: Prisma.CertificateCounterSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CertificateCounter
   */
  omit?: Prisma.CertificateCounterOmit<ExtArgs> | null
  /**
   * Filter, which CertificateCounter to fetch.
   */
  where: Prisma.CertificateCounterWhereUniqueInput
}

/**
 * CertificateCounter findFirst
 */
export type CertificateCounterFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CertificateCounter
   */
  select?: Prisma.CertificateCounterSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CertificateCounter
   */
  omit?: Prisma.CertificateCounterOmit<ExtArgs> | null
  /**
   * Filter, which CertificateCounter to fetch.
   */
  where?: Prisma.CertificateCounterWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of CertificateCounters to fetch.
   */
  orderBy?: Prisma.CertificateCounterOrderByWithRelationInput | Prisma.CertificateCounterOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for CertificateCounters.
   */
  cursor?: Prisma.CertificateCounterWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` CertificateCounters from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` CertificateCounters.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of CertificateCounters.
   */
  distinct?: Prisma.CertificateCounterScalarFieldEnum | Prisma.CertificateCounterScalarFieldEnum[]
}

/**
 * CertificateCounter findFirstOrThrow
 */
export type CertificateCounterFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CertificateCounter
   */
  select?: Prisma.CertificateCounterSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CertificateCounter
   */
  omit?: Prisma.CertificateCounterOmit<ExtArgs> | null
  /**
   * Filter, which CertificateCounter to fetch.
   */
  where?: Prisma.CertificateCounterWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of CertificateCounters to fetch.
   */
  orderBy?: Prisma.CertificateCounterOrderByWithRelationInput | Prisma.CertificateCounterOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for CertificateCounters.
   */
  cursor?: Prisma.CertificateCounterWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` CertificateCounters from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` CertificateCounters.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of CertificateCounters.
   */
  distinct?: Prisma.CertificateCounterScalarFieldEnum | Prisma.CertificateCounterScalarFieldEnum[]
}

/**
 * CertificateCounter findMany
 */
export type CertificateCounterFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CertificateCounter
   */
  select?: Prisma.CertificateCounterSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CertificateCounter
   */
  omit?: Prisma.CertificateCounterOmit<ExtArgs> | null
  /**
   * Filter, which CertificateCounters to fetch.
   */
  where?: Prisma.CertificateCounterWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of CertificateCounters to fetch.
   */
  orderBy?: Prisma.CertificateCounterOrderByWithRelationInput | Prisma.CertificateCounterOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing CertificateCounters.
   */
  cursor?: Prisma.CertificateCounterWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` CertificateCounters from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` CertificateCounters.
   */
  skip?: number
  distinct?: Prisma.CertificateCounterScalarFieldEnum | Prisma.CertificateCounterScalarFieldEnum[]
}

/**
 * CertificateCounter create
 */
export type CertificateCounterCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CertificateCounter
   */
  select?: Prisma.CertificateCounterSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CertificateCounter
   */
  omit?: Prisma.CertificateCounterOmit<ExtArgs> | null
  /**
   * The data needed to create a CertificateCounter.
   */
  data: Prisma.XOR<Prisma.CertificateCounterCreateInput, Prisma.CertificateCounterUncheckedCreateInput>
}

/**
 * CertificateCounter createMany
 */
export type CertificateCounterCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many CertificateCounters.
   */
  data: Prisma.CertificateCounterCreateManyInput | Prisma.CertificateCounterCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * CertificateCounter createManyAndReturn
 */
export type CertificateCounterCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CertificateCounter
   */
  select?: Prisma.CertificateCounterSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the CertificateCounter
   */
  omit?: Prisma.CertificateCounterOmit<ExtArgs> | null
  /**
   * The data used to create many CertificateCounters.
   */
  data: Prisma.CertificateCounterCreateManyInput | Prisma.CertificateCounterCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * CertificateCounter update
 */
export type CertificateCounterUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CertificateCounter
   */
  select?: Prisma.CertificateCounterSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CertificateCounter
   */
  omit?: Prisma.CertificateCounterOmit<ExtArgs> | null
  /**
   * The data needed to update a CertificateCounter.
   */
  data: Prisma.XOR<Prisma.CertificateCounterUpdateInput, Prisma.CertificateCounterUncheckedUpdateInput>
  /**
   * Choose, which CertificateCounter to update.
   */
  where: Prisma.CertificateCounterWhereUniqueInput
}

/**
 * CertificateCounter updateMany
 */
export type CertificateCounterUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update CertificateCounters.
   */
  data: Prisma.XOR<Prisma.CertificateCounterUpdateManyMutationInput, Prisma.CertificateCounterUncheckedUpdateManyInput>
  /**
   * Filter which CertificateCounters to update
   */
  where?: Prisma.CertificateCounterWhereInput
  /**
   * Limit how many CertificateCounters to update.
   */
  limit?: number
}

/**
 * CertificateCounter updateManyAndReturn
 */
export type CertificateCounterUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CertificateCounter
   */
  select?: Prisma.CertificateCounterSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the CertificateCounter
   */
  omit?: Prisma.CertificateCounterOmit<ExtArgs> | null
  /**
   * The data used to update CertificateCounters.
   */
  data: Prisma.XOR<Prisma.CertificateCounterUpdateManyMutationInput, Prisma.CertificateCounterUncheckedUpdateManyInput>
  /**
   * Filter which CertificateCounters to update
   */
  where?: Prisma.CertificateCounterWhereInput
  /**
   * Limit how many CertificateCounters to update.
   */
  limit?: number
}

/**
 * CertificateCounter upsert
 */
export type CertificateCounterUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CertificateCounter
   */
  select?: Prisma.CertificateCounterSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CertificateCounter
   */
  omit?: Prisma.CertificateCounterOmit<ExtArgs> | null
  /**
   * The filter to search for the CertificateCounter to update in case it exists.
   */
  where: Prisma.CertificateCounterWhereUniqueInput
  /**
   * In case the CertificateCounter found by the `where` argument doesn't exist, create a new CertificateCounter with this data.
   */
  create: Prisma.XOR<Prisma.CertificateCounterCreateInput, Prisma.CertificateCounterUncheckedCreateInput>
  /**
   * In case the CertificateCounter was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.CertificateCounterUpdateInput, Prisma.CertificateCounterUncheckedUpdateInput>
}

/**
 * CertificateCounter delete
 */
export type CertificateCounterDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CertificateCounter
   */
  select?: Prisma.CertificateCounterSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CertificateCounter
   */
  omit?: Prisma.CertificateCounterOmit<ExtArgs> | null
  /**
   * Filter which CertificateCounter to delete.
   */
  where: Prisma.CertificateCounterWhereUniqueInput
}

/**
 * CertificateCounter deleteMany
 */
export type CertificateCounterDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which CertificateCounters to delete
   */
  where?: Prisma.CertificateCounterWhereInput
  /**
   * Limit how many CertificateCounters to delete.
   */
  limit?: number
}

/**
 * CertificateCounter without action
 */
export type CertificateCounterDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CertificateCounter
   */
  select?: Prisma.CertificateCounterSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CertificateCounter
   */
  omit?: Prisma.CertificateCounterOmit<ExtArgs> | null
}
