
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `CertificateApplication` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model CertificateApplication
 * 
 */
export type CertificateApplicationModel = runtime.Types.Result.DefaultSelection<Prisma.$CertificateApplicationPayload>

export type AggregateCertificateApplication = {
  _count: CertificateApplicationCountAggregateOutputType | null
  _min: CertificateApplicationMinAggregateOutputType | null
  _max: CertificateApplicationMaxAggregateOutputType | null
}

export type CertificateApplicationMinAggregateOutputType = {
  id: string | null
  certificateTypeEn: string | null
  certificateTypeBn: string | null
  citizenId: string | null
  status: string | null
  issuedAt: Date | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type CertificateApplicationMaxAggregateOutputType = {
  id: string | null
  certificateTypeEn: string | null
  certificateTypeBn: string | null
  citizenId: string | null
  status: string | null
  issuedAt: Date | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type CertificateApplicationCountAggregateOutputType = {
  id: number
  certificateTypeEn: number
  certificateTypeBn: number
  citizenId: number
  specificData: number
  status: number
  issuedAt: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type CertificateApplicationMinAggregateInputType = {
  id?: true
  certificateTypeEn?: true
  certificateTypeBn?: true
  citizenId?: true
  status?: true
  issuedAt?: true
  createdAt?: true
  updatedAt?: true
}

export type CertificateApplicationMaxAggregateInputType = {
  id?: true
  certificateTypeEn?: true
  certificateTypeBn?: true
  citizenId?: true
  status?: true
  issuedAt?: true
  createdAt?: true
  updatedAt?: true
}

export type CertificateApplicationCountAggregateInputType = {
  id?: true
  certificateTypeEn?: true
  certificateTypeBn?: true
  citizenId?: true
  specificData?: true
  status?: true
  issuedAt?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type CertificateApplicationAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which CertificateApplication to aggregate.
   */
  where?: Prisma.CertificateApplicationWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of CertificateApplications to fetch.
   */
  orderBy?: Prisma.CertificateApplicationOrderByWithRelationInput | Prisma.CertificateApplicationOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.CertificateApplicationWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` CertificateApplications from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` CertificateApplications.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned CertificateApplications
  **/
  _count?: true | CertificateApplicationCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: CertificateApplicationMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: CertificateApplicationMaxAggregateInputType
}

export type GetCertificateApplicationAggregateType<T extends CertificateApplicationAggregateArgs> = {
      [P in keyof T & keyof AggregateCertificateApplication]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateCertificateApplication[P]>
    : Prisma.GetScalarType<T[P], AggregateCertificateApplication[P]>
}




export type CertificateApplicationGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.CertificateApplicationWhereInput
  orderBy?: Prisma.CertificateApplicationOrderByWithAggregationInput | Prisma.CertificateApplicationOrderByWithAggregationInput[]
  by: Prisma.CertificateApplicationScalarFieldEnum[] | Prisma.CertificateApplicationScalarFieldEnum
  having?: Prisma.CertificateApplicationScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: CertificateApplicationCountAggregateInputType | true
  _min?: CertificateApplicationMinAggregateInputType
  _max?: CertificateApplicationMaxAggregateInputType
}

export type CertificateApplicationGroupByOutputType = {
  id: string
  certificateTypeEn: string
  certificateTypeBn: string
  citizenId: string
  specificData: runtime.JsonValue | null
  status: string
  issuedAt: Date | null
  createdAt: Date
  updatedAt: Date
  _count: CertificateApplicationCountAggregateOutputType | null
  _min: CertificateApplicationMinAggregateOutputType | null
  _max: CertificateApplicationMaxAggregateOutputType | null
}

type GetCertificateApplicationGroupByPayload<T extends CertificateApplicationGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<CertificateApplicationGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof CertificateApplicationGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], CertificateApplicationGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], CertificateApplicationGroupByOutputType[P]>
      }
    >
  >



export type CertificateApplicationWhereInput = {
  AND?: Prisma.CertificateApplicationWhereInput | Prisma.CertificateApplicationWhereInput[]
  OR?: Prisma.CertificateApplicationWhereInput[]
  NOT?: Prisma.CertificateApplicationWhereInput | Prisma.CertificateApplicationWhereInput[]
  id?: Prisma.StringFilter<"CertificateApplication"> | string
  certificateTypeEn?: Prisma.StringFilter<"CertificateApplication"> | string
  certificateTypeBn?: Prisma.StringFilter<"CertificateApplication"> | string
  citizenId?: Prisma.StringFilter<"CertificateApplication"> | string
  specificData?: Prisma.JsonNullableFilter<"CertificateApplication">
  status?: Prisma.StringFilter<"CertificateApplication"> | string
  issuedAt?: Prisma.DateTimeNullableFilter<"CertificateApplication"> | Date | string | null
  createdAt?: Prisma.DateTimeFilter<"CertificateApplication"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"CertificateApplication"> | Date | string
  citizen?: Prisma.XOR<Prisma.CitizenScalarRelationFilter, Prisma.CitizenWhereInput>
}

export type CertificateApplicationOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  certificateTypeEn?: Prisma.SortOrder
  certificateTypeBn?: Prisma.SortOrder
  citizenId?: Prisma.SortOrder
  specificData?: Prisma.SortOrderInput | Prisma.SortOrder
  status?: Prisma.SortOrder
  issuedAt?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  citizen?: Prisma.CitizenOrderByWithRelationInput
}

export type CertificateApplicationWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.CertificateApplicationWhereInput | Prisma.CertificateApplicationWhereInput[]
  OR?: Prisma.CertificateApplicationWhereInput[]
  NOT?: Prisma.CertificateApplicationWhereInput | Prisma.CertificateApplicationWhereInput[]
  certificateTypeEn?: Prisma.StringFilter<"CertificateApplication"> | string
  certificateTypeBn?: Prisma.StringFilter<"CertificateApplication"> | string
  citizenId?: Prisma.StringFilter<"CertificateApplication"> | string
  specificData?: Prisma.JsonNullableFilter<"CertificateApplication">
  status?: Prisma.StringFilter<"CertificateApplication"> | string
  issuedAt?: Prisma.DateTimeNullableFilter<"CertificateApplication"> | Date | string | null
  createdAt?: Prisma.DateTimeFilter<"CertificateApplication"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"CertificateApplication"> | Date | string
  citizen?: Prisma.XOR<Prisma.CitizenScalarRelationFilter, Prisma.CitizenWhereInput>
}, "id">

export type CertificateApplicationOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  certificateTypeEn?: Prisma.SortOrder
  certificateTypeBn?: Prisma.SortOrder
  citizenId?: Prisma.SortOrder
  specificData?: Prisma.SortOrderInput | Prisma.SortOrder
  status?: Prisma.SortOrder
  issuedAt?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.CertificateApplicationCountOrderByAggregateInput
  _max?: Prisma.CertificateApplicationMaxOrderByAggregateInput
  _min?: Prisma.CertificateApplicationMinOrderByAggregateInput
}

export type CertificateApplicationScalarWhereWithAggregatesInput = {
  AND?: Prisma.CertificateApplicationScalarWhereWithAggregatesInput | Prisma.CertificateApplicationScalarWhereWithAggregatesInput[]
  OR?: Prisma.CertificateApplicationScalarWhereWithAggregatesInput[]
  NOT?: Prisma.CertificateApplicationScalarWhereWithAggregatesInput | Prisma.CertificateApplicationScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"CertificateApplication"> | string
  certificateTypeEn?: Prisma.StringWithAggregatesFilter<"CertificateApplication"> | string
  certificateTypeBn?: Prisma.StringWithAggregatesFilter<"CertificateApplication"> | string
  citizenId?: Prisma.StringWithAggregatesFilter<"CertificateApplication"> | string
  specificData?: Prisma.JsonNullableWithAggregatesFilter<"CertificateApplication">
  status?: Prisma.StringWithAggregatesFilter<"CertificateApplication"> | string
  issuedAt?: Prisma.DateTimeNullableWithAggregatesFilter<"CertificateApplication"> | Date | string | null
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"CertificateApplication"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"CertificateApplication"> | Date | string
}

export type CertificateApplicationCreateInput = {
  id?: string
  certificateTypeEn: string
  certificateTypeBn: string
  specificData?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  status?: string
  issuedAt?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  citizen: Prisma.CitizenCreateNestedOneWithoutCertificateApplicationsInput
}

export type CertificateApplicationUncheckedCreateInput = {
  id?: string
  certificateTypeEn: string
  certificateTypeBn: string
  citizenId: string
  specificData?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  status?: string
  issuedAt?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type CertificateApplicationUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  certificateTypeEn?: Prisma.StringFieldUpdateOperationsInput | string
  certificateTypeBn?: Prisma.StringFieldUpdateOperationsInput | string
  specificData?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  status?: Prisma.StringFieldUpdateOperationsInput | string
  issuedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  citizen?: Prisma.CitizenUpdateOneRequiredWithoutCertificateApplicationsNestedInput
}

export type CertificateApplicationUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  certificateTypeEn?: Prisma.StringFieldUpdateOperationsInput | string
  certificateTypeBn?: Prisma.StringFieldUpdateOperationsInput | string
  citizenId?: Prisma.StringFieldUpdateOperationsInput | string
  specificData?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  status?: Prisma.StringFieldUpdateOperationsInput | string
  issuedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type CertificateApplicationCreateManyInput = {
  id?: string
  certificateTypeEn: string
  certificateTypeBn: string
  citizenId: string
  specificData?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  status?: string
  issuedAt?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type CertificateApplicationUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  certificateTypeEn?: Prisma.StringFieldUpdateOperationsInput | string
  certificateTypeBn?: Prisma.StringFieldUpdateOperationsInput | string
  specificData?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  status?: Prisma.StringFieldUpdateOperationsInput | string
  issuedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type CertificateApplicationUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  certificateTypeEn?: Prisma.StringFieldUpdateOperationsInput | string
  certificateTypeBn?: Prisma.StringFieldUpdateOperationsInput | string
  citizenId?: Prisma.StringFieldUpdateOperationsInput | string
  specificData?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  status?: Prisma.StringFieldUpdateOperationsInput | string
  issuedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type CertificateApplicationListRelationFilter = {
  every?: Prisma.CertificateApplicationWhereInput
  some?: Prisma.CertificateApplicationWhereInput
  none?: Prisma.CertificateApplicationWhereInput
}

export type CertificateApplicationOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type CertificateApplicationCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  certificateTypeEn?: Prisma.SortOrder
  certificateTypeBn?: Prisma.SortOrder
  citizenId?: Prisma.SortOrder
  specificData?: Prisma.SortOrder
  status?: Prisma.SortOrder
  issuedAt?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type CertificateApplicationMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  certificateTypeEn?: Prisma.SortOrder
  certificateTypeBn?: Prisma.SortOrder
  citizenId?: Prisma.SortOrder
  status?: Prisma.SortOrder
  issuedAt?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type CertificateApplicationMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  certificateTypeEn?: Prisma.SortOrder
  certificateTypeBn?: Prisma.SortOrder
  citizenId?: Prisma.SortOrder
  status?: Prisma.SortOrder
  issuedAt?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type CertificateApplicationCreateNestedManyWithoutCitizenInput = {
  create?: Prisma.XOR<Prisma.CertificateApplicationCreateWithoutCitizenInput, Prisma.CertificateApplicationUncheckedCreateWithoutCitizenInput> | Prisma.CertificateApplicationCreateWithoutCitizenInput[] | Prisma.CertificateApplicationUncheckedCreateWithoutCitizenInput[]
  connectOrCreate?: Prisma.CertificateApplicationCreateOrConnectWithoutCitizenInput | Prisma.CertificateApplicationCreateOrConnectWithoutCitizenInput[]
  createMany?: Prisma.CertificateApplicationCreateManyCitizenInputEnvelope
  connect?: Prisma.CertificateApplicationWhereUniqueInput | Prisma.CertificateApplicationWhereUniqueInput[]
}

export type CertificateApplicationUncheckedCreateNestedManyWithoutCitizenInput = {
  create?: Prisma.XOR<Prisma.CertificateApplicationCreateWithoutCitizenInput, Prisma.CertificateApplicationUncheckedCreateWithoutCitizenInput> | Prisma.CertificateApplicationCreateWithoutCitizenInput[] | Prisma.CertificateApplicationUncheckedCreateWithoutCitizenInput[]
  connectOrCreate?: Prisma.CertificateApplicationCreateOrConnectWithoutCitizenInput | Prisma.CertificateApplicationCreateOrConnectWithoutCitizenInput[]
  createMany?: Prisma.CertificateApplicationCreateManyCitizenInputEnvelope
  connect?: Prisma.CertificateApplicationWhereUniqueInput | Prisma.CertificateApplicationWhereUniqueInput[]
}

export type CertificateApplicationUpdateManyWithoutCitizenNestedInput = {
  create?: Prisma.XOR<Prisma.CertificateApplicationCreateWithoutCitizenInput, Prisma.CertificateApplicationUncheckedCreateWithoutCitizenInput> | Prisma.CertificateApplicationCreateWithoutCitizenInput[] | Prisma.CertificateApplicationUncheckedCreateWithoutCitizenInput[]
  connectOrCreate?: Prisma.CertificateApplicationCreateOrConnectWithoutCitizenInput | Prisma.CertificateApplicationCreateOrConnectWithoutCitizenInput[]
  upsert?: Prisma.CertificateApplicationUpsertWithWhereUniqueWithoutCitizenInput | Prisma.CertificateApplicationUpsertWithWhereUniqueWithoutCitizenInput[]
  createMany?: Prisma.CertificateApplicationCreateManyCitizenInputEnvelope
  set?: Prisma.CertificateApplicationWhereUniqueInput | Prisma.CertificateApplicationWhereUniqueInput[]
  disconnect?: Prisma.CertificateApplicationWhereUniqueInput | Prisma.CertificateApplicationWhereUniqueInput[]
  delete?: Prisma.CertificateApplicationWhereUniqueInput | Prisma.CertificateApplicationWhereUniqueInput[]
  connect?: Prisma.CertificateApplicationWhereUniqueInput | Prisma.CertificateApplicationWhereUniqueInput[]
  update?: Prisma.CertificateApplicationUpdateWithWhereUniqueWithoutCitizenInput | Prisma.CertificateApplicationUpdateWithWhereUniqueWithoutCitizenInput[]
  updateMany?: Prisma.CertificateApplicationUpdateManyWithWhereWithoutCitizenInput | Prisma.CertificateApplicationUpdateManyWithWhereWithoutCitizenInput[]
  deleteMany?: Prisma.CertificateApplicationScalarWhereInput | Prisma.CertificateApplicationScalarWhereInput[]
}

export type CertificateApplicationUncheckedUpdateManyWithoutCitizenNestedInput = {
  create?: Prisma.XOR<Prisma.CertificateApplicationCreateWithoutCitizenInput, Prisma.CertificateApplicationUncheckedCreateWithoutCitizenInput> | Prisma.CertificateApplicationCreateWithoutCitizenInput[] | Prisma.CertificateApplicationUncheckedCreateWithoutCitizenInput[]
  connectOrCreate?: Prisma.CertificateApplicationCreateOrConnectWithoutCitizenInput | Prisma.CertificateApplicationCreateOrConnectWithoutCitizenInput[]
  upsert?: Prisma.CertificateApplicationUpsertWithWhereUniqueWithoutCitizenInput | Prisma.CertificateApplicationUpsertWithWhereUniqueWithoutCitizenInput[]
  createMany?: Prisma.CertificateApplicationCreateManyCitizenInputEnvelope
  set?: Prisma.CertificateApplicationWhereUniqueInput | Prisma.CertificateApplicationWhereUniqueInput[]
  disconnect?: Prisma.CertificateApplicationWhereUniqueInput | Prisma.CertificateApplicationWhereUniqueInput[]
  delete?: Prisma.CertificateApplicationWhereUniqueInput | Prisma.CertificateApplicationWhereUniqueInput[]
  connect?: Prisma.CertificateApplicationWhereUniqueInput | Prisma.CertificateApplicationWhereUniqueInput[]
  update?: Prisma.CertificateApplicationUpdateWithWhereUniqueWithoutCitizenInput | Prisma.CertificateApplicationUpdateWithWhereUniqueWithoutCitizenInput[]
  updateMany?: Prisma.CertificateApplicationUpdateManyWithWhereWithoutCitizenInput | Prisma.CertificateApplicationUpdateManyWithWhereWithoutCitizenInput[]
  deleteMany?: Prisma.CertificateApplicationScalarWhereInput | Prisma.CertificateApplicationScalarWhereInput[]
}

export type CertificateApplicationCreateWithoutCitizenInput = {
  id?: string
  certificateTypeEn: string
  certificateTypeBn: string
  specificData?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  status?: string
  issuedAt?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type CertificateApplicationUncheckedCreateWithoutCitizenInput = {
  id?: string
  certificateTypeEn: string
  certificateTypeBn: string
  specificData?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  status?: string
  issuedAt?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type CertificateApplicationCreateOrConnectWithoutCitizenInput = {
  where: Prisma.CertificateApplicationWhereUniqueInput
  create: Prisma.XOR<Prisma.CertificateApplicationCreateWithoutCitizenInput, Prisma.CertificateApplicationUncheckedCreateWithoutCitizenInput>
}

export type CertificateApplicationCreateManyCitizenInputEnvelope = {
  data: Prisma.CertificateApplicationCreateManyCitizenInput | Prisma.CertificateApplicationCreateManyCitizenInput[]
  skipDuplicates?: boolean
}

export type CertificateApplicationUpsertWithWhereUniqueWithoutCitizenInput = {
  where: Prisma.CertificateApplicationWhereUniqueInput
  update: Prisma.XOR<Prisma.CertificateApplicationUpdateWithoutCitizenInput, Prisma.CertificateApplicationUncheckedUpdateWithoutCitizenInput>
  create: Prisma.XOR<Prisma.CertificateApplicationCreateWithoutCitizenInput, Prisma.CertificateApplicationUncheckedCreateWithoutCitizenInput>
}

export type CertificateApplicationUpdateWithWhereUniqueWithoutCitizenInput = {
  where: Prisma.CertificateApplicationWhereUniqueInput
  data: Prisma.XOR<Prisma.CertificateApplicationUpdateWithoutCitizenInput, Prisma.CertificateApplicationUncheckedUpdateWithoutCitizenInput>
}

export type CertificateApplicationUpdateManyWithWhereWithoutCitizenInput = {
  where: Prisma.CertificateApplicationScalarWhereInput
  data: Prisma.XOR<Prisma.CertificateApplicationUpdateManyMutationInput, Prisma.CertificateApplicationUncheckedUpdateManyWithoutCitizenInput>
}

export type CertificateApplicationScalarWhereInput = {
  AND?: Prisma.CertificateApplicationScalarWhereInput | Prisma.CertificateApplicationScalarWhereInput[]
  OR?: Prisma.CertificateApplicationScalarWhereInput[]
  NOT?: Prisma.CertificateApplicationScalarWhereInput | Prisma.CertificateApplicationScalarWhereInput[]
  id?: Prisma.StringFilter<"CertificateApplication"> | string
  certificateTypeEn?: Prisma.StringFilter<"CertificateApplication"> | string
  certificateTypeBn?: Prisma.StringFilter<"CertificateApplication"> | string
  citizenId?: Prisma.StringFilter<"CertificateApplication"> | string
  specificData?: Prisma.JsonNullableFilter<"CertificateApplication">
  status?: Prisma.StringFilter<"CertificateApplication"> | string
  issuedAt?: Prisma.DateTimeNullableFilter<"CertificateApplication"> | Date | string | null
  createdAt?: Prisma.DateTimeFilter<"CertificateApplication"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"CertificateApplication"> | Date | string
}

export type CertificateApplicationCreateManyCitizenInput = {
  id?: string
  certificateTypeEn: string
  certificateTypeBn: string
  specificData?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  status?: string
  issuedAt?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type CertificateApplicationUpdateWithoutCitizenInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  certificateTypeEn?: Prisma.StringFieldUpdateOperationsInput | string
  certificateTypeBn?: Prisma.StringFieldUpdateOperationsInput | string
  specificData?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  status?: Prisma.StringFieldUpdateOperationsInput | string
  issuedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type CertificateApplicationUncheckedUpdateWithoutCitizenInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  certificateTypeEn?: Prisma.StringFieldUpdateOperationsInput | string
  certificateTypeBn?: Prisma.StringFieldUpdateOperationsInput | string
  specificData?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  status?: Prisma.StringFieldUpdateOperationsInput | string
  issuedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type CertificateApplicationUncheckedUpdateManyWithoutCitizenInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  certificateTypeEn?: Prisma.StringFieldUpdateOperationsInput | string
  certificateTypeBn?: Prisma.StringFieldUpdateOperationsInput | string
  specificData?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  status?: Prisma.StringFieldUpdateOperationsInput | string
  issuedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type CertificateApplicationSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  certificateTypeEn?: boolean
  certificateTypeBn?: boolean
  citizenId?: boolean
  specificData?: boolean
  status?: boolean
  issuedAt?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  citizen?: boolean | Prisma.CitizenDefaultArgs<ExtArgs>
}, ExtArgs["result"]["certificateApplication"]>

export type CertificateApplicationSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  certificateTypeEn?: boolean
  certificateTypeBn?: boolean
  citizenId?: boolean
  specificData?: boolean
  status?: boolean
  issuedAt?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  citizen?: boolean | Prisma.CitizenDefaultArgs<ExtArgs>
}, ExtArgs["result"]["certificateApplication"]>

export type CertificateApplicationSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  certificateTypeEn?: boolean
  certificateTypeBn?: boolean
  citizenId?: boolean
  specificData?: boolean
  status?: boolean
  issuedAt?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  citizen?: boolean | Prisma.CitizenDefaultArgs<ExtArgs>
}, ExtArgs["result"]["certificateApplication"]>

export type CertificateApplicationSelectScalar = {
  id?: boolean
  certificateTypeEn?: boolean
  certificateTypeBn?: boolean
  citizenId?: boolean
  specificData?: boolean
  status?: boolean
  issuedAt?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type CertificateApplicationOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "certificateTypeEn" | "certificateTypeBn" | "citizenId" | "specificData" | "status" | "issuedAt" | "createdAt" | "updatedAt", ExtArgs["result"]["certificateApplication"]>
export type CertificateApplicationInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  citizen?: boolean | Prisma.CitizenDefaultArgs<ExtArgs>
}
export type CertificateApplicationIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  citizen?: boolean | Prisma.CitizenDefaultArgs<ExtArgs>
}
export type CertificateApplicationIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  citizen?: boolean | Prisma.CitizenDefaultArgs<ExtArgs>
}

export type $CertificateApplicationPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "CertificateApplication"
  objects: {
    citizen: Prisma.$CitizenPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    certificateTypeEn: string
    certificateTypeBn: string
    citizenId: string
    specificData: runtime.JsonValue | null
    status: string
    issuedAt: Date | null
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["certificateApplication"]>
  composites: {}
}

export type CertificateApplicationGetPayload<S extends boolean | null | undefined | CertificateApplicationDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$CertificateApplicationPayload, S>

export type CertificateApplicationCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<CertificateApplicationFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: CertificateApplicationCountAggregateInputType | true
  }

export interface CertificateApplicationDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['CertificateApplication'], meta: { name: 'CertificateApplication' } }
  /**
   * Find zero or one CertificateApplication that matches the filter.
   * @param {CertificateApplicationFindUniqueArgs} args - Arguments to find a CertificateApplication
   * @example
   * // Get one CertificateApplication
   * const certificateApplication = await prisma.certificateApplication.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends CertificateApplicationFindUniqueArgs>(args: Prisma.SelectSubset<T, CertificateApplicationFindUniqueArgs<ExtArgs>>): Prisma.Prisma__CertificateApplicationClient<runtime.Types.Result.GetResult<Prisma.$CertificateApplicationPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one CertificateApplication that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {CertificateApplicationFindUniqueOrThrowArgs} args - Arguments to find a CertificateApplication
   * @example
   * // Get one CertificateApplication
   * const certificateApplication = await prisma.certificateApplication.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends CertificateApplicationFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, CertificateApplicationFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__CertificateApplicationClient<runtime.Types.Result.GetResult<Prisma.$CertificateApplicationPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first CertificateApplication that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CertificateApplicationFindFirstArgs} args - Arguments to find a CertificateApplication
   * @example
   * // Get one CertificateApplication
   * const certificateApplication = await prisma.certificateApplication.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends CertificateApplicationFindFirstArgs>(args?: Prisma.SelectSubset<T, CertificateApplicationFindFirstArgs<ExtArgs>>): Prisma.Prisma__CertificateApplicationClient<runtime.Types.Result.GetResult<Prisma.$CertificateApplicationPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first CertificateApplication that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CertificateApplicationFindFirstOrThrowArgs} args - Arguments to find a CertificateApplication
   * @example
   * // Get one CertificateApplication
   * const certificateApplication = await prisma.certificateApplication.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends CertificateApplicationFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, CertificateApplicationFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__CertificateApplicationClient<runtime.Types.Result.GetResult<Prisma.$CertificateApplicationPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more CertificateApplications that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CertificateApplicationFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all CertificateApplications
   * const certificateApplications = await prisma.certificateApplication.findMany()
   * 
   * // Get first 10 CertificateApplications
   * const certificateApplications = await prisma.certificateApplication.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const certificateApplicationWithIdOnly = await prisma.certificateApplication.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends CertificateApplicationFindManyArgs>(args?: Prisma.SelectSubset<T, CertificateApplicationFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$CertificateApplicationPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a CertificateApplication.
   * @param {CertificateApplicationCreateArgs} args - Arguments to create a CertificateApplication.
   * @example
   * // Create one CertificateApplication
   * const CertificateApplication = await prisma.certificateApplication.create({
   *   data: {
   *     // ... data to create a CertificateApplication
   *   }
   * })
   * 
   */
  create<T extends CertificateApplicationCreateArgs>(args: Prisma.SelectSubset<T, CertificateApplicationCreateArgs<ExtArgs>>): Prisma.Prisma__CertificateApplicationClient<runtime.Types.Result.GetResult<Prisma.$CertificateApplicationPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many CertificateApplications.
   * @param {CertificateApplicationCreateManyArgs} args - Arguments to create many CertificateApplications.
   * @example
   * // Create many CertificateApplications
   * const certificateApplication = await prisma.certificateApplication.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends CertificateApplicationCreateManyArgs>(args?: Prisma.SelectSubset<T, CertificateApplicationCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many CertificateApplications and returns the data saved in the database.
   * @param {CertificateApplicationCreateManyAndReturnArgs} args - Arguments to create many CertificateApplications.
   * @example
   * // Create many CertificateApplications
   * const certificateApplication = await prisma.certificateApplication.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many CertificateApplications and only return the `id`
   * const certificateApplicationWithIdOnly = await prisma.certificateApplication.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends CertificateApplicationCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, CertificateApplicationCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$CertificateApplicationPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a CertificateApplication.
   * @param {CertificateApplicationDeleteArgs} args - Arguments to delete one CertificateApplication.
   * @example
   * // Delete one CertificateApplication
   * const CertificateApplication = await prisma.certificateApplication.delete({
   *   where: {
   *     // ... filter to delete one CertificateApplication
   *   }
   * })
   * 
   */
  delete<T extends CertificateApplicationDeleteArgs>(args: Prisma.SelectSubset<T, CertificateApplicationDeleteArgs<ExtArgs>>): Prisma.Prisma__CertificateApplicationClient<runtime.Types.Result.GetResult<Prisma.$CertificateApplicationPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one CertificateApplication.
   * @param {CertificateApplicationUpdateArgs} args - Arguments to update one CertificateApplication.
   * @example
   * // Update one CertificateApplication
   * const certificateApplication = await prisma.certificateApplication.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends CertificateApplicationUpdateArgs>(args: Prisma.SelectSubset<T, CertificateApplicationUpdateArgs<ExtArgs>>): Prisma.Prisma__CertificateApplicationClient<runtime.Types.Result.GetResult<Prisma.$CertificateApplicationPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more CertificateApplications.
   * @param {CertificateApplicationDeleteManyArgs} args - Arguments to filter CertificateApplications to delete.
   * @example
   * // Delete a few CertificateApplications
   * const { count } = await prisma.certificateApplication.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends CertificateApplicationDeleteManyArgs>(args?: Prisma.SelectSubset<T, CertificateApplicationDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more CertificateApplications.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CertificateApplicationUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many CertificateApplications
   * const certificateApplication = await prisma.certificateApplication.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends CertificateApplicationUpdateManyArgs>(args: Prisma.SelectSubset<T, CertificateApplicationUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more CertificateApplications and returns the data updated in the database.
   * @param {CertificateApplicationUpdateManyAndReturnArgs} args - Arguments to update many CertificateApplications.
   * @example
   * // Update many CertificateApplications
   * const certificateApplication = await prisma.certificateApplication.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more CertificateApplications and only return the `id`
   * const certificateApplicationWithIdOnly = await prisma.certificateApplication.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends CertificateApplicationUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, CertificateApplicationUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$CertificateApplicationPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one CertificateApplication.
   * @param {CertificateApplicationUpsertArgs} args - Arguments to update or create a CertificateApplication.
   * @example
   * // Update or create a CertificateApplication
   * const certificateApplication = await prisma.certificateApplication.upsert({
   *   create: {
   *     // ... data to create a CertificateApplication
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the CertificateApplication we want to update
   *   }
   * })
   */
  upsert<T extends CertificateApplicationUpsertArgs>(args: Prisma.SelectSubset<T, CertificateApplicationUpsertArgs<ExtArgs>>): Prisma.Prisma__CertificateApplicationClient<runtime.Types.Result.GetResult<Prisma.$CertificateApplicationPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of CertificateApplications.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CertificateApplicationCountArgs} args - Arguments to filter CertificateApplications to count.
   * @example
   * // Count the number of CertificateApplications
   * const count = await prisma.certificateApplication.count({
   *   where: {
   *     // ... the filter for the CertificateApplications we want to count
   *   }
   * })
  **/
  count<T extends CertificateApplicationCountArgs>(
    args?: Prisma.Subset<T, CertificateApplicationCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], CertificateApplicationCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a CertificateApplication.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CertificateApplicationAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends CertificateApplicationAggregateArgs>(args: Prisma.Subset<T, CertificateApplicationAggregateArgs>): Prisma.PrismaPromise<GetCertificateApplicationAggregateType<T>>

  /**
   * Group by CertificateApplication.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CertificateApplicationGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends CertificateApplicationGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: CertificateApplicationGroupByArgs['orderBy'] }
      : { orderBy?: CertificateApplicationGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, CertificateApplicationGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetCertificateApplicationGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the CertificateApplication model
 */
readonly fields: CertificateApplicationFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for CertificateApplication.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__CertificateApplicationClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  citizen<T extends Prisma.CitizenDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.CitizenDefaultArgs<ExtArgs>>): Prisma.Prisma__CitizenClient<runtime.Types.Result.GetResult<Prisma.$CitizenPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the CertificateApplication model
 */
export interface CertificateApplicationFieldRefs {
  readonly id: Prisma.FieldRef<"CertificateApplication", 'String'>
  readonly certificateTypeEn: Prisma.FieldRef<"CertificateApplication", 'String'>
  readonly certificateTypeBn: Prisma.FieldRef<"CertificateApplication", 'String'>
  readonly citizenId: Prisma.FieldRef<"CertificateApplication", 'String'>
  readonly specificData: Prisma.FieldRef<"CertificateApplication", 'Json'>
  readonly status: Prisma.FieldRef<"CertificateApplication", 'String'>
  readonly issuedAt: Prisma.FieldRef<"CertificateApplication", 'DateTime'>
  readonly createdAt: Prisma.FieldRef<"CertificateApplication", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"CertificateApplication", 'DateTime'>
}
    

// Custom InputTypes
/**
 * CertificateApplication findUnique
 */
export type CertificateApplicationFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CertificateApplication
   */
  select?: Prisma.CertificateApplicationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CertificateApplication
   */
  omit?: Prisma.CertificateApplicationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CertificateApplicationInclude<ExtArgs> | null
  /**
   * Filter, which CertificateApplication to fetch.
   */
  where: Prisma.CertificateApplicationWhereUniqueInput
}

/**
 * CertificateApplication findUniqueOrThrow
 */
export type CertificateApplicationFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CertificateApplication
   */
  select?: Prisma.CertificateApplicationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CertificateApplication
   */
  omit?: Prisma.CertificateApplicationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CertificateApplicationInclude<ExtArgs> | null
  /**
   * Filter, which CertificateApplication to fetch.
   */
  where: Prisma.CertificateApplicationWhereUniqueInput
}

/**
 * CertificateApplication findFirst
 */
export type CertificateApplicationFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CertificateApplication
   */
  select?: Prisma.CertificateApplicationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CertificateApplication
   */
  omit?: Prisma.CertificateApplicationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CertificateApplicationInclude<ExtArgs> | null
  /**
   * Filter, which CertificateApplication to fetch.
   */
  where?: Prisma.CertificateApplicationWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of CertificateApplications to fetch.
   */
  orderBy?: Prisma.CertificateApplicationOrderByWithRelationInput | Prisma.CertificateApplicationOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for CertificateApplications.
   */
  cursor?: Prisma.CertificateApplicationWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` CertificateApplications from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` CertificateApplications.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of CertificateApplications.
   */
  distinct?: Prisma.CertificateApplicationScalarFieldEnum | Prisma.CertificateApplicationScalarFieldEnum[]
}

/**
 * CertificateApplication findFirstOrThrow
 */
export type CertificateApplicationFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CertificateApplication
   */
  select?: Prisma.CertificateApplicationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CertificateApplication
   */
  omit?: Prisma.CertificateApplicationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CertificateApplicationInclude<ExtArgs> | null
  /**
   * Filter, which CertificateApplication to fetch.
   */
  where?: Prisma.CertificateApplicationWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of CertificateApplications to fetch.
   */
  orderBy?: Prisma.CertificateApplicationOrderByWithRelationInput | Prisma.CertificateApplicationOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for CertificateApplications.
   */
  cursor?: Prisma.CertificateApplicationWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` CertificateApplications from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` CertificateApplications.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of CertificateApplications.
   */
  distinct?: Prisma.CertificateApplicationScalarFieldEnum | Prisma.CertificateApplicationScalarFieldEnum[]
}

/**
 * CertificateApplication findMany
 */
export type CertificateApplicationFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CertificateApplication
   */
  select?: Prisma.CertificateApplicationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CertificateApplication
   */
  omit?: Prisma.CertificateApplicationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CertificateApplicationInclude<ExtArgs> | null
  /**
   * Filter, which CertificateApplications to fetch.
   */
  where?: Prisma.CertificateApplicationWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of CertificateApplications to fetch.
   */
  orderBy?: Prisma.CertificateApplicationOrderByWithRelationInput | Prisma.CertificateApplicationOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing CertificateApplications.
   */
  cursor?: Prisma.CertificateApplicationWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` CertificateApplications from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` CertificateApplications.
   */
  skip?: number
  distinct?: Prisma.CertificateApplicationScalarFieldEnum | Prisma.CertificateApplicationScalarFieldEnum[]
}

/**
 * CertificateApplication create
 */
export type CertificateApplicationCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CertificateApplication
   */
  select?: Prisma.CertificateApplicationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CertificateApplication
   */
  omit?: Prisma.CertificateApplicationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CertificateApplicationInclude<ExtArgs> | null
  /**
   * The data needed to create a CertificateApplication.
   */
  data: Prisma.XOR<Prisma.CertificateApplicationCreateInput, Prisma.CertificateApplicationUncheckedCreateInput>
}

/**
 * CertificateApplication createMany
 */
export type CertificateApplicationCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many CertificateApplications.
   */
  data: Prisma.CertificateApplicationCreateManyInput | Prisma.CertificateApplicationCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * CertificateApplication createManyAndReturn
 */
export type CertificateApplicationCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CertificateApplication
   */
  select?: Prisma.CertificateApplicationSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the CertificateApplication
   */
  omit?: Prisma.CertificateApplicationOmit<ExtArgs> | null
  /**
   * The data used to create many CertificateApplications.
   */
  data: Prisma.CertificateApplicationCreateManyInput | Prisma.CertificateApplicationCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CertificateApplicationIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * CertificateApplication update
 */
export type CertificateApplicationUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CertificateApplication
   */
  select?: Prisma.CertificateApplicationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CertificateApplication
   */
  omit?: Prisma.CertificateApplicationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CertificateApplicationInclude<ExtArgs> | null
  /**
   * The data needed to update a CertificateApplication.
   */
  data: Prisma.XOR<Prisma.CertificateApplicationUpdateInput, Prisma.CertificateApplicationUncheckedUpdateInput>
  /**
   * Choose, which CertificateApplication to update.
   */
  where: Prisma.CertificateApplicationWhereUniqueInput
}

/**
 * CertificateApplication updateMany
 */
export type CertificateApplicationUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update CertificateApplications.
   */
  data: Prisma.XOR<Prisma.CertificateApplicationUpdateManyMutationInput, Prisma.CertificateApplicationUncheckedUpdateManyInput>
  /**
   * Filter which CertificateApplications to update
   */
  where?: Prisma.CertificateApplicationWhereInput
  /**
   * Limit how many CertificateApplications to update.
   */
  limit?: number
}

/**
 * CertificateApplication updateManyAndReturn
 */
export type CertificateApplicationUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CertificateApplication
   */
  select?: Prisma.CertificateApplicationSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the CertificateApplication
   */
  omit?: Prisma.CertificateApplicationOmit<ExtArgs> | null
  /**
   * The data used to update CertificateApplications.
   */
  data: Prisma.XOR<Prisma.CertificateApplicationUpdateManyMutationInput, Prisma.CertificateApplicationUncheckedUpdateManyInput>
  /**
   * Filter which CertificateApplications to update
   */
  where?: Prisma.CertificateApplicationWhereInput
  /**
   * Limit how many CertificateApplications to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CertificateApplicationIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * CertificateApplication upsert
 */
export type CertificateApplicationUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CertificateApplication
   */
  select?: Prisma.CertificateApplicationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CertificateApplication
   */
  omit?: Prisma.CertificateApplicationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CertificateApplicationInclude<ExtArgs> | null
  /**
   * The filter to search for the CertificateApplication to update in case it exists.
   */
  where: Prisma.CertificateApplicationWhereUniqueInput
  /**
   * In case the CertificateApplication found by the `where` argument doesn't exist, create a new CertificateApplication with this data.
   */
  create: Prisma.XOR<Prisma.CertificateApplicationCreateInput, Prisma.CertificateApplicationUncheckedCreateInput>
  /**
   * In case the CertificateApplication was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.CertificateApplicationUpdateInput, Prisma.CertificateApplicationUncheckedUpdateInput>
}

/**
 * CertificateApplication delete
 */
export type CertificateApplicationDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CertificateApplication
   */
  select?: Prisma.CertificateApplicationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CertificateApplication
   */
  omit?: Prisma.CertificateApplicationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CertificateApplicationInclude<ExtArgs> | null
  /**
   * Filter which CertificateApplication to delete.
   */
  where: Prisma.CertificateApplicationWhereUniqueInput
}

/**
 * CertificateApplication deleteMany
 */
export type CertificateApplicationDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which CertificateApplications to delete
   */
  where?: Prisma.CertificateApplicationWhereInput
  /**
   * Limit how many CertificateApplications to delete.
   */
  limit?: number
}

/**
 * CertificateApplication without action
 */
export type CertificateApplicationDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CertificateApplication
   */
  select?: Prisma.CertificateApplicationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CertificateApplication
   */
  omit?: Prisma.CertificateApplicationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CertificateApplicationInclude<ExtArgs> | null
}
