
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `FiscalYear` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model FiscalYear
 * 
 */
export type FiscalYearModel = runtime.Types.Result.DefaultSelection<Prisma.$FiscalYearPayload>

export type AggregateFiscalYear = {
  _count: FiscalYearCountAggregateOutputType | null
  _min: FiscalYearMinAggregateOutputType | null
  _max: FiscalYearMaxAggregateOutputType | null
}

export type FiscalYearMinAggregateOutputType = {
  id: string | null
  name: string | null
  nameBn: string | null
  startDate: Date | null
  endDate: Date | null
  isCurrent: boolean | null
  isActive: boolean | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type FiscalYearMaxAggregateOutputType = {
  id: string | null
  name: string | null
  nameBn: string | null
  startDate: Date | null
  endDate: Date | null
  isCurrent: boolean | null
  isActive: boolean | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type FiscalYearCountAggregateOutputType = {
  id: number
  name: number
  nameBn: number
  startDate: number
  endDate: number
  isCurrent: number
  isActive: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type FiscalYearMinAggregateInputType = {
  id?: true
  name?: true
  nameBn?: true
  startDate?: true
  endDate?: true
  isCurrent?: true
  isActive?: true
  createdAt?: true
  updatedAt?: true
}

export type FiscalYearMaxAggregateInputType = {
  id?: true
  name?: true
  nameBn?: true
  startDate?: true
  endDate?: true
  isCurrent?: true
  isActive?: true
  createdAt?: true
  updatedAt?: true
}

export type FiscalYearCountAggregateInputType = {
  id?: true
  name?: true
  nameBn?: true
  startDate?: true
  endDate?: true
  isCurrent?: true
  isActive?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type FiscalYearAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which FiscalYear to aggregate.
   */
  where?: Prisma.FiscalYearWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of FiscalYears to fetch.
   */
  orderBy?: Prisma.FiscalYearOrderByWithRelationInput | Prisma.FiscalYearOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.FiscalYearWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` FiscalYears from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` FiscalYears.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned FiscalYears
  **/
  _count?: true | FiscalYearCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: FiscalYearMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: FiscalYearMaxAggregateInputType
}

export type GetFiscalYearAggregateType<T extends FiscalYearAggregateArgs> = {
      [P in keyof T & keyof AggregateFiscalYear]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateFiscalYear[P]>
    : Prisma.GetScalarType<T[P], AggregateFiscalYear[P]>
}




export type FiscalYearGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.FiscalYearWhereInput
  orderBy?: Prisma.FiscalYearOrderByWithAggregationInput | Prisma.FiscalYearOrderByWithAggregationInput[]
  by: Prisma.FiscalYearScalarFieldEnum[] | Prisma.FiscalYearScalarFieldEnum
  having?: Prisma.FiscalYearScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: FiscalYearCountAggregateInputType | true
  _min?: FiscalYearMinAggregateInputType
  _max?: FiscalYearMaxAggregateInputType
}

export type FiscalYearGroupByOutputType = {
  id: string
  name: string
  nameBn: string
  startDate: Date
  endDate: Date
  isCurrent: boolean
  isActive: boolean
  createdAt: Date
  updatedAt: Date
  _count: FiscalYearCountAggregateOutputType | null
  _min: FiscalYearMinAggregateOutputType | null
  _max: FiscalYearMaxAggregateOutputType | null
}

type GetFiscalYearGroupByPayload<T extends FiscalYearGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<FiscalYearGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof FiscalYearGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], FiscalYearGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], FiscalYearGroupByOutputType[P]>
      }
    >
  >



export type FiscalYearWhereInput = {
  AND?: Prisma.FiscalYearWhereInput | Prisma.FiscalYearWhereInput[]
  OR?: Prisma.FiscalYearWhereInput[]
  NOT?: Prisma.FiscalYearWhereInput | Prisma.FiscalYearWhereInput[]
  id?: Prisma.StringFilter<"FiscalYear"> | string
  name?: Prisma.StringFilter<"FiscalYear"> | string
  nameBn?: Prisma.StringFilter<"FiscalYear"> | string
  startDate?: Prisma.DateTimeFilter<"FiscalYear"> | Date | string
  endDate?: Prisma.DateTimeFilter<"FiscalYear"> | Date | string
  isCurrent?: Prisma.BoolFilter<"FiscalYear"> | boolean
  isActive?: Prisma.BoolFilter<"FiscalYear"> | boolean
  createdAt?: Prisma.DateTimeFilter<"FiscalYear"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"FiscalYear"> | Date | string
  taxes?: Prisma.HoldingTaxListRelationFilter
  tradeLicenseApplications?: Prisma.TradeLicenseApplicationListRelationFilter
  tradeLicenses?: Prisma.TradeLicenseListRelationFilter
}

export type FiscalYearOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  nameBn?: Prisma.SortOrder
  startDate?: Prisma.SortOrder
  endDate?: Prisma.SortOrder
  isCurrent?: Prisma.SortOrder
  isActive?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  taxes?: Prisma.HoldingTaxOrderByRelationAggregateInput
  tradeLicenseApplications?: Prisma.TradeLicenseApplicationOrderByRelationAggregateInput
  tradeLicenses?: Prisma.TradeLicenseOrderByRelationAggregateInput
}

export type FiscalYearWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.FiscalYearWhereInput | Prisma.FiscalYearWhereInput[]
  OR?: Prisma.FiscalYearWhereInput[]
  NOT?: Prisma.FiscalYearWhereInput | Prisma.FiscalYearWhereInput[]
  name?: Prisma.StringFilter<"FiscalYear"> | string
  nameBn?: Prisma.StringFilter<"FiscalYear"> | string
  startDate?: Prisma.DateTimeFilter<"FiscalYear"> | Date | string
  endDate?: Prisma.DateTimeFilter<"FiscalYear"> | Date | string
  isCurrent?: Prisma.BoolFilter<"FiscalYear"> | boolean
  isActive?: Prisma.BoolFilter<"FiscalYear"> | boolean
  createdAt?: Prisma.DateTimeFilter<"FiscalYear"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"FiscalYear"> | Date | string
  taxes?: Prisma.HoldingTaxListRelationFilter
  tradeLicenseApplications?: Prisma.TradeLicenseApplicationListRelationFilter
  tradeLicenses?: Prisma.TradeLicenseListRelationFilter
}, "id">

export type FiscalYearOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  nameBn?: Prisma.SortOrder
  startDate?: Prisma.SortOrder
  endDate?: Prisma.SortOrder
  isCurrent?: Prisma.SortOrder
  isActive?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.FiscalYearCountOrderByAggregateInput
  _max?: Prisma.FiscalYearMaxOrderByAggregateInput
  _min?: Prisma.FiscalYearMinOrderByAggregateInput
}

export type FiscalYearScalarWhereWithAggregatesInput = {
  AND?: Prisma.FiscalYearScalarWhereWithAggregatesInput | Prisma.FiscalYearScalarWhereWithAggregatesInput[]
  OR?: Prisma.FiscalYearScalarWhereWithAggregatesInput[]
  NOT?: Prisma.FiscalYearScalarWhereWithAggregatesInput | Prisma.FiscalYearScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"FiscalYear"> | string
  name?: Prisma.StringWithAggregatesFilter<"FiscalYear"> | string
  nameBn?: Prisma.StringWithAggregatesFilter<"FiscalYear"> | string
  startDate?: Prisma.DateTimeWithAggregatesFilter<"FiscalYear"> | Date | string
  endDate?: Prisma.DateTimeWithAggregatesFilter<"FiscalYear"> | Date | string
  isCurrent?: Prisma.BoolWithAggregatesFilter<"FiscalYear"> | boolean
  isActive?: Prisma.BoolWithAggregatesFilter<"FiscalYear"> | boolean
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"FiscalYear"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"FiscalYear"> | Date | string
}

export type FiscalYearCreateInput = {
  id?: string
  name: string
  nameBn: string
  startDate: Date | string
  endDate: Date | string
  isCurrent?: boolean
  isActive?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  taxes?: Prisma.HoldingTaxCreateNestedManyWithoutFiscalYearInput
  tradeLicenseApplications?: Prisma.TradeLicenseApplicationCreateNestedManyWithoutFiscalYearInput
  tradeLicenses?: Prisma.TradeLicenseCreateNestedManyWithoutFiscalYearInput
}

export type FiscalYearUncheckedCreateInput = {
  id?: string
  name: string
  nameBn: string
  startDate: Date | string
  endDate: Date | string
  isCurrent?: boolean
  isActive?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  taxes?: Prisma.HoldingTaxUncheckedCreateNestedManyWithoutFiscalYearInput
  tradeLicenseApplications?: Prisma.TradeLicenseApplicationUncheckedCreateNestedManyWithoutFiscalYearInput
  tradeLicenses?: Prisma.TradeLicenseUncheckedCreateNestedManyWithoutFiscalYearInput
}

export type FiscalYearUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  nameBn?: Prisma.StringFieldUpdateOperationsInput | string
  startDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  endDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  isCurrent?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  taxes?: Prisma.HoldingTaxUpdateManyWithoutFiscalYearNestedInput
  tradeLicenseApplications?: Prisma.TradeLicenseApplicationUpdateManyWithoutFiscalYearNestedInput
  tradeLicenses?: Prisma.TradeLicenseUpdateManyWithoutFiscalYearNestedInput
}

export type FiscalYearUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  nameBn?: Prisma.StringFieldUpdateOperationsInput | string
  startDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  endDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  isCurrent?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  taxes?: Prisma.HoldingTaxUncheckedUpdateManyWithoutFiscalYearNestedInput
  tradeLicenseApplications?: Prisma.TradeLicenseApplicationUncheckedUpdateManyWithoutFiscalYearNestedInput
  tradeLicenses?: Prisma.TradeLicenseUncheckedUpdateManyWithoutFiscalYearNestedInput
}

export type FiscalYearCreateManyInput = {
  id?: string
  name: string
  nameBn: string
  startDate: Date | string
  endDate: Date | string
  isCurrent?: boolean
  isActive?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type FiscalYearUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  nameBn?: Prisma.StringFieldUpdateOperationsInput | string
  startDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  endDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  isCurrent?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type FiscalYearUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  nameBn?: Prisma.StringFieldUpdateOperationsInput | string
  startDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  endDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  isCurrent?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type FiscalYearScalarRelationFilter = {
  is?: Prisma.FiscalYearWhereInput
  isNot?: Prisma.FiscalYearWhereInput
}

export type FiscalYearCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  nameBn?: Prisma.SortOrder
  startDate?: Prisma.SortOrder
  endDate?: Prisma.SortOrder
  isCurrent?: Prisma.SortOrder
  isActive?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type FiscalYearMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  nameBn?: Prisma.SortOrder
  startDate?: Prisma.SortOrder
  endDate?: Prisma.SortOrder
  isCurrent?: Prisma.SortOrder
  isActive?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type FiscalYearMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  nameBn?: Prisma.SortOrder
  startDate?: Prisma.SortOrder
  endDate?: Prisma.SortOrder
  isCurrent?: Prisma.SortOrder
  isActive?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type FiscalYearCreateNestedOneWithoutTaxesInput = {
  create?: Prisma.XOR<Prisma.FiscalYearCreateWithoutTaxesInput, Prisma.FiscalYearUncheckedCreateWithoutTaxesInput>
  connectOrCreate?: Prisma.FiscalYearCreateOrConnectWithoutTaxesInput
  connect?: Prisma.FiscalYearWhereUniqueInput
}

export type FiscalYearUpdateOneRequiredWithoutTaxesNestedInput = {
  create?: Prisma.XOR<Prisma.FiscalYearCreateWithoutTaxesInput, Prisma.FiscalYearUncheckedCreateWithoutTaxesInput>
  connectOrCreate?: Prisma.FiscalYearCreateOrConnectWithoutTaxesInput
  upsert?: Prisma.FiscalYearUpsertWithoutTaxesInput
  connect?: Prisma.FiscalYearWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.FiscalYearUpdateToOneWithWhereWithoutTaxesInput, Prisma.FiscalYearUpdateWithoutTaxesInput>, Prisma.FiscalYearUncheckedUpdateWithoutTaxesInput>
}

export type FiscalYearCreateNestedOneWithoutTradeLicenseApplicationsInput = {
  create?: Prisma.XOR<Prisma.FiscalYearCreateWithoutTradeLicenseApplicationsInput, Prisma.FiscalYearUncheckedCreateWithoutTradeLicenseApplicationsInput>
  connectOrCreate?: Prisma.FiscalYearCreateOrConnectWithoutTradeLicenseApplicationsInput
  connect?: Prisma.FiscalYearWhereUniqueInput
}

export type FiscalYearUpdateOneRequiredWithoutTradeLicenseApplicationsNestedInput = {
  create?: Prisma.XOR<Prisma.FiscalYearCreateWithoutTradeLicenseApplicationsInput, Prisma.FiscalYearUncheckedCreateWithoutTradeLicenseApplicationsInput>
  connectOrCreate?: Prisma.FiscalYearCreateOrConnectWithoutTradeLicenseApplicationsInput
  upsert?: Prisma.FiscalYearUpsertWithoutTradeLicenseApplicationsInput
  connect?: Prisma.FiscalYearWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.FiscalYearUpdateToOneWithWhereWithoutTradeLicenseApplicationsInput, Prisma.FiscalYearUpdateWithoutTradeLicenseApplicationsInput>, Prisma.FiscalYearUncheckedUpdateWithoutTradeLicenseApplicationsInput>
}

export type FiscalYearCreateNestedOneWithoutTradeLicensesInput = {
  create?: Prisma.XOR<Prisma.FiscalYearCreateWithoutTradeLicensesInput, Prisma.FiscalYearUncheckedCreateWithoutTradeLicensesInput>
  connectOrCreate?: Prisma.FiscalYearCreateOrConnectWithoutTradeLicensesInput
  connect?: Prisma.FiscalYearWhereUniqueInput
}

export type FiscalYearUpdateOneRequiredWithoutTradeLicensesNestedInput = {
  create?: Prisma.XOR<Prisma.FiscalYearCreateWithoutTradeLicensesInput, Prisma.FiscalYearUncheckedCreateWithoutTradeLicensesInput>
  connectOrCreate?: Prisma.FiscalYearCreateOrConnectWithoutTradeLicensesInput
  upsert?: Prisma.FiscalYearUpsertWithoutTradeLicensesInput
  connect?: Prisma.FiscalYearWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.FiscalYearUpdateToOneWithWhereWithoutTradeLicensesInput, Prisma.FiscalYearUpdateWithoutTradeLicensesInput>, Prisma.FiscalYearUncheckedUpdateWithoutTradeLicensesInput>
}

export type FiscalYearCreateWithoutTaxesInput = {
  id?: string
  name: string
  nameBn: string
  startDate: Date | string
  endDate: Date | string
  isCurrent?: boolean
  isActive?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  tradeLicenseApplications?: Prisma.TradeLicenseApplicationCreateNestedManyWithoutFiscalYearInput
  tradeLicenses?: Prisma.TradeLicenseCreateNestedManyWithoutFiscalYearInput
}

export type FiscalYearUncheckedCreateWithoutTaxesInput = {
  id?: string
  name: string
  nameBn: string
  startDate: Date | string
  endDate: Date | string
  isCurrent?: boolean
  isActive?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  tradeLicenseApplications?: Prisma.TradeLicenseApplicationUncheckedCreateNestedManyWithoutFiscalYearInput
  tradeLicenses?: Prisma.TradeLicenseUncheckedCreateNestedManyWithoutFiscalYearInput
}

export type FiscalYearCreateOrConnectWithoutTaxesInput = {
  where: Prisma.FiscalYearWhereUniqueInput
  create: Prisma.XOR<Prisma.FiscalYearCreateWithoutTaxesInput, Prisma.FiscalYearUncheckedCreateWithoutTaxesInput>
}

export type FiscalYearUpsertWithoutTaxesInput = {
  update: Prisma.XOR<Prisma.FiscalYearUpdateWithoutTaxesInput, Prisma.FiscalYearUncheckedUpdateWithoutTaxesInput>
  create: Prisma.XOR<Prisma.FiscalYearCreateWithoutTaxesInput, Prisma.FiscalYearUncheckedCreateWithoutTaxesInput>
  where?: Prisma.FiscalYearWhereInput
}

export type FiscalYearUpdateToOneWithWhereWithoutTaxesInput = {
  where?: Prisma.FiscalYearWhereInput
  data: Prisma.XOR<Prisma.FiscalYearUpdateWithoutTaxesInput, Prisma.FiscalYearUncheckedUpdateWithoutTaxesInput>
}

export type FiscalYearUpdateWithoutTaxesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  nameBn?: Prisma.StringFieldUpdateOperationsInput | string
  startDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  endDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  isCurrent?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  tradeLicenseApplications?: Prisma.TradeLicenseApplicationUpdateManyWithoutFiscalYearNestedInput
  tradeLicenses?: Prisma.TradeLicenseUpdateManyWithoutFiscalYearNestedInput
}

export type FiscalYearUncheckedUpdateWithoutTaxesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  nameBn?: Prisma.StringFieldUpdateOperationsInput | string
  startDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  endDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  isCurrent?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  tradeLicenseApplications?: Prisma.TradeLicenseApplicationUncheckedUpdateManyWithoutFiscalYearNestedInput
  tradeLicenses?: Prisma.TradeLicenseUncheckedUpdateManyWithoutFiscalYearNestedInput
}

export type FiscalYearCreateWithoutTradeLicenseApplicationsInput = {
  id?: string
  name: string
  nameBn: string
  startDate: Date | string
  endDate: Date | string
  isCurrent?: boolean
  isActive?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  taxes?: Prisma.HoldingTaxCreateNestedManyWithoutFiscalYearInput
  tradeLicenses?: Prisma.TradeLicenseCreateNestedManyWithoutFiscalYearInput
}

export type FiscalYearUncheckedCreateWithoutTradeLicenseApplicationsInput = {
  id?: string
  name: string
  nameBn: string
  startDate: Date | string
  endDate: Date | string
  isCurrent?: boolean
  isActive?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  taxes?: Prisma.HoldingTaxUncheckedCreateNestedManyWithoutFiscalYearInput
  tradeLicenses?: Prisma.TradeLicenseUncheckedCreateNestedManyWithoutFiscalYearInput
}

export type FiscalYearCreateOrConnectWithoutTradeLicenseApplicationsInput = {
  where: Prisma.FiscalYearWhereUniqueInput
  create: Prisma.XOR<Prisma.FiscalYearCreateWithoutTradeLicenseApplicationsInput, Prisma.FiscalYearUncheckedCreateWithoutTradeLicenseApplicationsInput>
}

export type FiscalYearUpsertWithoutTradeLicenseApplicationsInput = {
  update: Prisma.XOR<Prisma.FiscalYearUpdateWithoutTradeLicenseApplicationsInput, Prisma.FiscalYearUncheckedUpdateWithoutTradeLicenseApplicationsInput>
  create: Prisma.XOR<Prisma.FiscalYearCreateWithoutTradeLicenseApplicationsInput, Prisma.FiscalYearUncheckedCreateWithoutTradeLicenseApplicationsInput>
  where?: Prisma.FiscalYearWhereInput
}

export type FiscalYearUpdateToOneWithWhereWithoutTradeLicenseApplicationsInput = {
  where?: Prisma.FiscalYearWhereInput
  data: Prisma.XOR<Prisma.FiscalYearUpdateWithoutTradeLicenseApplicationsInput, Prisma.FiscalYearUncheckedUpdateWithoutTradeLicenseApplicationsInput>
}

export type FiscalYearUpdateWithoutTradeLicenseApplicationsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  nameBn?: Prisma.StringFieldUpdateOperationsInput | string
  startDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  endDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  isCurrent?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  taxes?: Prisma.HoldingTaxUpdateManyWithoutFiscalYearNestedInput
  tradeLicenses?: Prisma.TradeLicenseUpdateManyWithoutFiscalYearNestedInput
}

export type FiscalYearUncheckedUpdateWithoutTradeLicenseApplicationsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  nameBn?: Prisma.StringFieldUpdateOperationsInput | string
  startDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  endDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  isCurrent?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  taxes?: Prisma.HoldingTaxUncheckedUpdateManyWithoutFiscalYearNestedInput
  tradeLicenses?: Prisma.TradeLicenseUncheckedUpdateManyWithoutFiscalYearNestedInput
}

export type FiscalYearCreateWithoutTradeLicensesInput = {
  id?: string
  name: string
  nameBn: string
  startDate: Date | string
  endDate: Date | string
  isCurrent?: boolean
  isActive?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  taxes?: Prisma.HoldingTaxCreateNestedManyWithoutFiscalYearInput
  tradeLicenseApplications?: Prisma.TradeLicenseApplicationCreateNestedManyWithoutFiscalYearInput
}

export type FiscalYearUncheckedCreateWithoutTradeLicensesInput = {
  id?: string
  name: string
  nameBn: string
  startDate: Date | string
  endDate: Date | string
  isCurrent?: boolean
  isActive?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  taxes?: Prisma.HoldingTaxUncheckedCreateNestedManyWithoutFiscalYearInput
  tradeLicenseApplications?: Prisma.TradeLicenseApplicationUncheckedCreateNestedManyWithoutFiscalYearInput
}

export type FiscalYearCreateOrConnectWithoutTradeLicensesInput = {
  where: Prisma.FiscalYearWhereUniqueInput
  create: Prisma.XOR<Prisma.FiscalYearCreateWithoutTradeLicensesInput, Prisma.FiscalYearUncheckedCreateWithoutTradeLicensesInput>
}

export type FiscalYearUpsertWithoutTradeLicensesInput = {
  update: Prisma.XOR<Prisma.FiscalYearUpdateWithoutTradeLicensesInput, Prisma.FiscalYearUncheckedUpdateWithoutTradeLicensesInput>
  create: Prisma.XOR<Prisma.FiscalYearCreateWithoutTradeLicensesInput, Prisma.FiscalYearUncheckedCreateWithoutTradeLicensesInput>
  where?: Prisma.FiscalYearWhereInput
}

export type FiscalYearUpdateToOneWithWhereWithoutTradeLicensesInput = {
  where?: Prisma.FiscalYearWhereInput
  data: Prisma.XOR<Prisma.FiscalYearUpdateWithoutTradeLicensesInput, Prisma.FiscalYearUncheckedUpdateWithoutTradeLicensesInput>
}

export type FiscalYearUpdateWithoutTradeLicensesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  nameBn?: Prisma.StringFieldUpdateOperationsInput | string
  startDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  endDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  isCurrent?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  taxes?: Prisma.HoldingTaxUpdateManyWithoutFiscalYearNestedInput
  tradeLicenseApplications?: Prisma.TradeLicenseApplicationUpdateManyWithoutFiscalYearNestedInput
}

export type FiscalYearUncheckedUpdateWithoutTradeLicensesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  nameBn?: Prisma.StringFieldUpdateOperationsInput | string
  startDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  endDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  isCurrent?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  taxes?: Prisma.HoldingTaxUncheckedUpdateManyWithoutFiscalYearNestedInput
  tradeLicenseApplications?: Prisma.TradeLicenseApplicationUncheckedUpdateManyWithoutFiscalYearNestedInput
}


/**
 * Count Type FiscalYearCountOutputType
 */

export type FiscalYearCountOutputType = {
  taxes: number
  tradeLicenseApplications: number
  tradeLicenses: number
}

export type FiscalYearCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  taxes?: boolean | FiscalYearCountOutputTypeCountTaxesArgs
  tradeLicenseApplications?: boolean | FiscalYearCountOutputTypeCountTradeLicenseApplicationsArgs
  tradeLicenses?: boolean | FiscalYearCountOutputTypeCountTradeLicensesArgs
}

/**
 * FiscalYearCountOutputType without action
 */
export type FiscalYearCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FiscalYearCountOutputType
   */
  select?: Prisma.FiscalYearCountOutputTypeSelect<ExtArgs> | null
}

/**
 * FiscalYearCountOutputType without action
 */
export type FiscalYearCountOutputTypeCountTaxesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.HoldingTaxWhereInput
}

/**
 * FiscalYearCountOutputType without action
 */
export type FiscalYearCountOutputTypeCountTradeLicenseApplicationsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.TradeLicenseApplicationWhereInput
}

/**
 * FiscalYearCountOutputType without action
 */
export type FiscalYearCountOutputTypeCountTradeLicensesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.TradeLicenseWhereInput
}


export type FiscalYearSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  nameBn?: boolean
  startDate?: boolean
  endDate?: boolean
  isCurrent?: boolean
  isActive?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  taxes?: boolean | Prisma.FiscalYear$taxesArgs<ExtArgs>
  tradeLicenseApplications?: boolean | Prisma.FiscalYear$tradeLicenseApplicationsArgs<ExtArgs>
  tradeLicenses?: boolean | Prisma.FiscalYear$tradeLicensesArgs<ExtArgs>
  _count?: boolean | Prisma.FiscalYearCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["fiscalYear"]>

export type FiscalYearSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  nameBn?: boolean
  startDate?: boolean
  endDate?: boolean
  isCurrent?: boolean
  isActive?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["fiscalYear"]>

export type FiscalYearSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  nameBn?: boolean
  startDate?: boolean
  endDate?: boolean
  isCurrent?: boolean
  isActive?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["fiscalYear"]>

export type FiscalYearSelectScalar = {
  id?: boolean
  name?: boolean
  nameBn?: boolean
  startDate?: boolean
  endDate?: boolean
  isCurrent?: boolean
  isActive?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type FiscalYearOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "name" | "nameBn" | "startDate" | "endDate" | "isCurrent" | "isActive" | "createdAt" | "updatedAt", ExtArgs["result"]["fiscalYear"]>
export type FiscalYearInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  taxes?: boolean | Prisma.FiscalYear$taxesArgs<ExtArgs>
  tradeLicenseApplications?: boolean | Prisma.FiscalYear$tradeLicenseApplicationsArgs<ExtArgs>
  tradeLicenses?: boolean | Prisma.FiscalYear$tradeLicensesArgs<ExtArgs>
  _count?: boolean | Prisma.FiscalYearCountOutputTypeDefaultArgs<ExtArgs>
}
export type FiscalYearIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}
export type FiscalYearIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}

export type $FiscalYearPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "FiscalYear"
  objects: {
    taxes: Prisma.$HoldingTaxPayload<ExtArgs>[]
    tradeLicenseApplications: Prisma.$TradeLicenseApplicationPayload<ExtArgs>[]
    tradeLicenses: Prisma.$TradeLicensePayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    name: string
    nameBn: string
    startDate: Date
    endDate: Date
    isCurrent: boolean
    isActive: boolean
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["fiscalYear"]>
  composites: {}
}

export type FiscalYearGetPayload<S extends boolean | null | undefined | FiscalYearDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$FiscalYearPayload, S>

export type FiscalYearCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<FiscalYearFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: FiscalYearCountAggregateInputType | true
  }

export interface FiscalYearDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['FiscalYear'], meta: { name: 'FiscalYear' } }
  /**
   * Find zero or one FiscalYear that matches the filter.
   * @param {FiscalYearFindUniqueArgs} args - Arguments to find a FiscalYear
   * @example
   * // Get one FiscalYear
   * const fiscalYear = await prisma.fiscalYear.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends FiscalYearFindUniqueArgs>(args: Prisma.SelectSubset<T, FiscalYearFindUniqueArgs<ExtArgs>>): Prisma.Prisma__FiscalYearClient<runtime.Types.Result.GetResult<Prisma.$FiscalYearPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one FiscalYear that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {FiscalYearFindUniqueOrThrowArgs} args - Arguments to find a FiscalYear
   * @example
   * // Get one FiscalYear
   * const fiscalYear = await prisma.fiscalYear.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends FiscalYearFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, FiscalYearFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__FiscalYearClient<runtime.Types.Result.GetResult<Prisma.$FiscalYearPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first FiscalYear that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FiscalYearFindFirstArgs} args - Arguments to find a FiscalYear
   * @example
   * // Get one FiscalYear
   * const fiscalYear = await prisma.fiscalYear.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends FiscalYearFindFirstArgs>(args?: Prisma.SelectSubset<T, FiscalYearFindFirstArgs<ExtArgs>>): Prisma.Prisma__FiscalYearClient<runtime.Types.Result.GetResult<Prisma.$FiscalYearPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first FiscalYear that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FiscalYearFindFirstOrThrowArgs} args - Arguments to find a FiscalYear
   * @example
   * // Get one FiscalYear
   * const fiscalYear = await prisma.fiscalYear.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends FiscalYearFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, FiscalYearFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__FiscalYearClient<runtime.Types.Result.GetResult<Prisma.$FiscalYearPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more FiscalYears that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FiscalYearFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all FiscalYears
   * const fiscalYears = await prisma.fiscalYear.findMany()
   * 
   * // Get first 10 FiscalYears
   * const fiscalYears = await prisma.fiscalYear.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const fiscalYearWithIdOnly = await prisma.fiscalYear.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends FiscalYearFindManyArgs>(args?: Prisma.SelectSubset<T, FiscalYearFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$FiscalYearPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a FiscalYear.
   * @param {FiscalYearCreateArgs} args - Arguments to create a FiscalYear.
   * @example
   * // Create one FiscalYear
   * const FiscalYear = await prisma.fiscalYear.create({
   *   data: {
   *     // ... data to create a FiscalYear
   *   }
   * })
   * 
   */
  create<T extends FiscalYearCreateArgs>(args: Prisma.SelectSubset<T, FiscalYearCreateArgs<ExtArgs>>): Prisma.Prisma__FiscalYearClient<runtime.Types.Result.GetResult<Prisma.$FiscalYearPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many FiscalYears.
   * @param {FiscalYearCreateManyArgs} args - Arguments to create many FiscalYears.
   * @example
   * // Create many FiscalYears
   * const fiscalYear = await prisma.fiscalYear.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends FiscalYearCreateManyArgs>(args?: Prisma.SelectSubset<T, FiscalYearCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many FiscalYears and returns the data saved in the database.
   * @param {FiscalYearCreateManyAndReturnArgs} args - Arguments to create many FiscalYears.
   * @example
   * // Create many FiscalYears
   * const fiscalYear = await prisma.fiscalYear.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many FiscalYears and only return the `id`
   * const fiscalYearWithIdOnly = await prisma.fiscalYear.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends FiscalYearCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, FiscalYearCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$FiscalYearPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a FiscalYear.
   * @param {FiscalYearDeleteArgs} args - Arguments to delete one FiscalYear.
   * @example
   * // Delete one FiscalYear
   * const FiscalYear = await prisma.fiscalYear.delete({
   *   where: {
   *     // ... filter to delete one FiscalYear
   *   }
   * })
   * 
   */
  delete<T extends FiscalYearDeleteArgs>(args: Prisma.SelectSubset<T, FiscalYearDeleteArgs<ExtArgs>>): Prisma.Prisma__FiscalYearClient<runtime.Types.Result.GetResult<Prisma.$FiscalYearPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one FiscalYear.
   * @param {FiscalYearUpdateArgs} args - Arguments to update one FiscalYear.
   * @example
   * // Update one FiscalYear
   * const fiscalYear = await prisma.fiscalYear.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends FiscalYearUpdateArgs>(args: Prisma.SelectSubset<T, FiscalYearUpdateArgs<ExtArgs>>): Prisma.Prisma__FiscalYearClient<runtime.Types.Result.GetResult<Prisma.$FiscalYearPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more FiscalYears.
   * @param {FiscalYearDeleteManyArgs} args - Arguments to filter FiscalYears to delete.
   * @example
   * // Delete a few FiscalYears
   * const { count } = await prisma.fiscalYear.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends FiscalYearDeleteManyArgs>(args?: Prisma.SelectSubset<T, FiscalYearDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more FiscalYears.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FiscalYearUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many FiscalYears
   * const fiscalYear = await prisma.fiscalYear.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends FiscalYearUpdateManyArgs>(args: Prisma.SelectSubset<T, FiscalYearUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more FiscalYears and returns the data updated in the database.
   * @param {FiscalYearUpdateManyAndReturnArgs} args - Arguments to update many FiscalYears.
   * @example
   * // Update many FiscalYears
   * const fiscalYear = await prisma.fiscalYear.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more FiscalYears and only return the `id`
   * const fiscalYearWithIdOnly = await prisma.fiscalYear.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends FiscalYearUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, FiscalYearUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$FiscalYearPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one FiscalYear.
   * @param {FiscalYearUpsertArgs} args - Arguments to update or create a FiscalYear.
   * @example
   * // Update or create a FiscalYear
   * const fiscalYear = await prisma.fiscalYear.upsert({
   *   create: {
   *     // ... data to create a FiscalYear
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the FiscalYear we want to update
   *   }
   * })
   */
  upsert<T extends FiscalYearUpsertArgs>(args: Prisma.SelectSubset<T, FiscalYearUpsertArgs<ExtArgs>>): Prisma.Prisma__FiscalYearClient<runtime.Types.Result.GetResult<Prisma.$FiscalYearPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of FiscalYears.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FiscalYearCountArgs} args - Arguments to filter FiscalYears to count.
   * @example
   * // Count the number of FiscalYears
   * const count = await prisma.fiscalYear.count({
   *   where: {
   *     // ... the filter for the FiscalYears we want to count
   *   }
   * })
  **/
  count<T extends FiscalYearCountArgs>(
    args?: Prisma.Subset<T, FiscalYearCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], FiscalYearCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a FiscalYear.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FiscalYearAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends FiscalYearAggregateArgs>(args: Prisma.Subset<T, FiscalYearAggregateArgs>): Prisma.PrismaPromise<GetFiscalYearAggregateType<T>>

  /**
   * Group by FiscalYear.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FiscalYearGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends FiscalYearGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: FiscalYearGroupByArgs['orderBy'] }
      : { orderBy?: FiscalYearGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, FiscalYearGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetFiscalYearGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the FiscalYear model
 */
readonly fields: FiscalYearFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for FiscalYear.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__FiscalYearClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  taxes<T extends Prisma.FiscalYear$taxesArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.FiscalYear$taxesArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$HoldingTaxPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  tradeLicenseApplications<T extends Prisma.FiscalYear$tradeLicenseApplicationsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.FiscalYear$tradeLicenseApplicationsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TradeLicenseApplicationPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  tradeLicenses<T extends Prisma.FiscalYear$tradeLicensesArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.FiscalYear$tradeLicensesArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TradeLicensePayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the FiscalYear model
 */
export interface FiscalYearFieldRefs {
  readonly id: Prisma.FieldRef<"FiscalYear", 'String'>
  readonly name: Prisma.FieldRef<"FiscalYear", 'String'>
  readonly nameBn: Prisma.FieldRef<"FiscalYear", 'String'>
  readonly startDate: Prisma.FieldRef<"FiscalYear", 'DateTime'>
  readonly endDate: Prisma.FieldRef<"FiscalYear", 'DateTime'>
  readonly isCurrent: Prisma.FieldRef<"FiscalYear", 'Boolean'>
  readonly isActive: Prisma.FieldRef<"FiscalYear", 'Boolean'>
  readonly createdAt: Prisma.FieldRef<"FiscalYear", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"FiscalYear", 'DateTime'>
}
    

// Custom InputTypes
/**
 * FiscalYear findUnique
 */
export type FiscalYearFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FiscalYear
   */
  select?: Prisma.FiscalYearSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FiscalYear
   */
  omit?: Prisma.FiscalYearOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FiscalYearInclude<ExtArgs> | null
  /**
   * Filter, which FiscalYear to fetch.
   */
  where: Prisma.FiscalYearWhereUniqueInput
}

/**
 * FiscalYear findUniqueOrThrow
 */
export type FiscalYearFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FiscalYear
   */
  select?: Prisma.FiscalYearSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FiscalYear
   */
  omit?: Prisma.FiscalYearOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FiscalYearInclude<ExtArgs> | null
  /**
   * Filter, which FiscalYear to fetch.
   */
  where: Prisma.FiscalYearWhereUniqueInput
}

/**
 * FiscalYear findFirst
 */
export type FiscalYearFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FiscalYear
   */
  select?: Prisma.FiscalYearSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FiscalYear
   */
  omit?: Prisma.FiscalYearOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FiscalYearInclude<ExtArgs> | null
  /**
   * Filter, which FiscalYear to fetch.
   */
  where?: Prisma.FiscalYearWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of FiscalYears to fetch.
   */
  orderBy?: Prisma.FiscalYearOrderByWithRelationInput | Prisma.FiscalYearOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for FiscalYears.
   */
  cursor?: Prisma.FiscalYearWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` FiscalYears from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` FiscalYears.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of FiscalYears.
   */
  distinct?: Prisma.FiscalYearScalarFieldEnum | Prisma.FiscalYearScalarFieldEnum[]
}

/**
 * FiscalYear findFirstOrThrow
 */
export type FiscalYearFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FiscalYear
   */
  select?: Prisma.FiscalYearSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FiscalYear
   */
  omit?: Prisma.FiscalYearOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FiscalYearInclude<ExtArgs> | null
  /**
   * Filter, which FiscalYear to fetch.
   */
  where?: Prisma.FiscalYearWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of FiscalYears to fetch.
   */
  orderBy?: Prisma.FiscalYearOrderByWithRelationInput | Prisma.FiscalYearOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for FiscalYears.
   */
  cursor?: Prisma.FiscalYearWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` FiscalYears from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` FiscalYears.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of FiscalYears.
   */
  distinct?: Prisma.FiscalYearScalarFieldEnum | Prisma.FiscalYearScalarFieldEnum[]
}

/**
 * FiscalYear findMany
 */
export type FiscalYearFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FiscalYear
   */
  select?: Prisma.FiscalYearSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FiscalYear
   */
  omit?: Prisma.FiscalYearOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FiscalYearInclude<ExtArgs> | null
  /**
   * Filter, which FiscalYears to fetch.
   */
  where?: Prisma.FiscalYearWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of FiscalYears to fetch.
   */
  orderBy?: Prisma.FiscalYearOrderByWithRelationInput | Prisma.FiscalYearOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing FiscalYears.
   */
  cursor?: Prisma.FiscalYearWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` FiscalYears from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` FiscalYears.
   */
  skip?: number
  distinct?: Prisma.FiscalYearScalarFieldEnum | Prisma.FiscalYearScalarFieldEnum[]
}

/**
 * FiscalYear create
 */
export type FiscalYearCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FiscalYear
   */
  select?: Prisma.FiscalYearSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FiscalYear
   */
  omit?: Prisma.FiscalYearOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FiscalYearInclude<ExtArgs> | null
  /**
   * The data needed to create a FiscalYear.
   */
  data: Prisma.XOR<Prisma.FiscalYearCreateInput, Prisma.FiscalYearUncheckedCreateInput>
}

/**
 * FiscalYear createMany
 */
export type FiscalYearCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many FiscalYears.
   */
  data: Prisma.FiscalYearCreateManyInput | Prisma.FiscalYearCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * FiscalYear createManyAndReturn
 */
export type FiscalYearCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FiscalYear
   */
  select?: Prisma.FiscalYearSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the FiscalYear
   */
  omit?: Prisma.FiscalYearOmit<ExtArgs> | null
  /**
   * The data used to create many FiscalYears.
   */
  data: Prisma.FiscalYearCreateManyInput | Prisma.FiscalYearCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * FiscalYear update
 */
export type FiscalYearUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FiscalYear
   */
  select?: Prisma.FiscalYearSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FiscalYear
   */
  omit?: Prisma.FiscalYearOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FiscalYearInclude<ExtArgs> | null
  /**
   * The data needed to update a FiscalYear.
   */
  data: Prisma.XOR<Prisma.FiscalYearUpdateInput, Prisma.FiscalYearUncheckedUpdateInput>
  /**
   * Choose, which FiscalYear to update.
   */
  where: Prisma.FiscalYearWhereUniqueInput
}

/**
 * FiscalYear updateMany
 */
export type FiscalYearUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update FiscalYears.
   */
  data: Prisma.XOR<Prisma.FiscalYearUpdateManyMutationInput, Prisma.FiscalYearUncheckedUpdateManyInput>
  /**
   * Filter which FiscalYears to update
   */
  where?: Prisma.FiscalYearWhereInput
  /**
   * Limit how many FiscalYears to update.
   */
  limit?: number
}

/**
 * FiscalYear updateManyAndReturn
 */
export type FiscalYearUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FiscalYear
   */
  select?: Prisma.FiscalYearSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the FiscalYear
   */
  omit?: Prisma.FiscalYearOmit<ExtArgs> | null
  /**
   * The data used to update FiscalYears.
   */
  data: Prisma.XOR<Prisma.FiscalYearUpdateManyMutationInput, Prisma.FiscalYearUncheckedUpdateManyInput>
  /**
   * Filter which FiscalYears to update
   */
  where?: Prisma.FiscalYearWhereInput
  /**
   * Limit how many FiscalYears to update.
   */
  limit?: number
}

/**
 * FiscalYear upsert
 */
export type FiscalYearUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FiscalYear
   */
  select?: Prisma.FiscalYearSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FiscalYear
   */
  omit?: Prisma.FiscalYearOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FiscalYearInclude<ExtArgs> | null
  /**
   * The filter to search for the FiscalYear to update in case it exists.
   */
  where: Prisma.FiscalYearWhereUniqueInput
  /**
   * In case the FiscalYear found by the `where` argument doesn't exist, create a new FiscalYear with this data.
   */
  create: Prisma.XOR<Prisma.FiscalYearCreateInput, Prisma.FiscalYearUncheckedCreateInput>
  /**
   * In case the FiscalYear was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.FiscalYearUpdateInput, Prisma.FiscalYearUncheckedUpdateInput>
}

/**
 * FiscalYear delete
 */
export type FiscalYearDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FiscalYear
   */
  select?: Prisma.FiscalYearSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FiscalYear
   */
  omit?: Prisma.FiscalYearOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FiscalYearInclude<ExtArgs> | null
  /**
   * Filter which FiscalYear to delete.
   */
  where: Prisma.FiscalYearWhereUniqueInput
}

/**
 * FiscalYear deleteMany
 */
export type FiscalYearDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which FiscalYears to delete
   */
  where?: Prisma.FiscalYearWhereInput
  /**
   * Limit how many FiscalYears to delete.
   */
  limit?: number
}

/**
 * FiscalYear.taxes
 */
export type FiscalYear$taxesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the HoldingTax
   */
  select?: Prisma.HoldingTaxSelect<ExtArgs> | null
  /**
   * Omit specific fields from the HoldingTax
   */
  omit?: Prisma.HoldingTaxOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.HoldingTaxInclude<ExtArgs> | null
  where?: Prisma.HoldingTaxWhereInput
  orderBy?: Prisma.HoldingTaxOrderByWithRelationInput | Prisma.HoldingTaxOrderByWithRelationInput[]
  cursor?: Prisma.HoldingTaxWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.HoldingTaxScalarFieldEnum | Prisma.HoldingTaxScalarFieldEnum[]
}

/**
 * FiscalYear.tradeLicenseApplications
 */
export type FiscalYear$tradeLicenseApplicationsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TradeLicenseApplication
   */
  select?: Prisma.TradeLicenseApplicationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TradeLicenseApplication
   */
  omit?: Prisma.TradeLicenseApplicationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TradeLicenseApplicationInclude<ExtArgs> | null
  where?: Prisma.TradeLicenseApplicationWhereInput
  orderBy?: Prisma.TradeLicenseApplicationOrderByWithRelationInput | Prisma.TradeLicenseApplicationOrderByWithRelationInput[]
  cursor?: Prisma.TradeLicenseApplicationWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.TradeLicenseApplicationScalarFieldEnum | Prisma.TradeLicenseApplicationScalarFieldEnum[]
}

/**
 * FiscalYear.tradeLicenses
 */
export type FiscalYear$tradeLicensesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TradeLicense
   */
  select?: Prisma.TradeLicenseSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TradeLicense
   */
  omit?: Prisma.TradeLicenseOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TradeLicenseInclude<ExtArgs> | null
  where?: Prisma.TradeLicenseWhereInput
  orderBy?: Prisma.TradeLicenseOrderByWithRelationInput | Prisma.TradeLicenseOrderByWithRelationInput[]
  cursor?: Prisma.TradeLicenseWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.TradeLicenseScalarFieldEnum | Prisma.TradeLicenseScalarFieldEnum[]
}

/**
 * FiscalYear without action
 */
export type FiscalYearDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FiscalYear
   */
  select?: Prisma.FiscalYearSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FiscalYear
   */
  omit?: Prisma.FiscalYearOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FiscalYearInclude<ExtArgs> | null
}
