
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `TradeLicense` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model TradeLicense
 * 
 */
export type TradeLicenseModel = runtime.Types.Result.DefaultSelection<Prisma.$TradeLicensePayload>

export type AggregateTradeLicense = {
  _count: TradeLicenseCountAggregateOutputType | null
  _avg: TradeLicenseAvgAggregateOutputType | null
  _sum: TradeLicenseSumAggregateOutputType | null
  _min: TradeLicenseMinAggregateOutputType | null
  _max: TradeLicenseMaxAggregateOutputType | null
}

export type TradeLicenseAvgAggregateOutputType = {
  licenseFee: number | null
  arrears: number | null
  discount: number | null
  vatAmount: number | null
  signboardTax: number | null
  professionalTax: number | null
  subCharge: number | null
  totalAmount: number | null
}

export type TradeLicenseSumAggregateOutputType = {
  licenseFee: number | null
  arrears: number | null
  discount: number | null
  vatAmount: number | null
  signboardTax: number | null
  professionalTax: number | null
  subCharge: number | null
  totalAmount: number | null
}

export type TradeLicenseMinAggregateOutputType = {
  id: string | null
  licenseNo: string | null
  trackingNo: string | null
  applicationId: string | null
  fiscalYearId: string | null
  licenseFee: number | null
  arrears: number | null
  arrearsFiscalYear: string | null
  discount: number | null
  vatAmount: number | null
  signboardTax: number | null
  professionalTax: number | null
  subCharge: number | null
  totalAmount: number | null
  paymentStatus: string | null
  paymentType: string | null
  paymentDate: Date | null
  issueDate: Date | null
  expiryDate: Date | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type TradeLicenseMaxAggregateOutputType = {
  id: string | null
  licenseNo: string | null
  trackingNo: string | null
  applicationId: string | null
  fiscalYearId: string | null
  licenseFee: number | null
  arrears: number | null
  arrearsFiscalYear: string | null
  discount: number | null
  vatAmount: number | null
  signboardTax: number | null
  professionalTax: number | null
  subCharge: number | null
  totalAmount: number | null
  paymentStatus: string | null
  paymentType: string | null
  paymentDate: Date | null
  issueDate: Date | null
  expiryDate: Date | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type TradeLicenseCountAggregateOutputType = {
  id: number
  licenseNo: number
  trackingNo: number
  applicationId: number
  fiscalYearId: number
  licenseFee: number
  arrears: number
  arrearsFiscalYear: number
  discount: number
  vatAmount: number
  signboardTax: number
  professionalTax: number
  subCharge: number
  totalAmount: number
  paymentStatus: number
  paymentType: number
  paymentDate: number
  issueDate: number
  expiryDate: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type TradeLicenseAvgAggregateInputType = {
  licenseFee?: true
  arrears?: true
  discount?: true
  vatAmount?: true
  signboardTax?: true
  professionalTax?: true
  subCharge?: true
  totalAmount?: true
}

export type TradeLicenseSumAggregateInputType = {
  licenseFee?: true
  arrears?: true
  discount?: true
  vatAmount?: true
  signboardTax?: true
  professionalTax?: true
  subCharge?: true
  totalAmount?: true
}

export type TradeLicenseMinAggregateInputType = {
  id?: true
  licenseNo?: true
  trackingNo?: true
  applicationId?: true
  fiscalYearId?: true
  licenseFee?: true
  arrears?: true
  arrearsFiscalYear?: true
  discount?: true
  vatAmount?: true
  signboardTax?: true
  professionalTax?: true
  subCharge?: true
  totalAmount?: true
  paymentStatus?: true
  paymentType?: true
  paymentDate?: true
  issueDate?: true
  expiryDate?: true
  createdAt?: true
  updatedAt?: true
}

export type TradeLicenseMaxAggregateInputType = {
  id?: true
  licenseNo?: true
  trackingNo?: true
  applicationId?: true
  fiscalYearId?: true
  licenseFee?: true
  arrears?: true
  arrearsFiscalYear?: true
  discount?: true
  vatAmount?: true
  signboardTax?: true
  professionalTax?: true
  subCharge?: true
  totalAmount?: true
  paymentStatus?: true
  paymentType?: true
  paymentDate?: true
  issueDate?: true
  expiryDate?: true
  createdAt?: true
  updatedAt?: true
}

export type TradeLicenseCountAggregateInputType = {
  id?: true
  licenseNo?: true
  trackingNo?: true
  applicationId?: true
  fiscalYearId?: true
  licenseFee?: true
  arrears?: true
  arrearsFiscalYear?: true
  discount?: true
  vatAmount?: true
  signboardTax?: true
  professionalTax?: true
  subCharge?: true
  totalAmount?: true
  paymentStatus?: true
  paymentType?: true
  paymentDate?: true
  issueDate?: true
  expiryDate?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type TradeLicenseAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which TradeLicense to aggregate.
   */
  where?: Prisma.TradeLicenseWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of TradeLicenses to fetch.
   */
  orderBy?: Prisma.TradeLicenseOrderByWithRelationInput | Prisma.TradeLicenseOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.TradeLicenseWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` TradeLicenses from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` TradeLicenses.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned TradeLicenses
  **/
  _count?: true | TradeLicenseCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: TradeLicenseAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: TradeLicenseSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: TradeLicenseMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: TradeLicenseMaxAggregateInputType
}

export type GetTradeLicenseAggregateType<T extends TradeLicenseAggregateArgs> = {
      [P in keyof T & keyof AggregateTradeLicense]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateTradeLicense[P]>
    : Prisma.GetScalarType<T[P], AggregateTradeLicense[P]>
}




export type TradeLicenseGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.TradeLicenseWhereInput
  orderBy?: Prisma.TradeLicenseOrderByWithAggregationInput | Prisma.TradeLicenseOrderByWithAggregationInput[]
  by: Prisma.TradeLicenseScalarFieldEnum[] | Prisma.TradeLicenseScalarFieldEnum
  having?: Prisma.TradeLicenseScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: TradeLicenseCountAggregateInputType | true
  _avg?: TradeLicenseAvgAggregateInputType
  _sum?: TradeLicenseSumAggregateInputType
  _min?: TradeLicenseMinAggregateInputType
  _max?: TradeLicenseMaxAggregateInputType
}

export type TradeLicenseGroupByOutputType = {
  id: string
  licenseNo: string | null
  trackingNo: string
  applicationId: string
  fiscalYearId: string
  licenseFee: number
  arrears: number
  arrearsFiscalYear: string | null
  discount: number
  vatAmount: number
  signboardTax: number
  professionalTax: number
  subCharge: number
  totalAmount: number
  paymentStatus: string
  paymentType: string | null
  paymentDate: Date | null
  issueDate: Date
  expiryDate: Date
  createdAt: Date
  updatedAt: Date
  _count: TradeLicenseCountAggregateOutputType | null
  _avg: TradeLicenseAvgAggregateOutputType | null
  _sum: TradeLicenseSumAggregateOutputType | null
  _min: TradeLicenseMinAggregateOutputType | null
  _max: TradeLicenseMaxAggregateOutputType | null
}

type GetTradeLicenseGroupByPayload<T extends TradeLicenseGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<TradeLicenseGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof TradeLicenseGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], TradeLicenseGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], TradeLicenseGroupByOutputType[P]>
      }
    >
  >



export type TradeLicenseWhereInput = {
  AND?: Prisma.TradeLicenseWhereInput | Prisma.TradeLicenseWhereInput[]
  OR?: Prisma.TradeLicenseWhereInput[]
  NOT?: Prisma.TradeLicenseWhereInput | Prisma.TradeLicenseWhereInput[]
  id?: Prisma.StringFilter<"TradeLicense"> | string
  licenseNo?: Prisma.StringNullableFilter<"TradeLicense"> | string | null
  trackingNo?: Prisma.StringFilter<"TradeLicense"> | string
  applicationId?: Prisma.StringFilter<"TradeLicense"> | string
  fiscalYearId?: Prisma.StringFilter<"TradeLicense"> | string
  licenseFee?: Prisma.FloatFilter<"TradeLicense"> | number
  arrears?: Prisma.FloatFilter<"TradeLicense"> | number
  arrearsFiscalYear?: Prisma.StringNullableFilter<"TradeLicense"> | string | null
  discount?: Prisma.FloatFilter<"TradeLicense"> | number
  vatAmount?: Prisma.FloatFilter<"TradeLicense"> | number
  signboardTax?: Prisma.FloatFilter<"TradeLicense"> | number
  professionalTax?: Prisma.FloatFilter<"TradeLicense"> | number
  subCharge?: Prisma.FloatFilter<"TradeLicense"> | number
  totalAmount?: Prisma.FloatFilter<"TradeLicense"> | number
  paymentStatus?: Prisma.StringFilter<"TradeLicense"> | string
  paymentType?: Prisma.StringNullableFilter<"TradeLicense"> | string | null
  paymentDate?: Prisma.DateTimeNullableFilter<"TradeLicense"> | Date | string | null
  issueDate?: Prisma.DateTimeFilter<"TradeLicense"> | Date | string
  expiryDate?: Prisma.DateTimeFilter<"TradeLicense"> | Date | string
  createdAt?: Prisma.DateTimeFilter<"TradeLicense"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"TradeLicense"> | Date | string
  application?: Prisma.XOR<Prisma.TradeLicenseApplicationScalarRelationFilter, Prisma.TradeLicenseApplicationWhereInput>
  fiscalYear?: Prisma.XOR<Prisma.FiscalYearScalarRelationFilter, Prisma.FiscalYearWhereInput>
}

export type TradeLicenseOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  licenseNo?: Prisma.SortOrderInput | Prisma.SortOrder
  trackingNo?: Prisma.SortOrder
  applicationId?: Prisma.SortOrder
  fiscalYearId?: Prisma.SortOrder
  licenseFee?: Prisma.SortOrder
  arrears?: Prisma.SortOrder
  arrearsFiscalYear?: Prisma.SortOrderInput | Prisma.SortOrder
  discount?: Prisma.SortOrder
  vatAmount?: Prisma.SortOrder
  signboardTax?: Prisma.SortOrder
  professionalTax?: Prisma.SortOrder
  subCharge?: Prisma.SortOrder
  totalAmount?: Prisma.SortOrder
  paymentStatus?: Prisma.SortOrder
  paymentType?: Prisma.SortOrderInput | Prisma.SortOrder
  paymentDate?: Prisma.SortOrderInput | Prisma.SortOrder
  issueDate?: Prisma.SortOrder
  expiryDate?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  application?: Prisma.TradeLicenseApplicationOrderByWithRelationInput
  fiscalYear?: Prisma.FiscalYearOrderByWithRelationInput
}

export type TradeLicenseWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  licenseNo?: string
  trackingNo?: string
  applicationId?: string
  AND?: Prisma.TradeLicenseWhereInput | Prisma.TradeLicenseWhereInput[]
  OR?: Prisma.TradeLicenseWhereInput[]
  NOT?: Prisma.TradeLicenseWhereInput | Prisma.TradeLicenseWhereInput[]
  fiscalYearId?: Prisma.StringFilter<"TradeLicense"> | string
  licenseFee?: Prisma.FloatFilter<"TradeLicense"> | number
  arrears?: Prisma.FloatFilter<"TradeLicense"> | number
  arrearsFiscalYear?: Prisma.StringNullableFilter<"TradeLicense"> | string | null
  discount?: Prisma.FloatFilter<"TradeLicense"> | number
  vatAmount?: Prisma.FloatFilter<"TradeLicense"> | number
  signboardTax?: Prisma.FloatFilter<"TradeLicense"> | number
  professionalTax?: Prisma.FloatFilter<"TradeLicense"> | number
  subCharge?: Prisma.FloatFilter<"TradeLicense"> | number
  totalAmount?: Prisma.FloatFilter<"TradeLicense"> | number
  paymentStatus?: Prisma.StringFilter<"TradeLicense"> | string
  paymentType?: Prisma.StringNullableFilter<"TradeLicense"> | string | null
  paymentDate?: Prisma.DateTimeNullableFilter<"TradeLicense"> | Date | string | null
  issueDate?: Prisma.DateTimeFilter<"TradeLicense"> | Date | string
  expiryDate?: Prisma.DateTimeFilter<"TradeLicense"> | Date | string
  createdAt?: Prisma.DateTimeFilter<"TradeLicense"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"TradeLicense"> | Date | string
  application?: Prisma.XOR<Prisma.TradeLicenseApplicationScalarRelationFilter, Prisma.TradeLicenseApplicationWhereInput>
  fiscalYear?: Prisma.XOR<Prisma.FiscalYearScalarRelationFilter, Prisma.FiscalYearWhereInput>
}, "id" | "licenseNo" | "trackingNo" | "applicationId">

export type TradeLicenseOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  licenseNo?: Prisma.SortOrderInput | Prisma.SortOrder
  trackingNo?: Prisma.SortOrder
  applicationId?: Prisma.SortOrder
  fiscalYearId?: Prisma.SortOrder
  licenseFee?: Prisma.SortOrder
  arrears?: Prisma.SortOrder
  arrearsFiscalYear?: Prisma.SortOrderInput | Prisma.SortOrder
  discount?: Prisma.SortOrder
  vatAmount?: Prisma.SortOrder
  signboardTax?: Prisma.SortOrder
  professionalTax?: Prisma.SortOrder
  subCharge?: Prisma.SortOrder
  totalAmount?: Prisma.SortOrder
  paymentStatus?: Prisma.SortOrder
  paymentType?: Prisma.SortOrderInput | Prisma.SortOrder
  paymentDate?: Prisma.SortOrderInput | Prisma.SortOrder
  issueDate?: Prisma.SortOrder
  expiryDate?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.TradeLicenseCountOrderByAggregateInput
  _avg?: Prisma.TradeLicenseAvgOrderByAggregateInput
  _max?: Prisma.TradeLicenseMaxOrderByAggregateInput
  _min?: Prisma.TradeLicenseMinOrderByAggregateInput
  _sum?: Prisma.TradeLicenseSumOrderByAggregateInput
}

export type TradeLicenseScalarWhereWithAggregatesInput = {
  AND?: Prisma.TradeLicenseScalarWhereWithAggregatesInput | Prisma.TradeLicenseScalarWhereWithAggregatesInput[]
  OR?: Prisma.TradeLicenseScalarWhereWithAggregatesInput[]
  NOT?: Prisma.TradeLicenseScalarWhereWithAggregatesInput | Prisma.TradeLicenseScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"TradeLicense"> | string
  licenseNo?: Prisma.StringNullableWithAggregatesFilter<"TradeLicense"> | string | null
  trackingNo?: Prisma.StringWithAggregatesFilter<"TradeLicense"> | string
  applicationId?: Prisma.StringWithAggregatesFilter<"TradeLicense"> | string
  fiscalYearId?: Prisma.StringWithAggregatesFilter<"TradeLicense"> | string
  licenseFee?: Prisma.FloatWithAggregatesFilter<"TradeLicense"> | number
  arrears?: Prisma.FloatWithAggregatesFilter<"TradeLicense"> | number
  arrearsFiscalYear?: Prisma.StringNullableWithAggregatesFilter<"TradeLicense"> | string | null
  discount?: Prisma.FloatWithAggregatesFilter<"TradeLicense"> | number
  vatAmount?: Prisma.FloatWithAggregatesFilter<"TradeLicense"> | number
  signboardTax?: Prisma.FloatWithAggregatesFilter<"TradeLicense"> | number
  professionalTax?: Prisma.FloatWithAggregatesFilter<"TradeLicense"> | number
  subCharge?: Prisma.FloatWithAggregatesFilter<"TradeLicense"> | number
  totalAmount?: Prisma.FloatWithAggregatesFilter<"TradeLicense"> | number
  paymentStatus?: Prisma.StringWithAggregatesFilter<"TradeLicense"> | string
  paymentType?: Prisma.StringNullableWithAggregatesFilter<"TradeLicense"> | string | null
  paymentDate?: Prisma.DateTimeNullableWithAggregatesFilter<"TradeLicense"> | Date | string | null
  issueDate?: Prisma.DateTimeWithAggregatesFilter<"TradeLicense"> | Date | string
  expiryDate?: Prisma.DateTimeWithAggregatesFilter<"TradeLicense"> | Date | string
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"TradeLicense"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"TradeLicense"> | Date | string
}

export type TradeLicenseCreateInput = {
  id?: string
  licenseNo?: string | null
  trackingNo: string
  licenseFee?: number
  arrears?: number
  arrearsFiscalYear?: string | null
  discount?: number
  vatAmount?: number
  signboardTax?: number
  professionalTax?: number
  subCharge?: number
  totalAmount: number
  paymentStatus?: string
  paymentType?: string | null
  paymentDate?: Date | string | null
  issueDate?: Date | string
  expiryDate: Date | string
  createdAt?: Date | string
  updatedAt?: Date | string
  application: Prisma.TradeLicenseApplicationCreateNestedOneWithoutTradeLicenseInput
  fiscalYear: Prisma.FiscalYearCreateNestedOneWithoutTradeLicensesInput
}

export type TradeLicenseUncheckedCreateInput = {
  id?: string
  licenseNo?: string | null
  trackingNo: string
  applicationId: string
  fiscalYearId: string
  licenseFee?: number
  arrears?: number
  arrearsFiscalYear?: string | null
  discount?: number
  vatAmount?: number
  signboardTax?: number
  professionalTax?: number
  subCharge?: number
  totalAmount: number
  paymentStatus?: string
  paymentType?: string | null
  paymentDate?: Date | string | null
  issueDate?: Date | string
  expiryDate: Date | string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type TradeLicenseUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  licenseNo?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  trackingNo?: Prisma.StringFieldUpdateOperationsInput | string
  licenseFee?: Prisma.FloatFieldUpdateOperationsInput | number
  arrears?: Prisma.FloatFieldUpdateOperationsInput | number
  arrearsFiscalYear?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  discount?: Prisma.FloatFieldUpdateOperationsInput | number
  vatAmount?: Prisma.FloatFieldUpdateOperationsInput | number
  signboardTax?: Prisma.FloatFieldUpdateOperationsInput | number
  professionalTax?: Prisma.FloatFieldUpdateOperationsInput | number
  subCharge?: Prisma.FloatFieldUpdateOperationsInput | number
  totalAmount?: Prisma.FloatFieldUpdateOperationsInput | number
  paymentStatus?: Prisma.StringFieldUpdateOperationsInput | string
  paymentType?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  paymentDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  issueDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  expiryDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  application?: Prisma.TradeLicenseApplicationUpdateOneRequiredWithoutTradeLicenseNestedInput
  fiscalYear?: Prisma.FiscalYearUpdateOneRequiredWithoutTradeLicensesNestedInput
}

export type TradeLicenseUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  licenseNo?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  trackingNo?: Prisma.StringFieldUpdateOperationsInput | string
  applicationId?: Prisma.StringFieldUpdateOperationsInput | string
  fiscalYearId?: Prisma.StringFieldUpdateOperationsInput | string
  licenseFee?: Prisma.FloatFieldUpdateOperationsInput | number
  arrears?: Prisma.FloatFieldUpdateOperationsInput | number
  arrearsFiscalYear?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  discount?: Prisma.FloatFieldUpdateOperationsInput | number
  vatAmount?: Prisma.FloatFieldUpdateOperationsInput | number
  signboardTax?: Prisma.FloatFieldUpdateOperationsInput | number
  professionalTax?: Prisma.FloatFieldUpdateOperationsInput | number
  subCharge?: Prisma.FloatFieldUpdateOperationsInput | number
  totalAmount?: Prisma.FloatFieldUpdateOperationsInput | number
  paymentStatus?: Prisma.StringFieldUpdateOperationsInput | string
  paymentType?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  paymentDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  issueDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  expiryDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type TradeLicenseCreateManyInput = {
  id?: string
  licenseNo?: string | null
  trackingNo: string
  applicationId: string
  fiscalYearId: string
  licenseFee?: number
  arrears?: number
  arrearsFiscalYear?: string | null
  discount?: number
  vatAmount?: number
  signboardTax?: number
  professionalTax?: number
  subCharge?: number
  totalAmount: number
  paymentStatus?: string
  paymentType?: string | null
  paymentDate?: Date | string | null
  issueDate?: Date | string
  expiryDate: Date | string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type TradeLicenseUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  licenseNo?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  trackingNo?: Prisma.StringFieldUpdateOperationsInput | string
  licenseFee?: Prisma.FloatFieldUpdateOperationsInput | number
  arrears?: Prisma.FloatFieldUpdateOperationsInput | number
  arrearsFiscalYear?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  discount?: Prisma.FloatFieldUpdateOperationsInput | number
  vatAmount?: Prisma.FloatFieldUpdateOperationsInput | number
  signboardTax?: Prisma.FloatFieldUpdateOperationsInput | number
  professionalTax?: Prisma.FloatFieldUpdateOperationsInput | number
  subCharge?: Prisma.FloatFieldUpdateOperationsInput | number
  totalAmount?: Prisma.FloatFieldUpdateOperationsInput | number
  paymentStatus?: Prisma.StringFieldUpdateOperationsInput | string
  paymentType?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  paymentDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  issueDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  expiryDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type TradeLicenseUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  licenseNo?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  trackingNo?: Prisma.StringFieldUpdateOperationsInput | string
  applicationId?: Prisma.StringFieldUpdateOperationsInput | string
  fiscalYearId?: Prisma.StringFieldUpdateOperationsInput | string
  licenseFee?: Prisma.FloatFieldUpdateOperationsInput | number
  arrears?: Prisma.FloatFieldUpdateOperationsInput | number
  arrearsFiscalYear?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  discount?: Prisma.FloatFieldUpdateOperationsInput | number
  vatAmount?: Prisma.FloatFieldUpdateOperationsInput | number
  signboardTax?: Prisma.FloatFieldUpdateOperationsInput | number
  professionalTax?: Prisma.FloatFieldUpdateOperationsInput | number
  subCharge?: Prisma.FloatFieldUpdateOperationsInput | number
  totalAmount?: Prisma.FloatFieldUpdateOperationsInput | number
  paymentStatus?: Prisma.StringFieldUpdateOperationsInput | string
  paymentType?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  paymentDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  issueDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  expiryDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type TradeLicenseListRelationFilter = {
  every?: Prisma.TradeLicenseWhereInput
  some?: Prisma.TradeLicenseWhereInput
  none?: Prisma.TradeLicenseWhereInput
}

export type TradeLicenseOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type TradeLicenseNullableScalarRelationFilter = {
  is?: Prisma.TradeLicenseWhereInput | null
  isNot?: Prisma.TradeLicenseWhereInput | null
}

export type TradeLicenseCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  licenseNo?: Prisma.SortOrder
  trackingNo?: Prisma.SortOrder
  applicationId?: Prisma.SortOrder
  fiscalYearId?: Prisma.SortOrder
  licenseFee?: Prisma.SortOrder
  arrears?: Prisma.SortOrder
  arrearsFiscalYear?: Prisma.SortOrder
  discount?: Prisma.SortOrder
  vatAmount?: Prisma.SortOrder
  signboardTax?: Prisma.SortOrder
  professionalTax?: Prisma.SortOrder
  subCharge?: Prisma.SortOrder
  totalAmount?: Prisma.SortOrder
  paymentStatus?: Prisma.SortOrder
  paymentType?: Prisma.SortOrder
  paymentDate?: Prisma.SortOrder
  issueDate?: Prisma.SortOrder
  expiryDate?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type TradeLicenseAvgOrderByAggregateInput = {
  licenseFee?: Prisma.SortOrder
  arrears?: Prisma.SortOrder
  discount?: Prisma.SortOrder
  vatAmount?: Prisma.SortOrder
  signboardTax?: Prisma.SortOrder
  professionalTax?: Prisma.SortOrder
  subCharge?: Prisma.SortOrder
  totalAmount?: Prisma.SortOrder
}

export type TradeLicenseMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  licenseNo?: Prisma.SortOrder
  trackingNo?: Prisma.SortOrder
  applicationId?: Prisma.SortOrder
  fiscalYearId?: Prisma.SortOrder
  licenseFee?: Prisma.SortOrder
  arrears?: Prisma.SortOrder
  arrearsFiscalYear?: Prisma.SortOrder
  discount?: Prisma.SortOrder
  vatAmount?: Prisma.SortOrder
  signboardTax?: Prisma.SortOrder
  professionalTax?: Prisma.SortOrder
  subCharge?: Prisma.SortOrder
  totalAmount?: Prisma.SortOrder
  paymentStatus?: Prisma.SortOrder
  paymentType?: Prisma.SortOrder
  paymentDate?: Prisma.SortOrder
  issueDate?: Prisma.SortOrder
  expiryDate?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type TradeLicenseMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  licenseNo?: Prisma.SortOrder
  trackingNo?: Prisma.SortOrder
  applicationId?: Prisma.SortOrder
  fiscalYearId?: Prisma.SortOrder
  licenseFee?: Prisma.SortOrder
  arrears?: Prisma.SortOrder
  arrearsFiscalYear?: Prisma.SortOrder
  discount?: Prisma.SortOrder
  vatAmount?: Prisma.SortOrder
  signboardTax?: Prisma.SortOrder
  professionalTax?: Prisma.SortOrder
  subCharge?: Prisma.SortOrder
  totalAmount?: Prisma.SortOrder
  paymentStatus?: Prisma.SortOrder
  paymentType?: Prisma.SortOrder
  paymentDate?: Prisma.SortOrder
  issueDate?: Prisma.SortOrder
  expiryDate?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type TradeLicenseSumOrderByAggregateInput = {
  licenseFee?: Prisma.SortOrder
  arrears?: Prisma.SortOrder
  discount?: Prisma.SortOrder
  vatAmount?: Prisma.SortOrder
  signboardTax?: Prisma.SortOrder
  professionalTax?: Prisma.SortOrder
  subCharge?: Prisma.SortOrder
  totalAmount?: Prisma.SortOrder
}

export type TradeLicenseCreateNestedManyWithoutFiscalYearInput = {
  create?: Prisma.XOR<Prisma.TradeLicenseCreateWithoutFiscalYearInput, Prisma.TradeLicenseUncheckedCreateWithoutFiscalYearInput> | Prisma.TradeLicenseCreateWithoutFiscalYearInput[] | Prisma.TradeLicenseUncheckedCreateWithoutFiscalYearInput[]
  connectOrCreate?: Prisma.TradeLicenseCreateOrConnectWithoutFiscalYearInput | Prisma.TradeLicenseCreateOrConnectWithoutFiscalYearInput[]
  createMany?: Prisma.TradeLicenseCreateManyFiscalYearInputEnvelope
  connect?: Prisma.TradeLicenseWhereUniqueInput | Prisma.TradeLicenseWhereUniqueInput[]
}

export type TradeLicenseUncheckedCreateNestedManyWithoutFiscalYearInput = {
  create?: Prisma.XOR<Prisma.TradeLicenseCreateWithoutFiscalYearInput, Prisma.TradeLicenseUncheckedCreateWithoutFiscalYearInput> | Prisma.TradeLicenseCreateWithoutFiscalYearInput[] | Prisma.TradeLicenseUncheckedCreateWithoutFiscalYearInput[]
  connectOrCreate?: Prisma.TradeLicenseCreateOrConnectWithoutFiscalYearInput | Prisma.TradeLicenseCreateOrConnectWithoutFiscalYearInput[]
  createMany?: Prisma.TradeLicenseCreateManyFiscalYearInputEnvelope
  connect?: Prisma.TradeLicenseWhereUniqueInput | Prisma.TradeLicenseWhereUniqueInput[]
}

export type TradeLicenseUpdateManyWithoutFiscalYearNestedInput = {
  create?: Prisma.XOR<Prisma.TradeLicenseCreateWithoutFiscalYearInput, Prisma.TradeLicenseUncheckedCreateWithoutFiscalYearInput> | Prisma.TradeLicenseCreateWithoutFiscalYearInput[] | Prisma.TradeLicenseUncheckedCreateWithoutFiscalYearInput[]
  connectOrCreate?: Prisma.TradeLicenseCreateOrConnectWithoutFiscalYearInput | Prisma.TradeLicenseCreateOrConnectWithoutFiscalYearInput[]
  upsert?: Prisma.TradeLicenseUpsertWithWhereUniqueWithoutFiscalYearInput | Prisma.TradeLicenseUpsertWithWhereUniqueWithoutFiscalYearInput[]
  createMany?: Prisma.TradeLicenseCreateManyFiscalYearInputEnvelope
  set?: Prisma.TradeLicenseWhereUniqueInput | Prisma.TradeLicenseWhereUniqueInput[]
  disconnect?: Prisma.TradeLicenseWhereUniqueInput | Prisma.TradeLicenseWhereUniqueInput[]
  delete?: Prisma.TradeLicenseWhereUniqueInput | Prisma.TradeLicenseWhereUniqueInput[]
  connect?: Prisma.TradeLicenseWhereUniqueInput | Prisma.TradeLicenseWhereUniqueInput[]
  update?: Prisma.TradeLicenseUpdateWithWhereUniqueWithoutFiscalYearInput | Prisma.TradeLicenseUpdateWithWhereUniqueWithoutFiscalYearInput[]
  updateMany?: Prisma.TradeLicenseUpdateManyWithWhereWithoutFiscalYearInput | Prisma.TradeLicenseUpdateManyWithWhereWithoutFiscalYearInput[]
  deleteMany?: Prisma.TradeLicenseScalarWhereInput | Prisma.TradeLicenseScalarWhereInput[]
}

export type TradeLicenseUncheckedUpdateManyWithoutFiscalYearNestedInput = {
  create?: Prisma.XOR<Prisma.TradeLicenseCreateWithoutFiscalYearInput, Prisma.TradeLicenseUncheckedCreateWithoutFiscalYearInput> | Prisma.TradeLicenseCreateWithoutFiscalYearInput[] | Prisma.TradeLicenseUncheckedCreateWithoutFiscalYearInput[]
  connectOrCreate?: Prisma.TradeLicenseCreateOrConnectWithoutFiscalYearInput | Prisma.TradeLicenseCreateOrConnectWithoutFiscalYearInput[]
  upsert?: Prisma.TradeLicenseUpsertWithWhereUniqueWithoutFiscalYearInput | Prisma.TradeLicenseUpsertWithWhereUniqueWithoutFiscalYearInput[]
  createMany?: Prisma.TradeLicenseCreateManyFiscalYearInputEnvelope
  set?: Prisma.TradeLicenseWhereUniqueInput | Prisma.TradeLicenseWhereUniqueInput[]
  disconnect?: Prisma.TradeLicenseWhereUniqueInput | Prisma.TradeLicenseWhereUniqueInput[]
  delete?: Prisma.TradeLicenseWhereUniqueInput | Prisma.TradeLicenseWhereUniqueInput[]
  connect?: Prisma.TradeLicenseWhereUniqueInput | Prisma.TradeLicenseWhereUniqueInput[]
  update?: Prisma.TradeLicenseUpdateWithWhereUniqueWithoutFiscalYearInput | Prisma.TradeLicenseUpdateWithWhereUniqueWithoutFiscalYearInput[]
  updateMany?: Prisma.TradeLicenseUpdateManyWithWhereWithoutFiscalYearInput | Prisma.TradeLicenseUpdateManyWithWhereWithoutFiscalYearInput[]
  deleteMany?: Prisma.TradeLicenseScalarWhereInput | Prisma.TradeLicenseScalarWhereInput[]
}

export type TradeLicenseCreateNestedOneWithoutApplicationInput = {
  create?: Prisma.XOR<Prisma.TradeLicenseCreateWithoutApplicationInput, Prisma.TradeLicenseUncheckedCreateWithoutApplicationInput>
  connectOrCreate?: Prisma.TradeLicenseCreateOrConnectWithoutApplicationInput
  connect?: Prisma.TradeLicenseWhereUniqueInput
}

export type TradeLicenseUncheckedCreateNestedOneWithoutApplicationInput = {
  create?: Prisma.XOR<Prisma.TradeLicenseCreateWithoutApplicationInput, Prisma.TradeLicenseUncheckedCreateWithoutApplicationInput>
  connectOrCreate?: Prisma.TradeLicenseCreateOrConnectWithoutApplicationInput
  connect?: Prisma.TradeLicenseWhereUniqueInput
}

export type TradeLicenseUpdateOneWithoutApplicationNestedInput = {
  create?: Prisma.XOR<Prisma.TradeLicenseCreateWithoutApplicationInput, Prisma.TradeLicenseUncheckedCreateWithoutApplicationInput>
  connectOrCreate?: Prisma.TradeLicenseCreateOrConnectWithoutApplicationInput
  upsert?: Prisma.TradeLicenseUpsertWithoutApplicationInput
  disconnect?: Prisma.TradeLicenseWhereInput | boolean
  delete?: Prisma.TradeLicenseWhereInput | boolean
  connect?: Prisma.TradeLicenseWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.TradeLicenseUpdateToOneWithWhereWithoutApplicationInput, Prisma.TradeLicenseUpdateWithoutApplicationInput>, Prisma.TradeLicenseUncheckedUpdateWithoutApplicationInput>
}

export type TradeLicenseUncheckedUpdateOneWithoutApplicationNestedInput = {
  create?: Prisma.XOR<Prisma.TradeLicenseCreateWithoutApplicationInput, Prisma.TradeLicenseUncheckedCreateWithoutApplicationInput>
  connectOrCreate?: Prisma.TradeLicenseCreateOrConnectWithoutApplicationInput
  upsert?: Prisma.TradeLicenseUpsertWithoutApplicationInput
  disconnect?: Prisma.TradeLicenseWhereInput | boolean
  delete?: Prisma.TradeLicenseWhereInput | boolean
  connect?: Prisma.TradeLicenseWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.TradeLicenseUpdateToOneWithWhereWithoutApplicationInput, Prisma.TradeLicenseUpdateWithoutApplicationInput>, Prisma.TradeLicenseUncheckedUpdateWithoutApplicationInput>
}

export type TradeLicenseCreateWithoutFiscalYearInput = {
  id?: string
  licenseNo?: string | null
  trackingNo: string
  licenseFee?: number
  arrears?: number
  arrearsFiscalYear?: string | null
  discount?: number
  vatAmount?: number
  signboardTax?: number
  professionalTax?: number
  subCharge?: number
  totalAmount: number
  paymentStatus?: string
  paymentType?: string | null
  paymentDate?: Date | string | null
  issueDate?: Date | string
  expiryDate: Date | string
  createdAt?: Date | string
  updatedAt?: Date | string
  application: Prisma.TradeLicenseApplicationCreateNestedOneWithoutTradeLicenseInput
}

export type TradeLicenseUncheckedCreateWithoutFiscalYearInput = {
  id?: string
  licenseNo?: string | null
  trackingNo: string
  applicationId: string
  licenseFee?: number
  arrears?: number
  arrearsFiscalYear?: string | null
  discount?: number
  vatAmount?: number
  signboardTax?: number
  professionalTax?: number
  subCharge?: number
  totalAmount: number
  paymentStatus?: string
  paymentType?: string | null
  paymentDate?: Date | string | null
  issueDate?: Date | string
  expiryDate: Date | string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type TradeLicenseCreateOrConnectWithoutFiscalYearInput = {
  where: Prisma.TradeLicenseWhereUniqueInput
  create: Prisma.XOR<Prisma.TradeLicenseCreateWithoutFiscalYearInput, Prisma.TradeLicenseUncheckedCreateWithoutFiscalYearInput>
}

export type TradeLicenseCreateManyFiscalYearInputEnvelope = {
  data: Prisma.TradeLicenseCreateManyFiscalYearInput | Prisma.TradeLicenseCreateManyFiscalYearInput[]
  skipDuplicates?: boolean
}

export type TradeLicenseUpsertWithWhereUniqueWithoutFiscalYearInput = {
  where: Prisma.TradeLicenseWhereUniqueInput
  update: Prisma.XOR<Prisma.TradeLicenseUpdateWithoutFiscalYearInput, Prisma.TradeLicenseUncheckedUpdateWithoutFiscalYearInput>
  create: Prisma.XOR<Prisma.TradeLicenseCreateWithoutFiscalYearInput, Prisma.TradeLicenseUncheckedCreateWithoutFiscalYearInput>
}

export type TradeLicenseUpdateWithWhereUniqueWithoutFiscalYearInput = {
  where: Prisma.TradeLicenseWhereUniqueInput
  data: Prisma.XOR<Prisma.TradeLicenseUpdateWithoutFiscalYearInput, Prisma.TradeLicenseUncheckedUpdateWithoutFiscalYearInput>
}

export type TradeLicenseUpdateManyWithWhereWithoutFiscalYearInput = {
  where: Prisma.TradeLicenseScalarWhereInput
  data: Prisma.XOR<Prisma.TradeLicenseUpdateManyMutationInput, Prisma.TradeLicenseUncheckedUpdateManyWithoutFiscalYearInput>
}

export type TradeLicenseScalarWhereInput = {
  AND?: Prisma.TradeLicenseScalarWhereInput | Prisma.TradeLicenseScalarWhereInput[]
  OR?: Prisma.TradeLicenseScalarWhereInput[]
  NOT?: Prisma.TradeLicenseScalarWhereInput | Prisma.TradeLicenseScalarWhereInput[]
  id?: Prisma.StringFilter<"TradeLicense"> | string
  licenseNo?: Prisma.StringNullableFilter<"TradeLicense"> | string | null
  trackingNo?: Prisma.StringFilter<"TradeLicense"> | string
  applicationId?: Prisma.StringFilter<"TradeLicense"> | string
  fiscalYearId?: Prisma.StringFilter<"TradeLicense"> | string
  licenseFee?: Prisma.FloatFilter<"TradeLicense"> | number
  arrears?: Prisma.FloatFilter<"TradeLicense"> | number
  arrearsFiscalYear?: Prisma.StringNullableFilter<"TradeLicense"> | string | null
  discount?: Prisma.FloatFilter<"TradeLicense"> | number
  vatAmount?: Prisma.FloatFilter<"TradeLicense"> | number
  signboardTax?: Prisma.FloatFilter<"TradeLicense"> | number
  professionalTax?: Prisma.FloatFilter<"TradeLicense"> | number
  subCharge?: Prisma.FloatFilter<"TradeLicense"> | number
  totalAmount?: Prisma.FloatFilter<"TradeLicense"> | number
  paymentStatus?: Prisma.StringFilter<"TradeLicense"> | string
  paymentType?: Prisma.StringNullableFilter<"TradeLicense"> | string | null
  paymentDate?: Prisma.DateTimeNullableFilter<"TradeLicense"> | Date | string | null
  issueDate?: Prisma.DateTimeFilter<"TradeLicense"> | Date | string
  expiryDate?: Prisma.DateTimeFilter<"TradeLicense"> | Date | string
  createdAt?: Prisma.DateTimeFilter<"TradeLicense"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"TradeLicense"> | Date | string
}

export type TradeLicenseCreateWithoutApplicationInput = {
  id?: string
  licenseNo?: string | null
  trackingNo: string
  licenseFee?: number
  arrears?: number
  arrearsFiscalYear?: string | null
  discount?: number
  vatAmount?: number
  signboardTax?: number
  professionalTax?: number
  subCharge?: number
  totalAmount: number
  paymentStatus?: string
  paymentType?: string | null
  paymentDate?: Date | string | null
  issueDate?: Date | string
  expiryDate: Date | string
  createdAt?: Date | string
  updatedAt?: Date | string
  fiscalYear: Prisma.FiscalYearCreateNestedOneWithoutTradeLicensesInput
}

export type TradeLicenseUncheckedCreateWithoutApplicationInput = {
  id?: string
  licenseNo?: string | null
  trackingNo: string
  fiscalYearId: string
  licenseFee?: number
  arrears?: number
  arrearsFiscalYear?: string | null
  discount?: number
  vatAmount?: number
  signboardTax?: number
  professionalTax?: number
  subCharge?: number
  totalAmount: number
  paymentStatus?: string
  paymentType?: string | null
  paymentDate?: Date | string | null
  issueDate?: Date | string
  expiryDate: Date | string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type TradeLicenseCreateOrConnectWithoutApplicationInput = {
  where: Prisma.TradeLicenseWhereUniqueInput
  create: Prisma.XOR<Prisma.TradeLicenseCreateWithoutApplicationInput, Prisma.TradeLicenseUncheckedCreateWithoutApplicationInput>
}

export type TradeLicenseUpsertWithoutApplicationInput = {
  update: Prisma.XOR<Prisma.TradeLicenseUpdateWithoutApplicationInput, Prisma.TradeLicenseUncheckedUpdateWithoutApplicationInput>
  create: Prisma.XOR<Prisma.TradeLicenseCreateWithoutApplicationInput, Prisma.TradeLicenseUncheckedCreateWithoutApplicationInput>
  where?: Prisma.TradeLicenseWhereInput
}

export type TradeLicenseUpdateToOneWithWhereWithoutApplicationInput = {
  where?: Prisma.TradeLicenseWhereInput
  data: Prisma.XOR<Prisma.TradeLicenseUpdateWithoutApplicationInput, Prisma.TradeLicenseUncheckedUpdateWithoutApplicationInput>
}

export type TradeLicenseUpdateWithoutApplicationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  licenseNo?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  trackingNo?: Prisma.StringFieldUpdateOperationsInput | string
  licenseFee?: Prisma.FloatFieldUpdateOperationsInput | number
  arrears?: Prisma.FloatFieldUpdateOperationsInput | number
  arrearsFiscalYear?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  discount?: Prisma.FloatFieldUpdateOperationsInput | number
  vatAmount?: Prisma.FloatFieldUpdateOperationsInput | number
  signboardTax?: Prisma.FloatFieldUpdateOperationsInput | number
  professionalTax?: Prisma.FloatFieldUpdateOperationsInput | number
  subCharge?: Prisma.FloatFieldUpdateOperationsInput | number
  totalAmount?: Prisma.FloatFieldUpdateOperationsInput | number
  paymentStatus?: Prisma.StringFieldUpdateOperationsInput | string
  paymentType?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  paymentDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  issueDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  expiryDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  fiscalYear?: Prisma.FiscalYearUpdateOneRequiredWithoutTradeLicensesNestedInput
}

export type TradeLicenseUncheckedUpdateWithoutApplicationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  licenseNo?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  trackingNo?: Prisma.StringFieldUpdateOperationsInput | string
  fiscalYearId?: Prisma.StringFieldUpdateOperationsInput | string
  licenseFee?: Prisma.FloatFieldUpdateOperationsInput | number
  arrears?: Prisma.FloatFieldUpdateOperationsInput | number
  arrearsFiscalYear?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  discount?: Prisma.FloatFieldUpdateOperationsInput | number
  vatAmount?: Prisma.FloatFieldUpdateOperationsInput | number
  signboardTax?: Prisma.FloatFieldUpdateOperationsInput | number
  professionalTax?: Prisma.FloatFieldUpdateOperationsInput | number
  subCharge?: Prisma.FloatFieldUpdateOperationsInput | number
  totalAmount?: Prisma.FloatFieldUpdateOperationsInput | number
  paymentStatus?: Prisma.StringFieldUpdateOperationsInput | string
  paymentType?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  paymentDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  issueDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  expiryDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type TradeLicenseCreateManyFiscalYearInput = {
  id?: string
  licenseNo?: string | null
  trackingNo: string
  applicationId: string
  licenseFee?: number
  arrears?: number
  arrearsFiscalYear?: string | null
  discount?: number
  vatAmount?: number
  signboardTax?: number
  professionalTax?: number
  subCharge?: number
  totalAmount: number
  paymentStatus?: string
  paymentType?: string | null
  paymentDate?: Date | string | null
  issueDate?: Date | string
  expiryDate: Date | string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type TradeLicenseUpdateWithoutFiscalYearInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  licenseNo?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  trackingNo?: Prisma.StringFieldUpdateOperationsInput | string
  licenseFee?: Prisma.FloatFieldUpdateOperationsInput | number
  arrears?: Prisma.FloatFieldUpdateOperationsInput | number
  arrearsFiscalYear?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  discount?: Prisma.FloatFieldUpdateOperationsInput | number
  vatAmount?: Prisma.FloatFieldUpdateOperationsInput | number
  signboardTax?: Prisma.FloatFieldUpdateOperationsInput | number
  professionalTax?: Prisma.FloatFieldUpdateOperationsInput | number
  subCharge?: Prisma.FloatFieldUpdateOperationsInput | number
  totalAmount?: Prisma.FloatFieldUpdateOperationsInput | number
  paymentStatus?: Prisma.StringFieldUpdateOperationsInput | string
  paymentType?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  paymentDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  issueDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  expiryDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  application?: Prisma.TradeLicenseApplicationUpdateOneRequiredWithoutTradeLicenseNestedInput
}

export type TradeLicenseUncheckedUpdateWithoutFiscalYearInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  licenseNo?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  trackingNo?: Prisma.StringFieldUpdateOperationsInput | string
  applicationId?: Prisma.StringFieldUpdateOperationsInput | string
  licenseFee?: Prisma.FloatFieldUpdateOperationsInput | number
  arrears?: Prisma.FloatFieldUpdateOperationsInput | number
  arrearsFiscalYear?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  discount?: Prisma.FloatFieldUpdateOperationsInput | number
  vatAmount?: Prisma.FloatFieldUpdateOperationsInput | number
  signboardTax?: Prisma.FloatFieldUpdateOperationsInput | number
  professionalTax?: Prisma.FloatFieldUpdateOperationsInput | number
  subCharge?: Prisma.FloatFieldUpdateOperationsInput | number
  totalAmount?: Prisma.FloatFieldUpdateOperationsInput | number
  paymentStatus?: Prisma.StringFieldUpdateOperationsInput | string
  paymentType?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  paymentDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  issueDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  expiryDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type TradeLicenseUncheckedUpdateManyWithoutFiscalYearInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  licenseNo?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  trackingNo?: Prisma.StringFieldUpdateOperationsInput | string
  applicationId?: Prisma.StringFieldUpdateOperationsInput | string
  licenseFee?: Prisma.FloatFieldUpdateOperationsInput | number
  arrears?: Prisma.FloatFieldUpdateOperationsInput | number
  arrearsFiscalYear?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  discount?: Prisma.FloatFieldUpdateOperationsInput | number
  vatAmount?: Prisma.FloatFieldUpdateOperationsInput | number
  signboardTax?: Prisma.FloatFieldUpdateOperationsInput | number
  professionalTax?: Prisma.FloatFieldUpdateOperationsInput | number
  subCharge?: Prisma.FloatFieldUpdateOperationsInput | number
  totalAmount?: Prisma.FloatFieldUpdateOperationsInput | number
  paymentStatus?: Prisma.StringFieldUpdateOperationsInput | string
  paymentType?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  paymentDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  issueDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  expiryDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type TradeLicenseSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  licenseNo?: boolean
  trackingNo?: boolean
  applicationId?: boolean
  fiscalYearId?: boolean
  licenseFee?: boolean
  arrears?: boolean
  arrearsFiscalYear?: boolean
  discount?: boolean
  vatAmount?: boolean
  signboardTax?: boolean
  professionalTax?: boolean
  subCharge?: boolean
  totalAmount?: boolean
  paymentStatus?: boolean
  paymentType?: boolean
  paymentDate?: boolean
  issueDate?: boolean
  expiryDate?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  application?: boolean | Prisma.TradeLicenseApplicationDefaultArgs<ExtArgs>
  fiscalYear?: boolean | Prisma.FiscalYearDefaultArgs<ExtArgs>
}, ExtArgs["result"]["tradeLicense"]>

export type TradeLicenseSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  licenseNo?: boolean
  trackingNo?: boolean
  applicationId?: boolean
  fiscalYearId?: boolean
  licenseFee?: boolean
  arrears?: boolean
  arrearsFiscalYear?: boolean
  discount?: boolean
  vatAmount?: boolean
  signboardTax?: boolean
  professionalTax?: boolean
  subCharge?: boolean
  totalAmount?: boolean
  paymentStatus?: boolean
  paymentType?: boolean
  paymentDate?: boolean
  issueDate?: boolean
  expiryDate?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  application?: boolean | Prisma.TradeLicenseApplicationDefaultArgs<ExtArgs>
  fiscalYear?: boolean | Prisma.FiscalYearDefaultArgs<ExtArgs>
}, ExtArgs["result"]["tradeLicense"]>

export type TradeLicenseSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  licenseNo?: boolean
  trackingNo?: boolean
  applicationId?: boolean
  fiscalYearId?: boolean
  licenseFee?: boolean
  arrears?: boolean
  arrearsFiscalYear?: boolean
  discount?: boolean
  vatAmount?: boolean
  signboardTax?: boolean
  professionalTax?: boolean
  subCharge?: boolean
  totalAmount?: boolean
  paymentStatus?: boolean
  paymentType?: boolean
  paymentDate?: boolean
  issueDate?: boolean
  expiryDate?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  application?: boolean | Prisma.TradeLicenseApplicationDefaultArgs<ExtArgs>
  fiscalYear?: boolean | Prisma.FiscalYearDefaultArgs<ExtArgs>
}, ExtArgs["result"]["tradeLicense"]>

export type TradeLicenseSelectScalar = {
  id?: boolean
  licenseNo?: boolean
  trackingNo?: boolean
  applicationId?: boolean
  fiscalYearId?: boolean
  licenseFee?: boolean
  arrears?: boolean
  arrearsFiscalYear?: boolean
  discount?: boolean
  vatAmount?: boolean
  signboardTax?: boolean
  professionalTax?: boolean
  subCharge?: boolean
  totalAmount?: boolean
  paymentStatus?: boolean
  paymentType?: boolean
  paymentDate?: boolean
  issueDate?: boolean
  expiryDate?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type TradeLicenseOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "licenseNo" | "trackingNo" | "applicationId" | "fiscalYearId" | "licenseFee" | "arrears" | "arrearsFiscalYear" | "discount" | "vatAmount" | "signboardTax" | "professionalTax" | "subCharge" | "totalAmount" | "paymentStatus" | "paymentType" | "paymentDate" | "issueDate" | "expiryDate" | "createdAt" | "updatedAt", ExtArgs["result"]["tradeLicense"]>
export type TradeLicenseInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  application?: boolean | Prisma.TradeLicenseApplicationDefaultArgs<ExtArgs>
  fiscalYear?: boolean | Prisma.FiscalYearDefaultArgs<ExtArgs>
}
export type TradeLicenseIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  application?: boolean | Prisma.TradeLicenseApplicationDefaultArgs<ExtArgs>
  fiscalYear?: boolean | Prisma.FiscalYearDefaultArgs<ExtArgs>
}
export type TradeLicenseIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  application?: boolean | Prisma.TradeLicenseApplicationDefaultArgs<ExtArgs>
  fiscalYear?: boolean | Prisma.FiscalYearDefaultArgs<ExtArgs>
}

export type $TradeLicensePayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "TradeLicense"
  objects: {
    application: Prisma.$TradeLicenseApplicationPayload<ExtArgs>
    fiscalYear: Prisma.$FiscalYearPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    licenseNo: string | null
    trackingNo: string
    applicationId: string
    fiscalYearId: string
    licenseFee: number
    arrears: number
    arrearsFiscalYear: string | null
    discount: number
    vatAmount: number
    signboardTax: number
    professionalTax: number
    subCharge: number
    totalAmount: number
    paymentStatus: string
    paymentType: string | null
    paymentDate: Date | null
    issueDate: Date
    expiryDate: Date
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["tradeLicense"]>
  composites: {}
}

export type TradeLicenseGetPayload<S extends boolean | null | undefined | TradeLicenseDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$TradeLicensePayload, S>

export type TradeLicenseCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<TradeLicenseFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: TradeLicenseCountAggregateInputType | true
  }

export interface TradeLicenseDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['TradeLicense'], meta: { name: 'TradeLicense' } }
  /**
   * Find zero or one TradeLicense that matches the filter.
   * @param {TradeLicenseFindUniqueArgs} args - Arguments to find a TradeLicense
   * @example
   * // Get one TradeLicense
   * const tradeLicense = await prisma.tradeLicense.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends TradeLicenseFindUniqueArgs>(args: Prisma.SelectSubset<T, TradeLicenseFindUniqueArgs<ExtArgs>>): Prisma.Prisma__TradeLicenseClient<runtime.Types.Result.GetResult<Prisma.$TradeLicensePayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one TradeLicense that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {TradeLicenseFindUniqueOrThrowArgs} args - Arguments to find a TradeLicense
   * @example
   * // Get one TradeLicense
   * const tradeLicense = await prisma.tradeLicense.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends TradeLicenseFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, TradeLicenseFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__TradeLicenseClient<runtime.Types.Result.GetResult<Prisma.$TradeLicensePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first TradeLicense that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TradeLicenseFindFirstArgs} args - Arguments to find a TradeLicense
   * @example
   * // Get one TradeLicense
   * const tradeLicense = await prisma.tradeLicense.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends TradeLicenseFindFirstArgs>(args?: Prisma.SelectSubset<T, TradeLicenseFindFirstArgs<ExtArgs>>): Prisma.Prisma__TradeLicenseClient<runtime.Types.Result.GetResult<Prisma.$TradeLicensePayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first TradeLicense that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TradeLicenseFindFirstOrThrowArgs} args - Arguments to find a TradeLicense
   * @example
   * // Get one TradeLicense
   * const tradeLicense = await prisma.tradeLicense.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends TradeLicenseFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, TradeLicenseFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__TradeLicenseClient<runtime.Types.Result.GetResult<Prisma.$TradeLicensePayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more TradeLicenses that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TradeLicenseFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all TradeLicenses
   * const tradeLicenses = await prisma.tradeLicense.findMany()
   * 
   * // Get first 10 TradeLicenses
   * const tradeLicenses = await prisma.tradeLicense.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const tradeLicenseWithIdOnly = await prisma.tradeLicense.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends TradeLicenseFindManyArgs>(args?: Prisma.SelectSubset<T, TradeLicenseFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TradeLicensePayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a TradeLicense.
   * @param {TradeLicenseCreateArgs} args - Arguments to create a TradeLicense.
   * @example
   * // Create one TradeLicense
   * const TradeLicense = await prisma.tradeLicense.create({
   *   data: {
   *     // ... data to create a TradeLicense
   *   }
   * })
   * 
   */
  create<T extends TradeLicenseCreateArgs>(args: Prisma.SelectSubset<T, TradeLicenseCreateArgs<ExtArgs>>): Prisma.Prisma__TradeLicenseClient<runtime.Types.Result.GetResult<Prisma.$TradeLicensePayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many TradeLicenses.
   * @param {TradeLicenseCreateManyArgs} args - Arguments to create many TradeLicenses.
   * @example
   * // Create many TradeLicenses
   * const tradeLicense = await prisma.tradeLicense.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends TradeLicenseCreateManyArgs>(args?: Prisma.SelectSubset<T, TradeLicenseCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many TradeLicenses and returns the data saved in the database.
   * @param {TradeLicenseCreateManyAndReturnArgs} args - Arguments to create many TradeLicenses.
   * @example
   * // Create many TradeLicenses
   * const tradeLicense = await prisma.tradeLicense.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many TradeLicenses and only return the `id`
   * const tradeLicenseWithIdOnly = await prisma.tradeLicense.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends TradeLicenseCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, TradeLicenseCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TradeLicensePayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a TradeLicense.
   * @param {TradeLicenseDeleteArgs} args - Arguments to delete one TradeLicense.
   * @example
   * // Delete one TradeLicense
   * const TradeLicense = await prisma.tradeLicense.delete({
   *   where: {
   *     // ... filter to delete one TradeLicense
   *   }
   * })
   * 
   */
  delete<T extends TradeLicenseDeleteArgs>(args: Prisma.SelectSubset<T, TradeLicenseDeleteArgs<ExtArgs>>): Prisma.Prisma__TradeLicenseClient<runtime.Types.Result.GetResult<Prisma.$TradeLicensePayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one TradeLicense.
   * @param {TradeLicenseUpdateArgs} args - Arguments to update one TradeLicense.
   * @example
   * // Update one TradeLicense
   * const tradeLicense = await prisma.tradeLicense.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends TradeLicenseUpdateArgs>(args: Prisma.SelectSubset<T, TradeLicenseUpdateArgs<ExtArgs>>): Prisma.Prisma__TradeLicenseClient<runtime.Types.Result.GetResult<Prisma.$TradeLicensePayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more TradeLicenses.
   * @param {TradeLicenseDeleteManyArgs} args - Arguments to filter TradeLicenses to delete.
   * @example
   * // Delete a few TradeLicenses
   * const { count } = await prisma.tradeLicense.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends TradeLicenseDeleteManyArgs>(args?: Prisma.SelectSubset<T, TradeLicenseDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more TradeLicenses.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TradeLicenseUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many TradeLicenses
   * const tradeLicense = await prisma.tradeLicense.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends TradeLicenseUpdateManyArgs>(args: Prisma.SelectSubset<T, TradeLicenseUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more TradeLicenses and returns the data updated in the database.
   * @param {TradeLicenseUpdateManyAndReturnArgs} args - Arguments to update many TradeLicenses.
   * @example
   * // Update many TradeLicenses
   * const tradeLicense = await prisma.tradeLicense.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more TradeLicenses and only return the `id`
   * const tradeLicenseWithIdOnly = await prisma.tradeLicense.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends TradeLicenseUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, TradeLicenseUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TradeLicensePayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one TradeLicense.
   * @param {TradeLicenseUpsertArgs} args - Arguments to update or create a TradeLicense.
   * @example
   * // Update or create a TradeLicense
   * const tradeLicense = await prisma.tradeLicense.upsert({
   *   create: {
   *     // ... data to create a TradeLicense
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the TradeLicense we want to update
   *   }
   * })
   */
  upsert<T extends TradeLicenseUpsertArgs>(args: Prisma.SelectSubset<T, TradeLicenseUpsertArgs<ExtArgs>>): Prisma.Prisma__TradeLicenseClient<runtime.Types.Result.GetResult<Prisma.$TradeLicensePayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of TradeLicenses.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TradeLicenseCountArgs} args - Arguments to filter TradeLicenses to count.
   * @example
   * // Count the number of TradeLicenses
   * const count = await prisma.tradeLicense.count({
   *   where: {
   *     // ... the filter for the TradeLicenses we want to count
   *   }
   * })
  **/
  count<T extends TradeLicenseCountArgs>(
    args?: Prisma.Subset<T, TradeLicenseCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], TradeLicenseCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a TradeLicense.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TradeLicenseAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends TradeLicenseAggregateArgs>(args: Prisma.Subset<T, TradeLicenseAggregateArgs>): Prisma.PrismaPromise<GetTradeLicenseAggregateType<T>>

  /**
   * Group by TradeLicense.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TradeLicenseGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends TradeLicenseGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: TradeLicenseGroupByArgs['orderBy'] }
      : { orderBy?: TradeLicenseGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, TradeLicenseGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetTradeLicenseGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the TradeLicense model
 */
readonly fields: TradeLicenseFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for TradeLicense.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__TradeLicenseClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  application<T extends Prisma.TradeLicenseApplicationDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.TradeLicenseApplicationDefaultArgs<ExtArgs>>): Prisma.Prisma__TradeLicenseApplicationClient<runtime.Types.Result.GetResult<Prisma.$TradeLicenseApplicationPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  fiscalYear<T extends Prisma.FiscalYearDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.FiscalYearDefaultArgs<ExtArgs>>): Prisma.Prisma__FiscalYearClient<runtime.Types.Result.GetResult<Prisma.$FiscalYearPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the TradeLicense model
 */
export interface TradeLicenseFieldRefs {
  readonly id: Prisma.FieldRef<"TradeLicense", 'String'>
  readonly licenseNo: Prisma.FieldRef<"TradeLicense", 'String'>
  readonly trackingNo: Prisma.FieldRef<"TradeLicense", 'String'>
  readonly applicationId: Prisma.FieldRef<"TradeLicense", 'String'>
  readonly fiscalYearId: Prisma.FieldRef<"TradeLicense", 'String'>
  readonly licenseFee: Prisma.FieldRef<"TradeLicense", 'Float'>
  readonly arrears: Prisma.FieldRef<"TradeLicense", 'Float'>
  readonly arrearsFiscalYear: Prisma.FieldRef<"TradeLicense", 'String'>
  readonly discount: Prisma.FieldRef<"TradeLicense", 'Float'>
  readonly vatAmount: Prisma.FieldRef<"TradeLicense", 'Float'>
  readonly signboardTax: Prisma.FieldRef<"TradeLicense", 'Float'>
  readonly professionalTax: Prisma.FieldRef<"TradeLicense", 'Float'>
  readonly subCharge: Prisma.FieldRef<"TradeLicense", 'Float'>
  readonly totalAmount: Prisma.FieldRef<"TradeLicense", 'Float'>
  readonly paymentStatus: Prisma.FieldRef<"TradeLicense", 'String'>
  readonly paymentType: Prisma.FieldRef<"TradeLicense", 'String'>
  readonly paymentDate: Prisma.FieldRef<"TradeLicense", 'DateTime'>
  readonly issueDate: Prisma.FieldRef<"TradeLicense", 'DateTime'>
  readonly expiryDate: Prisma.FieldRef<"TradeLicense", 'DateTime'>
  readonly createdAt: Prisma.FieldRef<"TradeLicense", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"TradeLicense", 'DateTime'>
}
    

// Custom InputTypes
/**
 * TradeLicense findUnique
 */
export type TradeLicenseFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TradeLicense
   */
  select?: Prisma.TradeLicenseSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TradeLicense
   */
  omit?: Prisma.TradeLicenseOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TradeLicenseInclude<ExtArgs> | null
  /**
   * Filter, which TradeLicense to fetch.
   */
  where: Prisma.TradeLicenseWhereUniqueInput
}

/**
 * TradeLicense findUniqueOrThrow
 */
export type TradeLicenseFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TradeLicense
   */
  select?: Prisma.TradeLicenseSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TradeLicense
   */
  omit?: Prisma.TradeLicenseOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TradeLicenseInclude<ExtArgs> | null
  /**
   * Filter, which TradeLicense to fetch.
   */
  where: Prisma.TradeLicenseWhereUniqueInput
}

/**
 * TradeLicense findFirst
 */
export type TradeLicenseFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TradeLicense
   */
  select?: Prisma.TradeLicenseSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TradeLicense
   */
  omit?: Prisma.TradeLicenseOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TradeLicenseInclude<ExtArgs> | null
  /**
   * Filter, which TradeLicense to fetch.
   */
  where?: Prisma.TradeLicenseWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of TradeLicenses to fetch.
   */
  orderBy?: Prisma.TradeLicenseOrderByWithRelationInput | Prisma.TradeLicenseOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for TradeLicenses.
   */
  cursor?: Prisma.TradeLicenseWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` TradeLicenses from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` TradeLicenses.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of TradeLicenses.
   */
  distinct?: Prisma.TradeLicenseScalarFieldEnum | Prisma.TradeLicenseScalarFieldEnum[]
}

/**
 * TradeLicense findFirstOrThrow
 */
export type TradeLicenseFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TradeLicense
   */
  select?: Prisma.TradeLicenseSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TradeLicense
   */
  omit?: Prisma.TradeLicenseOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TradeLicenseInclude<ExtArgs> | null
  /**
   * Filter, which TradeLicense to fetch.
   */
  where?: Prisma.TradeLicenseWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of TradeLicenses to fetch.
   */
  orderBy?: Prisma.TradeLicenseOrderByWithRelationInput | Prisma.TradeLicenseOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for TradeLicenses.
   */
  cursor?: Prisma.TradeLicenseWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` TradeLicenses from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` TradeLicenses.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of TradeLicenses.
   */
  distinct?: Prisma.TradeLicenseScalarFieldEnum | Prisma.TradeLicenseScalarFieldEnum[]
}

/**
 * TradeLicense findMany
 */
export type TradeLicenseFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TradeLicense
   */
  select?: Prisma.TradeLicenseSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TradeLicense
   */
  omit?: Prisma.TradeLicenseOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TradeLicenseInclude<ExtArgs> | null
  /**
   * Filter, which TradeLicenses to fetch.
   */
  where?: Prisma.TradeLicenseWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of TradeLicenses to fetch.
   */
  orderBy?: Prisma.TradeLicenseOrderByWithRelationInput | Prisma.TradeLicenseOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing TradeLicenses.
   */
  cursor?: Prisma.TradeLicenseWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` TradeLicenses from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` TradeLicenses.
   */
  skip?: number
  distinct?: Prisma.TradeLicenseScalarFieldEnum | Prisma.TradeLicenseScalarFieldEnum[]
}

/**
 * TradeLicense create
 */
export type TradeLicenseCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TradeLicense
   */
  select?: Prisma.TradeLicenseSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TradeLicense
   */
  omit?: Prisma.TradeLicenseOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TradeLicenseInclude<ExtArgs> | null
  /**
   * The data needed to create a TradeLicense.
   */
  data: Prisma.XOR<Prisma.TradeLicenseCreateInput, Prisma.TradeLicenseUncheckedCreateInput>
}

/**
 * TradeLicense createMany
 */
export type TradeLicenseCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many TradeLicenses.
   */
  data: Prisma.TradeLicenseCreateManyInput | Prisma.TradeLicenseCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * TradeLicense createManyAndReturn
 */
export type TradeLicenseCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TradeLicense
   */
  select?: Prisma.TradeLicenseSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the TradeLicense
   */
  omit?: Prisma.TradeLicenseOmit<ExtArgs> | null
  /**
   * The data used to create many TradeLicenses.
   */
  data: Prisma.TradeLicenseCreateManyInput | Prisma.TradeLicenseCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TradeLicenseIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * TradeLicense update
 */
export type TradeLicenseUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TradeLicense
   */
  select?: Prisma.TradeLicenseSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TradeLicense
   */
  omit?: Prisma.TradeLicenseOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TradeLicenseInclude<ExtArgs> | null
  /**
   * The data needed to update a TradeLicense.
   */
  data: Prisma.XOR<Prisma.TradeLicenseUpdateInput, Prisma.TradeLicenseUncheckedUpdateInput>
  /**
   * Choose, which TradeLicense to update.
   */
  where: Prisma.TradeLicenseWhereUniqueInput
}

/**
 * TradeLicense updateMany
 */
export type TradeLicenseUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update TradeLicenses.
   */
  data: Prisma.XOR<Prisma.TradeLicenseUpdateManyMutationInput, Prisma.TradeLicenseUncheckedUpdateManyInput>
  /**
   * Filter which TradeLicenses to update
   */
  where?: Prisma.TradeLicenseWhereInput
  /**
   * Limit how many TradeLicenses to update.
   */
  limit?: number
}

/**
 * TradeLicense updateManyAndReturn
 */
export type TradeLicenseUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TradeLicense
   */
  select?: Prisma.TradeLicenseSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the TradeLicense
   */
  omit?: Prisma.TradeLicenseOmit<ExtArgs> | null
  /**
   * The data used to update TradeLicenses.
   */
  data: Prisma.XOR<Prisma.TradeLicenseUpdateManyMutationInput, Prisma.TradeLicenseUncheckedUpdateManyInput>
  /**
   * Filter which TradeLicenses to update
   */
  where?: Prisma.TradeLicenseWhereInput
  /**
   * Limit how many TradeLicenses to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TradeLicenseIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * TradeLicense upsert
 */
export type TradeLicenseUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TradeLicense
   */
  select?: Prisma.TradeLicenseSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TradeLicense
   */
  omit?: Prisma.TradeLicenseOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TradeLicenseInclude<ExtArgs> | null
  /**
   * The filter to search for the TradeLicense to update in case it exists.
   */
  where: Prisma.TradeLicenseWhereUniqueInput
  /**
   * In case the TradeLicense found by the `where` argument doesn't exist, create a new TradeLicense with this data.
   */
  create: Prisma.XOR<Prisma.TradeLicenseCreateInput, Prisma.TradeLicenseUncheckedCreateInput>
  /**
   * In case the TradeLicense was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.TradeLicenseUpdateInput, Prisma.TradeLicenseUncheckedUpdateInput>
}

/**
 * TradeLicense delete
 */
export type TradeLicenseDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TradeLicense
   */
  select?: Prisma.TradeLicenseSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TradeLicense
   */
  omit?: Prisma.TradeLicenseOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TradeLicenseInclude<ExtArgs> | null
  /**
   * Filter which TradeLicense to delete.
   */
  where: Prisma.TradeLicenseWhereUniqueInput
}

/**
 * TradeLicense deleteMany
 */
export type TradeLicenseDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which TradeLicenses to delete
   */
  where?: Prisma.TradeLicenseWhereInput
  /**
   * Limit how many TradeLicenses to delete.
   */
  limit?: number
}

/**
 * TradeLicense without action
 */
export type TradeLicenseDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TradeLicense
   */
  select?: Prisma.TradeLicenseSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TradeLicense
   */
  omit?: Prisma.TradeLicenseOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TradeLicenseInclude<ExtArgs> | null
}
