
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file should be your main import to use Prisma. Through it you get access to all the models, enums, and input types.
 * If you're looking for something you can import in the client-side of your application, please refer to the `browser.ts` file instead.
 *
 * 🟢 You can import this file directly.
 */

import * as process from 'node:process'
import * as path from 'node:path'
import { fileURLToPath } from 'node:url'
globalThis['__dirname'] = path.dirname(fileURLToPath(import.meta.url))

import * as runtime from "@prisma/client/runtime/client"
import * as $Enums from "./enums"
import * as $Class from "./internal/class"
import * as Prisma from "./internal/prismaNamespace"

export * as $Enums from './enums'
export * from "./enums"
/**
 * ## Prisma Client
 * 
 * Type-safe database client for TypeScript
 * @example
 * ```
 * const prisma = new PrismaClient()
 * // Fetch zero or more CitizenApplications
 * const citizenApplications = await prisma.citizenApplication.findMany()
 * ```
 * 
 * Read more in our [docs](https://pris.ly/d/client).
 */
export const PrismaClient = $Class.getPrismaClientClass()
export type PrismaClient<LogOpts extends Prisma.LogLevel = never, OmitOpts extends Prisma.PrismaClientOptions["omit"] = Prisma.PrismaClientOptions["omit"], ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = $Class.PrismaClient<LogOpts, OmitOpts, ExtArgs>
export { Prisma }

/**
 * Model CitizenApplication
 * 
 */
export type CitizenApplication = Prisma.CitizenApplicationModel
/**
 * Model Citizen
 * 
 */
export type Citizen = Prisma.CitizenModel
/**
 * Model Ward
 * 
 */
export type Ward = Prisma.WardModel
/**
 * Model Village
 * 
 */
export type Village = Prisma.VillageModel
/**
 * Model FamilyApplication
 * 
 */
export type FamilyApplication = Prisma.FamilyApplicationModel
/**
 * Model FamilyMember
 * 
 */
export type FamilyMember = Prisma.FamilyMemberModel
/**
 * Model AssessmentApplication
 * 
 */
export type AssessmentApplication = Prisma.AssessmentApplicationModel
/**
 * Model HoldingTax
 * 
 */
export type HoldingTax = Prisma.HoldingTaxModel
/**
 * Model FiscalYear
 * 
 */
export type FiscalYear = Prisma.FiscalYearModel
/**
 * Model CertificateCounter
 * 
 */
export type CertificateCounter = Prisma.CertificateCounterModel
/**
 * Model TradeLicenseCategory
 * 
 */
export type TradeLicenseCategory = Prisma.TradeLicenseCategoryModel
/**
 * Model TradeLicenseApplication
 * 
 */
export type TradeLicenseApplication = Prisma.TradeLicenseApplicationModel
/**
 * Model TradeLicense
 * 
 */
export type TradeLicense = Prisma.TradeLicenseModel
/**
 * Model CertificateApplication
 * 
 */
export type CertificateApplication = Prisma.CertificateApplicationModel
/**
 * Model SuccessionApplication
 * 
 */
export type SuccessionApplication = Prisma.SuccessionApplicationModel
/**
 * Model Heir
 * 
 */
export type Heir = Prisma.HeirModel
