
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Union` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model Union
 * 
 */
export type UnionModel = runtime.Types.Result.DefaultSelection<Prisma.$UnionPayload>

export type AggregateUnion = {
  _count: UnionCountAggregateOutputType | null
  _min: UnionMinAggregateOutputType | null
  _max: UnionMaxAggregateOutputType | null
}

export type UnionMinAggregateOutputType = {
  id: string | null
  name: string | null
  nameBn: string | null
  geoCode: string | null
  upazilaId: string | null
}

export type UnionMaxAggregateOutputType = {
  id: string | null
  name: string | null
  nameBn: string | null
  geoCode: string | null
  upazilaId: string | null
}

export type UnionCountAggregateOutputType = {
  id: number
  name: number
  nameBn: number
  geoCode: number
  upazilaId: number
  _all: number
}


export type UnionMinAggregateInputType = {
  id?: true
  name?: true
  nameBn?: true
  geoCode?: true
  upazilaId?: true
}

export type UnionMaxAggregateInputType = {
  id?: true
  name?: true
  nameBn?: true
  geoCode?: true
  upazilaId?: true
}

export type UnionCountAggregateInputType = {
  id?: true
  name?: true
  nameBn?: true
  geoCode?: true
  upazilaId?: true
  _all?: true
}

export type UnionAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Union to aggregate.
   */
  where?: Prisma.UnionWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Unions to fetch.
   */
  orderBy?: Prisma.UnionOrderByWithRelationInput | Prisma.UnionOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.UnionWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Unions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Unions.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Unions
  **/
  _count?: true | UnionCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: UnionMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: UnionMaxAggregateInputType
}

export type GetUnionAggregateType<T extends UnionAggregateArgs> = {
      [P in keyof T & keyof AggregateUnion]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateUnion[P]>
    : Prisma.GetScalarType<T[P], AggregateUnion[P]>
}




export type UnionGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.UnionWhereInput
  orderBy?: Prisma.UnionOrderByWithAggregationInput | Prisma.UnionOrderByWithAggregationInput[]
  by: Prisma.UnionScalarFieldEnum[] | Prisma.UnionScalarFieldEnum
  having?: Prisma.UnionScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: UnionCountAggregateInputType | true
  _min?: UnionMinAggregateInputType
  _max?: UnionMaxAggregateInputType
}

export type UnionGroupByOutputType = {
  id: string
  name: string
  nameBn: string
  geoCode: string | null
  upazilaId: string
  _count: UnionCountAggregateOutputType | null
  _min: UnionMinAggregateOutputType | null
  _max: UnionMaxAggregateOutputType | null
}

type GetUnionGroupByPayload<T extends UnionGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<UnionGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof UnionGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], UnionGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], UnionGroupByOutputType[P]>
      }
    >
  >



export type UnionWhereInput = {
  AND?: Prisma.UnionWhereInput | Prisma.UnionWhereInput[]
  OR?: Prisma.UnionWhereInput[]
  NOT?: Prisma.UnionWhereInput | Prisma.UnionWhereInput[]
  id?: Prisma.StringFilter<"Union"> | string
  name?: Prisma.StringFilter<"Union"> | string
  nameBn?: Prisma.StringFilter<"Union"> | string
  geoCode?: Prisma.StringNullableFilter<"Union"> | string | null
  upazilaId?: Prisma.StringFilter<"Union"> | string
  upazila?: Prisma.XOR<Prisma.UpazilaScalarRelationFilter, Prisma.UpazilaWhereInput>
  tenants?: Prisma.TenantListRelationFilter
}

export type UnionOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  nameBn?: Prisma.SortOrder
  geoCode?: Prisma.SortOrderInput | Prisma.SortOrder
  upazilaId?: Prisma.SortOrder
  upazila?: Prisma.UpazilaOrderByWithRelationInput
  tenants?: Prisma.TenantOrderByRelationAggregateInput
}

export type UnionWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.UnionWhereInput | Prisma.UnionWhereInput[]
  OR?: Prisma.UnionWhereInput[]
  NOT?: Prisma.UnionWhereInput | Prisma.UnionWhereInput[]
  name?: Prisma.StringFilter<"Union"> | string
  nameBn?: Prisma.StringFilter<"Union"> | string
  geoCode?: Prisma.StringNullableFilter<"Union"> | string | null
  upazilaId?: Prisma.StringFilter<"Union"> | string
  upazila?: Prisma.XOR<Prisma.UpazilaScalarRelationFilter, Prisma.UpazilaWhereInput>
  tenants?: Prisma.TenantListRelationFilter
}, "id">

export type UnionOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  nameBn?: Prisma.SortOrder
  geoCode?: Prisma.SortOrderInput | Prisma.SortOrder
  upazilaId?: Prisma.SortOrder
  _count?: Prisma.UnionCountOrderByAggregateInput
  _max?: Prisma.UnionMaxOrderByAggregateInput
  _min?: Prisma.UnionMinOrderByAggregateInput
}

export type UnionScalarWhereWithAggregatesInput = {
  AND?: Prisma.UnionScalarWhereWithAggregatesInput | Prisma.UnionScalarWhereWithAggregatesInput[]
  OR?: Prisma.UnionScalarWhereWithAggregatesInput[]
  NOT?: Prisma.UnionScalarWhereWithAggregatesInput | Prisma.UnionScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"Union"> | string
  name?: Prisma.StringWithAggregatesFilter<"Union"> | string
  nameBn?: Prisma.StringWithAggregatesFilter<"Union"> | string
  geoCode?: Prisma.StringNullableWithAggregatesFilter<"Union"> | string | null
  upazilaId?: Prisma.StringWithAggregatesFilter<"Union"> | string
}

export type UnionCreateInput = {
  id?: string
  name: string
  nameBn: string
  geoCode?: string | null
  upazila: Prisma.UpazilaCreateNestedOneWithoutUnionsInput
  tenants?: Prisma.TenantCreateNestedManyWithoutUnionInput
}

export type UnionUncheckedCreateInput = {
  id?: string
  name: string
  nameBn: string
  geoCode?: string | null
  upazilaId: string
  tenants?: Prisma.TenantUncheckedCreateNestedManyWithoutUnionInput
}

export type UnionUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  nameBn?: Prisma.StringFieldUpdateOperationsInput | string
  geoCode?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  upazila?: Prisma.UpazilaUpdateOneRequiredWithoutUnionsNestedInput
  tenants?: Prisma.TenantUpdateManyWithoutUnionNestedInput
}

export type UnionUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  nameBn?: Prisma.StringFieldUpdateOperationsInput | string
  geoCode?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  upazilaId?: Prisma.StringFieldUpdateOperationsInput | string
  tenants?: Prisma.TenantUncheckedUpdateManyWithoutUnionNestedInput
}

export type UnionCreateManyInput = {
  id?: string
  name: string
  nameBn: string
  geoCode?: string | null
  upazilaId: string
}

export type UnionUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  nameBn?: Prisma.StringFieldUpdateOperationsInput | string
  geoCode?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type UnionUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  nameBn?: Prisma.StringFieldUpdateOperationsInput | string
  geoCode?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  upazilaId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type UnionScalarRelationFilter = {
  is?: Prisma.UnionWhereInput
  isNot?: Prisma.UnionWhereInput
}

export type UnionListRelationFilter = {
  every?: Prisma.UnionWhereInput
  some?: Prisma.UnionWhereInput
  none?: Prisma.UnionWhereInput
}

export type UnionOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type UnionCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  nameBn?: Prisma.SortOrder
  geoCode?: Prisma.SortOrder
  upazilaId?: Prisma.SortOrder
}

export type UnionMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  nameBn?: Prisma.SortOrder
  geoCode?: Prisma.SortOrder
  upazilaId?: Prisma.SortOrder
}

export type UnionMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  nameBn?: Prisma.SortOrder
  geoCode?: Prisma.SortOrder
  upazilaId?: Prisma.SortOrder
}

export type UnionCreateNestedOneWithoutTenantsInput = {
  create?: Prisma.XOR<Prisma.UnionCreateWithoutTenantsInput, Prisma.UnionUncheckedCreateWithoutTenantsInput>
  connectOrCreate?: Prisma.UnionCreateOrConnectWithoutTenantsInput
  connect?: Prisma.UnionWhereUniqueInput
}

export type UnionUpdateOneRequiredWithoutTenantsNestedInput = {
  create?: Prisma.XOR<Prisma.UnionCreateWithoutTenantsInput, Prisma.UnionUncheckedCreateWithoutTenantsInput>
  connectOrCreate?: Prisma.UnionCreateOrConnectWithoutTenantsInput
  upsert?: Prisma.UnionUpsertWithoutTenantsInput
  connect?: Prisma.UnionWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.UnionUpdateToOneWithWhereWithoutTenantsInput, Prisma.UnionUpdateWithoutTenantsInput>, Prisma.UnionUncheckedUpdateWithoutTenantsInput>
}

export type UnionCreateNestedManyWithoutUpazilaInput = {
  create?: Prisma.XOR<Prisma.UnionCreateWithoutUpazilaInput, Prisma.UnionUncheckedCreateWithoutUpazilaInput> | Prisma.UnionCreateWithoutUpazilaInput[] | Prisma.UnionUncheckedCreateWithoutUpazilaInput[]
  connectOrCreate?: Prisma.UnionCreateOrConnectWithoutUpazilaInput | Prisma.UnionCreateOrConnectWithoutUpazilaInput[]
  createMany?: Prisma.UnionCreateManyUpazilaInputEnvelope
  connect?: Prisma.UnionWhereUniqueInput | Prisma.UnionWhereUniqueInput[]
}

export type UnionUncheckedCreateNestedManyWithoutUpazilaInput = {
  create?: Prisma.XOR<Prisma.UnionCreateWithoutUpazilaInput, Prisma.UnionUncheckedCreateWithoutUpazilaInput> | Prisma.UnionCreateWithoutUpazilaInput[] | Prisma.UnionUncheckedCreateWithoutUpazilaInput[]
  connectOrCreate?: Prisma.UnionCreateOrConnectWithoutUpazilaInput | Prisma.UnionCreateOrConnectWithoutUpazilaInput[]
  createMany?: Prisma.UnionCreateManyUpazilaInputEnvelope
  connect?: Prisma.UnionWhereUniqueInput | Prisma.UnionWhereUniqueInput[]
}

export type UnionUpdateManyWithoutUpazilaNestedInput = {
  create?: Prisma.XOR<Prisma.UnionCreateWithoutUpazilaInput, Prisma.UnionUncheckedCreateWithoutUpazilaInput> | Prisma.UnionCreateWithoutUpazilaInput[] | Prisma.UnionUncheckedCreateWithoutUpazilaInput[]
  connectOrCreate?: Prisma.UnionCreateOrConnectWithoutUpazilaInput | Prisma.UnionCreateOrConnectWithoutUpazilaInput[]
  upsert?: Prisma.UnionUpsertWithWhereUniqueWithoutUpazilaInput | Prisma.UnionUpsertWithWhereUniqueWithoutUpazilaInput[]
  createMany?: Prisma.UnionCreateManyUpazilaInputEnvelope
  set?: Prisma.UnionWhereUniqueInput | Prisma.UnionWhereUniqueInput[]
  disconnect?: Prisma.UnionWhereUniqueInput | Prisma.UnionWhereUniqueInput[]
  delete?: Prisma.UnionWhereUniqueInput | Prisma.UnionWhereUniqueInput[]
  connect?: Prisma.UnionWhereUniqueInput | Prisma.UnionWhereUniqueInput[]
  update?: Prisma.UnionUpdateWithWhereUniqueWithoutUpazilaInput | Prisma.UnionUpdateWithWhereUniqueWithoutUpazilaInput[]
  updateMany?: Prisma.UnionUpdateManyWithWhereWithoutUpazilaInput | Prisma.UnionUpdateManyWithWhereWithoutUpazilaInput[]
  deleteMany?: Prisma.UnionScalarWhereInput | Prisma.UnionScalarWhereInput[]
}

export type UnionUncheckedUpdateManyWithoutUpazilaNestedInput = {
  create?: Prisma.XOR<Prisma.UnionCreateWithoutUpazilaInput, Prisma.UnionUncheckedCreateWithoutUpazilaInput> | Prisma.UnionCreateWithoutUpazilaInput[] | Prisma.UnionUncheckedCreateWithoutUpazilaInput[]
  connectOrCreate?: Prisma.UnionCreateOrConnectWithoutUpazilaInput | Prisma.UnionCreateOrConnectWithoutUpazilaInput[]
  upsert?: Prisma.UnionUpsertWithWhereUniqueWithoutUpazilaInput | Prisma.UnionUpsertWithWhereUniqueWithoutUpazilaInput[]
  createMany?: Prisma.UnionCreateManyUpazilaInputEnvelope
  set?: Prisma.UnionWhereUniqueInput | Prisma.UnionWhereUniqueInput[]
  disconnect?: Prisma.UnionWhereUniqueInput | Prisma.UnionWhereUniqueInput[]
  delete?: Prisma.UnionWhereUniqueInput | Prisma.UnionWhereUniqueInput[]
  connect?: Prisma.UnionWhereUniqueInput | Prisma.UnionWhereUniqueInput[]
  update?: Prisma.UnionUpdateWithWhereUniqueWithoutUpazilaInput | Prisma.UnionUpdateWithWhereUniqueWithoutUpazilaInput[]
  updateMany?: Prisma.UnionUpdateManyWithWhereWithoutUpazilaInput | Prisma.UnionUpdateManyWithWhereWithoutUpazilaInput[]
  deleteMany?: Prisma.UnionScalarWhereInput | Prisma.UnionScalarWhereInput[]
}

export type UnionCreateWithoutTenantsInput = {
  id?: string
  name: string
  nameBn: string
  geoCode?: string | null
  upazila: Prisma.UpazilaCreateNestedOneWithoutUnionsInput
}

export type UnionUncheckedCreateWithoutTenantsInput = {
  id?: string
  name: string
  nameBn: string
  geoCode?: string | null
  upazilaId: string
}

export type UnionCreateOrConnectWithoutTenantsInput = {
  where: Prisma.UnionWhereUniqueInput
  create: Prisma.XOR<Prisma.UnionCreateWithoutTenantsInput, Prisma.UnionUncheckedCreateWithoutTenantsInput>
}

export type UnionUpsertWithoutTenantsInput = {
  update: Prisma.XOR<Prisma.UnionUpdateWithoutTenantsInput, Prisma.UnionUncheckedUpdateWithoutTenantsInput>
  create: Prisma.XOR<Prisma.UnionCreateWithoutTenantsInput, Prisma.UnionUncheckedCreateWithoutTenantsInput>
  where?: Prisma.UnionWhereInput
}

export type UnionUpdateToOneWithWhereWithoutTenantsInput = {
  where?: Prisma.UnionWhereInput
  data: Prisma.XOR<Prisma.UnionUpdateWithoutTenantsInput, Prisma.UnionUncheckedUpdateWithoutTenantsInput>
}

export type UnionUpdateWithoutTenantsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  nameBn?: Prisma.StringFieldUpdateOperationsInput | string
  geoCode?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  upazila?: Prisma.UpazilaUpdateOneRequiredWithoutUnionsNestedInput
}

export type UnionUncheckedUpdateWithoutTenantsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  nameBn?: Prisma.StringFieldUpdateOperationsInput | string
  geoCode?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  upazilaId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type UnionCreateWithoutUpazilaInput = {
  id?: string
  name: string
  nameBn: string
  geoCode?: string | null
  tenants?: Prisma.TenantCreateNestedManyWithoutUnionInput
}

export type UnionUncheckedCreateWithoutUpazilaInput = {
  id?: string
  name: string
  nameBn: string
  geoCode?: string | null
  tenants?: Prisma.TenantUncheckedCreateNestedManyWithoutUnionInput
}

export type UnionCreateOrConnectWithoutUpazilaInput = {
  where: Prisma.UnionWhereUniqueInput
  create: Prisma.XOR<Prisma.UnionCreateWithoutUpazilaInput, Prisma.UnionUncheckedCreateWithoutUpazilaInput>
}

export type UnionCreateManyUpazilaInputEnvelope = {
  data: Prisma.UnionCreateManyUpazilaInput | Prisma.UnionCreateManyUpazilaInput[]
  skipDuplicates?: boolean
}

export type UnionUpsertWithWhereUniqueWithoutUpazilaInput = {
  where: Prisma.UnionWhereUniqueInput
  update: Prisma.XOR<Prisma.UnionUpdateWithoutUpazilaInput, Prisma.UnionUncheckedUpdateWithoutUpazilaInput>
  create: Prisma.XOR<Prisma.UnionCreateWithoutUpazilaInput, Prisma.UnionUncheckedCreateWithoutUpazilaInput>
}

export type UnionUpdateWithWhereUniqueWithoutUpazilaInput = {
  where: Prisma.UnionWhereUniqueInput
  data: Prisma.XOR<Prisma.UnionUpdateWithoutUpazilaInput, Prisma.UnionUncheckedUpdateWithoutUpazilaInput>
}

export type UnionUpdateManyWithWhereWithoutUpazilaInput = {
  where: Prisma.UnionScalarWhereInput
  data: Prisma.XOR<Prisma.UnionUpdateManyMutationInput, Prisma.UnionUncheckedUpdateManyWithoutUpazilaInput>
}

export type UnionScalarWhereInput = {
  AND?: Prisma.UnionScalarWhereInput | Prisma.UnionScalarWhereInput[]
  OR?: Prisma.UnionScalarWhereInput[]
  NOT?: Prisma.UnionScalarWhereInput | Prisma.UnionScalarWhereInput[]
  id?: Prisma.StringFilter<"Union"> | string
  name?: Prisma.StringFilter<"Union"> | string
  nameBn?: Prisma.StringFilter<"Union"> | string
  geoCode?: Prisma.StringNullableFilter<"Union"> | string | null
  upazilaId?: Prisma.StringFilter<"Union"> | string
}

export type UnionCreateManyUpazilaInput = {
  id?: string
  name: string
  nameBn: string
  geoCode?: string | null
}

export type UnionUpdateWithoutUpazilaInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  nameBn?: Prisma.StringFieldUpdateOperationsInput | string
  geoCode?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  tenants?: Prisma.TenantUpdateManyWithoutUnionNestedInput
}

export type UnionUncheckedUpdateWithoutUpazilaInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  nameBn?: Prisma.StringFieldUpdateOperationsInput | string
  geoCode?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  tenants?: Prisma.TenantUncheckedUpdateManyWithoutUnionNestedInput
}

export type UnionUncheckedUpdateManyWithoutUpazilaInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  nameBn?: Prisma.StringFieldUpdateOperationsInput | string
  geoCode?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}


/**
 * Count Type UnionCountOutputType
 */

export type UnionCountOutputType = {
  tenants: number
}

export type UnionCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  tenants?: boolean | UnionCountOutputTypeCountTenantsArgs
}

/**
 * UnionCountOutputType without action
 */
export type UnionCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UnionCountOutputType
   */
  select?: Prisma.UnionCountOutputTypeSelect<ExtArgs> | null
}

/**
 * UnionCountOutputType without action
 */
export type UnionCountOutputTypeCountTenantsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.TenantWhereInput
}


export type UnionSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  nameBn?: boolean
  geoCode?: boolean
  upazilaId?: boolean
  upazila?: boolean | Prisma.UpazilaDefaultArgs<ExtArgs>
  tenants?: boolean | Prisma.Union$tenantsArgs<ExtArgs>
  _count?: boolean | Prisma.UnionCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["union"]>

export type UnionSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  nameBn?: boolean
  geoCode?: boolean
  upazilaId?: boolean
  upazila?: boolean | Prisma.UpazilaDefaultArgs<ExtArgs>
}, ExtArgs["result"]["union"]>

export type UnionSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  nameBn?: boolean
  geoCode?: boolean
  upazilaId?: boolean
  upazila?: boolean | Prisma.UpazilaDefaultArgs<ExtArgs>
}, ExtArgs["result"]["union"]>

export type UnionSelectScalar = {
  id?: boolean
  name?: boolean
  nameBn?: boolean
  geoCode?: boolean
  upazilaId?: boolean
}

export type UnionOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "name" | "nameBn" | "geoCode" | "upazilaId", ExtArgs["result"]["union"]>
export type UnionInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  upazila?: boolean | Prisma.UpazilaDefaultArgs<ExtArgs>
  tenants?: boolean | Prisma.Union$tenantsArgs<ExtArgs>
  _count?: boolean | Prisma.UnionCountOutputTypeDefaultArgs<ExtArgs>
}
export type UnionIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  upazila?: boolean | Prisma.UpazilaDefaultArgs<ExtArgs>
}
export type UnionIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  upazila?: boolean | Prisma.UpazilaDefaultArgs<ExtArgs>
}

export type $UnionPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Union"
  objects: {
    upazila: Prisma.$UpazilaPayload<ExtArgs>
    tenants: Prisma.$TenantPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    name: string
    nameBn: string
    geoCode: string | null
    upazilaId: string
  }, ExtArgs["result"]["union"]>
  composites: {}
}

export type UnionGetPayload<S extends boolean | null | undefined | UnionDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$UnionPayload, S>

export type UnionCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<UnionFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: UnionCountAggregateInputType | true
  }

export interface UnionDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Union'], meta: { name: 'Union' } }
  /**
   * Find zero or one Union that matches the filter.
   * @param {UnionFindUniqueArgs} args - Arguments to find a Union
   * @example
   * // Get one Union
   * const union = await prisma.union.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends UnionFindUniqueArgs>(args: Prisma.SelectSubset<T, UnionFindUniqueArgs<ExtArgs>>): Prisma.Prisma__UnionClient<runtime.Types.Result.GetResult<Prisma.$UnionPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Union that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {UnionFindUniqueOrThrowArgs} args - Arguments to find a Union
   * @example
   * // Get one Union
   * const union = await prisma.union.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends UnionFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, UnionFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__UnionClient<runtime.Types.Result.GetResult<Prisma.$UnionPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Union that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UnionFindFirstArgs} args - Arguments to find a Union
   * @example
   * // Get one Union
   * const union = await prisma.union.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends UnionFindFirstArgs>(args?: Prisma.SelectSubset<T, UnionFindFirstArgs<ExtArgs>>): Prisma.Prisma__UnionClient<runtime.Types.Result.GetResult<Prisma.$UnionPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Union that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UnionFindFirstOrThrowArgs} args - Arguments to find a Union
   * @example
   * // Get one Union
   * const union = await prisma.union.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends UnionFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, UnionFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__UnionClient<runtime.Types.Result.GetResult<Prisma.$UnionPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Unions that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UnionFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Unions
   * const unions = await prisma.union.findMany()
   * 
   * // Get first 10 Unions
   * const unions = await prisma.union.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const unionWithIdOnly = await prisma.union.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends UnionFindManyArgs>(args?: Prisma.SelectSubset<T, UnionFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$UnionPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Union.
   * @param {UnionCreateArgs} args - Arguments to create a Union.
   * @example
   * // Create one Union
   * const Union = await prisma.union.create({
   *   data: {
   *     // ... data to create a Union
   *   }
   * })
   * 
   */
  create<T extends UnionCreateArgs>(args: Prisma.SelectSubset<T, UnionCreateArgs<ExtArgs>>): Prisma.Prisma__UnionClient<runtime.Types.Result.GetResult<Prisma.$UnionPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Unions.
   * @param {UnionCreateManyArgs} args - Arguments to create many Unions.
   * @example
   * // Create many Unions
   * const union = await prisma.union.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends UnionCreateManyArgs>(args?: Prisma.SelectSubset<T, UnionCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Unions and returns the data saved in the database.
   * @param {UnionCreateManyAndReturnArgs} args - Arguments to create many Unions.
   * @example
   * // Create many Unions
   * const union = await prisma.union.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Unions and only return the `id`
   * const unionWithIdOnly = await prisma.union.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends UnionCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, UnionCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$UnionPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Union.
   * @param {UnionDeleteArgs} args - Arguments to delete one Union.
   * @example
   * // Delete one Union
   * const Union = await prisma.union.delete({
   *   where: {
   *     // ... filter to delete one Union
   *   }
   * })
   * 
   */
  delete<T extends UnionDeleteArgs>(args: Prisma.SelectSubset<T, UnionDeleteArgs<ExtArgs>>): Prisma.Prisma__UnionClient<runtime.Types.Result.GetResult<Prisma.$UnionPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Union.
   * @param {UnionUpdateArgs} args - Arguments to update one Union.
   * @example
   * // Update one Union
   * const union = await prisma.union.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends UnionUpdateArgs>(args: Prisma.SelectSubset<T, UnionUpdateArgs<ExtArgs>>): Prisma.Prisma__UnionClient<runtime.Types.Result.GetResult<Prisma.$UnionPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Unions.
   * @param {UnionDeleteManyArgs} args - Arguments to filter Unions to delete.
   * @example
   * // Delete a few Unions
   * const { count } = await prisma.union.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends UnionDeleteManyArgs>(args?: Prisma.SelectSubset<T, UnionDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Unions.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UnionUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Unions
   * const union = await prisma.union.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends UnionUpdateManyArgs>(args: Prisma.SelectSubset<T, UnionUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Unions and returns the data updated in the database.
   * @param {UnionUpdateManyAndReturnArgs} args - Arguments to update many Unions.
   * @example
   * // Update many Unions
   * const union = await prisma.union.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Unions and only return the `id`
   * const unionWithIdOnly = await prisma.union.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends UnionUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, UnionUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$UnionPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Union.
   * @param {UnionUpsertArgs} args - Arguments to update or create a Union.
   * @example
   * // Update or create a Union
   * const union = await prisma.union.upsert({
   *   create: {
   *     // ... data to create a Union
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Union we want to update
   *   }
   * })
   */
  upsert<T extends UnionUpsertArgs>(args: Prisma.SelectSubset<T, UnionUpsertArgs<ExtArgs>>): Prisma.Prisma__UnionClient<runtime.Types.Result.GetResult<Prisma.$UnionPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Unions.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UnionCountArgs} args - Arguments to filter Unions to count.
   * @example
   * // Count the number of Unions
   * const count = await prisma.union.count({
   *   where: {
   *     // ... the filter for the Unions we want to count
   *   }
   * })
  **/
  count<T extends UnionCountArgs>(
    args?: Prisma.Subset<T, UnionCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], UnionCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Union.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UnionAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends UnionAggregateArgs>(args: Prisma.Subset<T, UnionAggregateArgs>): Prisma.PrismaPromise<GetUnionAggregateType<T>>

  /**
   * Group by Union.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UnionGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends UnionGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: UnionGroupByArgs['orderBy'] }
      : { orderBy?: UnionGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, UnionGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetUnionGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Union model
 */
readonly fields: UnionFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Union.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__UnionClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  upazila<T extends Prisma.UpazilaDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.UpazilaDefaultArgs<ExtArgs>>): Prisma.Prisma__UpazilaClient<runtime.Types.Result.GetResult<Prisma.$UpazilaPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  tenants<T extends Prisma.Union$tenantsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Union$tenantsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TenantPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Union model
 */
export interface UnionFieldRefs {
  readonly id: Prisma.FieldRef<"Union", 'String'>
  readonly name: Prisma.FieldRef<"Union", 'String'>
  readonly nameBn: Prisma.FieldRef<"Union", 'String'>
  readonly geoCode: Prisma.FieldRef<"Union", 'String'>
  readonly upazilaId: Prisma.FieldRef<"Union", 'String'>
}
    

// Custom InputTypes
/**
 * Union findUnique
 */
export type UnionFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Union
   */
  select?: Prisma.UnionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Union
   */
  omit?: Prisma.UnionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UnionInclude<ExtArgs> | null
  /**
   * Filter, which Union to fetch.
   */
  where: Prisma.UnionWhereUniqueInput
}

/**
 * Union findUniqueOrThrow
 */
export type UnionFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Union
   */
  select?: Prisma.UnionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Union
   */
  omit?: Prisma.UnionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UnionInclude<ExtArgs> | null
  /**
   * Filter, which Union to fetch.
   */
  where: Prisma.UnionWhereUniqueInput
}

/**
 * Union findFirst
 */
export type UnionFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Union
   */
  select?: Prisma.UnionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Union
   */
  omit?: Prisma.UnionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UnionInclude<ExtArgs> | null
  /**
   * Filter, which Union to fetch.
   */
  where?: Prisma.UnionWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Unions to fetch.
   */
  orderBy?: Prisma.UnionOrderByWithRelationInput | Prisma.UnionOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Unions.
   */
  cursor?: Prisma.UnionWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Unions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Unions.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Unions.
   */
  distinct?: Prisma.UnionScalarFieldEnum | Prisma.UnionScalarFieldEnum[]
}

/**
 * Union findFirstOrThrow
 */
export type UnionFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Union
   */
  select?: Prisma.UnionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Union
   */
  omit?: Prisma.UnionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UnionInclude<ExtArgs> | null
  /**
   * Filter, which Union to fetch.
   */
  where?: Prisma.UnionWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Unions to fetch.
   */
  orderBy?: Prisma.UnionOrderByWithRelationInput | Prisma.UnionOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Unions.
   */
  cursor?: Prisma.UnionWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Unions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Unions.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Unions.
   */
  distinct?: Prisma.UnionScalarFieldEnum | Prisma.UnionScalarFieldEnum[]
}

/**
 * Union findMany
 */
export type UnionFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Union
   */
  select?: Prisma.UnionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Union
   */
  omit?: Prisma.UnionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UnionInclude<ExtArgs> | null
  /**
   * Filter, which Unions to fetch.
   */
  where?: Prisma.UnionWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Unions to fetch.
   */
  orderBy?: Prisma.UnionOrderByWithRelationInput | Prisma.UnionOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Unions.
   */
  cursor?: Prisma.UnionWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Unions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Unions.
   */
  skip?: number
  distinct?: Prisma.UnionScalarFieldEnum | Prisma.UnionScalarFieldEnum[]
}

/**
 * Union create
 */
export type UnionCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Union
   */
  select?: Prisma.UnionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Union
   */
  omit?: Prisma.UnionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UnionInclude<ExtArgs> | null
  /**
   * The data needed to create a Union.
   */
  data: Prisma.XOR<Prisma.UnionCreateInput, Prisma.UnionUncheckedCreateInput>
}

/**
 * Union createMany
 */
export type UnionCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Unions.
   */
  data: Prisma.UnionCreateManyInput | Prisma.UnionCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Union createManyAndReturn
 */
export type UnionCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Union
   */
  select?: Prisma.UnionSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Union
   */
  omit?: Prisma.UnionOmit<ExtArgs> | null
  /**
   * The data used to create many Unions.
   */
  data: Prisma.UnionCreateManyInput | Prisma.UnionCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UnionIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * Union update
 */
export type UnionUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Union
   */
  select?: Prisma.UnionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Union
   */
  omit?: Prisma.UnionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UnionInclude<ExtArgs> | null
  /**
   * The data needed to update a Union.
   */
  data: Prisma.XOR<Prisma.UnionUpdateInput, Prisma.UnionUncheckedUpdateInput>
  /**
   * Choose, which Union to update.
   */
  where: Prisma.UnionWhereUniqueInput
}

/**
 * Union updateMany
 */
export type UnionUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Unions.
   */
  data: Prisma.XOR<Prisma.UnionUpdateManyMutationInput, Prisma.UnionUncheckedUpdateManyInput>
  /**
   * Filter which Unions to update
   */
  where?: Prisma.UnionWhereInput
  /**
   * Limit how many Unions to update.
   */
  limit?: number
}

/**
 * Union updateManyAndReturn
 */
export type UnionUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Union
   */
  select?: Prisma.UnionSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Union
   */
  omit?: Prisma.UnionOmit<ExtArgs> | null
  /**
   * The data used to update Unions.
   */
  data: Prisma.XOR<Prisma.UnionUpdateManyMutationInput, Prisma.UnionUncheckedUpdateManyInput>
  /**
   * Filter which Unions to update
   */
  where?: Prisma.UnionWhereInput
  /**
   * Limit how many Unions to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UnionIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * Union upsert
 */
export type UnionUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Union
   */
  select?: Prisma.UnionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Union
   */
  omit?: Prisma.UnionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UnionInclude<ExtArgs> | null
  /**
   * The filter to search for the Union to update in case it exists.
   */
  where: Prisma.UnionWhereUniqueInput
  /**
   * In case the Union found by the `where` argument doesn't exist, create a new Union with this data.
   */
  create: Prisma.XOR<Prisma.UnionCreateInput, Prisma.UnionUncheckedCreateInput>
  /**
   * In case the Union was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.UnionUpdateInput, Prisma.UnionUncheckedUpdateInput>
}

/**
 * Union delete
 */
export type UnionDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Union
   */
  select?: Prisma.UnionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Union
   */
  omit?: Prisma.UnionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UnionInclude<ExtArgs> | null
  /**
   * Filter which Union to delete.
   */
  where: Prisma.UnionWhereUniqueInput
}

/**
 * Union deleteMany
 */
export type UnionDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Unions to delete
   */
  where?: Prisma.UnionWhereInput
  /**
   * Limit how many Unions to delete.
   */
  limit?: number
}

/**
 * Union.tenants
 */
export type Union$tenantsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Tenant
   */
  select?: Prisma.TenantSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Tenant
   */
  omit?: Prisma.TenantOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TenantInclude<ExtArgs> | null
  where?: Prisma.TenantWhereInput
  orderBy?: Prisma.TenantOrderByWithRelationInput | Prisma.TenantOrderByWithRelationInput[]
  cursor?: Prisma.TenantWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.TenantScalarFieldEnum | Prisma.TenantScalarFieldEnum[]
}

/**
 * Union without action
 */
export type UnionDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Union
   */
  select?: Prisma.UnionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Union
   */
  omit?: Prisma.UnionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UnionInclude<ExtArgs> | null
}
