export enum FAMILY_MARITAL_STATUS {
  UNMARRIED = "UNMARRIED",
  MARRIED = "MARRIED",
  WIDOWED = "WIDOWED",
  WIDOWER = "WIDOWER",
}

export enum VITAL_STATUS {
  ALIVE = "ALIVE",
  DECEASED = "DECEASED",
}

export enum FAMILY_APPLICATION_STATUS {
  PENDING = "PENDING",
  APPROVED = "APPROVED",
  REJECTED = "REJECTED",
}
